/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.42
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateJobJson,
  HTTPValidationError,
  JobAccepted,
  JobResult,
  JobStatus,
  JobStatusBatch,
} from '../models/index';
import {
    CreateJobJsonFromJSON,
    CreateJobJsonToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    JobAcceptedFromJSON,
    JobAcceptedToJSON,
    JobResultFromJSON,
    JobResultToJSON,
    JobStatusFromJSON,
    JobStatusToJSON,
    JobStatusBatchFromJSON,
    JobStatusBatchToJSON,
} from '../models/index';

export interface OcrApiCreateJobOcrV1JobsPostRequest {
    createJobJson: CreateJobJson;
}

export interface OcrApiJobResultOcrV1JobsJobIdResultGetRequest {
    jobId: string;
}

export interface OcrApiJobStatusBatchOcrV1JobsGetRequest {
    ids: string;
}

export interface OcrApiJobStatusOcrV1JobsJobIdGetRequest {
    jobId: string;
}

/**
 * 
 */
export class OcrApi extends runtime.BaseAPI {

    /**
     * The service downloads the file with its service account and OCRs every page through Mistral. Returns 202 with a job id to poll. Resubmitting an identical file (same client, same resolved policy) resolves to the prior result during preparation instead of re-paying for OCR; pass options.force to reprocess.
     * Submit an OCR job for a Google Drive file
     */
    async createJobOcrV1JobsPostRaw(requestParameters: OcrApiCreateJobOcrV1JobsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobAccepted>> {
        if (requestParameters['createJobJson'] == null) {
            throw new runtime.RequiredError(
                'createJobJson',
                'Required parameter "createJobJson" was null or undefined when calling createJobOcrV1JobsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Oauth2", []);
        }


        let urlPath = `/ocr/v1/jobs`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateJobJsonToJSON(requestParameters['createJobJson']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobAcceptedFromJSON(jsonValue));
    }

    /**
     * The service downloads the file with its service account and OCRs every page through Mistral. Returns 202 with a job id to poll. Resubmitting an identical file (same client, same resolved policy) resolves to the prior result during preparation instead of re-paying for OCR; pass options.force to reprocess.
     * Submit an OCR job for a Google Drive file
     */
    async createJobOcrV1JobsPost(requestParameters: OcrApiCreateJobOcrV1JobsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobAccepted> {
        const response = await this.createJobOcrV1JobsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch the full result
     */
    async jobResultOcrV1JobsJobIdResultGetRaw(requestParameters: OcrApiJobResultOcrV1JobsJobIdResultGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobResult>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling jobResultOcrV1JobsJobIdResultGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Oauth2", []);
        }


        let urlPath = `/ocr/v1/jobs/{job_id}/result`;
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobResultFromJSON(jsonValue));
    }

    /**
     * Fetch the full result
     */
    async jobResultOcrV1JobsJobIdResultGet(requestParameters: OcrApiJobResultOcrV1JobsJobIdResultGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobResult> {
        const response = await this.jobResultOcrV1JobsJobIdResultGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Comma-separated `ids` (e.g. `?ids=a,b,c`). Returns the status of the caller\'s own jobs among them; unknown, expired, or other clients\' ids come back in `not_found`. At most 100 ids per call.
     * Poll many jobs in one request
     */
    async jobStatusBatchOcrV1JobsGetRaw(requestParameters: OcrApiJobStatusBatchOcrV1JobsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobStatusBatch>> {
        if (requestParameters['ids'] == null) {
            throw new runtime.RequiredError(
                'ids',
                'Required parameter "ids" was null or undefined when calling jobStatusBatchOcrV1JobsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Oauth2", []);
        }


        let urlPath = `/ocr/v1/jobs`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobStatusBatchFromJSON(jsonValue));
    }

    /**
     * Comma-separated `ids` (e.g. `?ids=a,b,c`). Returns the status of the caller\'s own jobs among them; unknown, expired, or other clients\' ids come back in `not_found`. At most 100 ids per call.
     * Poll many jobs in one request
     */
    async jobStatusBatchOcrV1JobsGet(requestParameters: OcrApiJobStatusBatchOcrV1JobsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobStatusBatch> {
        const response = await this.jobStatusBatchOcrV1JobsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Poll one job
     */
    async jobStatusOcrV1JobsJobIdGetRaw(requestParameters: OcrApiJobStatusOcrV1JobsJobIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobStatus>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling jobStatusOcrV1JobsJobIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Oauth2", []);
        }


        let urlPath = `/ocr/v1/jobs/{job_id}`;
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobStatusFromJSON(jsonValue));
    }

    /**
     * Poll one job
     */
    async jobStatusOcrV1JobsJobIdGet(requestParameters: OcrApiJobStatusOcrV1JobsJobIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobStatus> {
        const response = await this.jobStatusOcrV1JobsJobIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
