/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.37910073660
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ContractTerms,
  RawContractTerms,
  UpdateRawContractContractTerms422Response,
} from '../models/index';
import {
    ContractTermsFromJSON,
    ContractTermsToJSON,
    RawContractTermsFromJSON,
    RawContractTermsToJSON,
    UpdateRawContractContractTerms422ResponseFromJSON,
    UpdateRawContractContractTerms422ResponseToJSON,
} from '../models/index';

export interface RawContractsApiGetRawContractContractTermsRequest {
    rawContractId: number;
}

export interface RawContractsApiUpdateRawContractContractTermsRequest {
    rawContractId: number;
    contractTerms: ContractTerms;
}

/**
 * 
 */
export class RawContractsApi extends runtime.BaseAPI {

    /**
     * Return the structured contract terms stored on a RawContract (WINAD-10633), and whether the contract\'s OCR text has changed since they were read (contract_terms_stale).
     */
    async getRawContractContractTermsRaw(requestParameters: RawContractsApiGetRawContractContractTermsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RawContractTerms>> {
        if (requestParameters['rawContractId'] == null) {
            throw new runtime.RequiredError(
                'rawContractId',
                'Required parameter "rawContractId" was null or undefined when calling getRawContractContractTerms().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Oauth2", []);
        }


        let urlPath = `/api/v1/raw_contracts/{raw_contractId}/contract_terms`;
        urlPath = urlPath.replace(`{${"raw_contractId"}}`, encodeURIComponent(String(requestParameters['rawContractId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RawContractTermsFromJSON(jsonValue));
    }

    /**
     * Return the structured contract terms stored on a RawContract (WINAD-10633), and whether the contract\'s OCR text has changed since they were read (contract_terms_stale).
     */
    async getRawContractContractTerms(requestParameters: RawContractsApiGetRawContractContractTermsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RawContractTerms> {
        const response = await this.getRawContractContractTermsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Replace the whole contract_terms document on a RawContract (WINAD-10633). The body is the document itself: a JSON object with a `schema` string (for example \"ticketing-terms-v1\" or \"coach-terms-v1\") and a `source` object (`rendition_sha256`, `run_id`, `extracted_at`, `method`). Every other key is a term and is stored as sent; terms are not validated beyond the envelope. `source.rendition_sha256` is the SHA-256 (hex) of the OCR text the terms were read from (the `text` returned by GET /raw_contracts/{id}/ocr_text); when that text later changes, `contract_terms_stale` is true.  Every change is recorded in the audit trail (who, old and new value, when), so this requires the winad_write scope and a user-backed token (client-credentials tokens are refused) with permission to update the RawContract. 
     */
    async updateRawContractContractTermsRaw(requestParameters: RawContractsApiUpdateRawContractContractTermsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RawContractTerms>> {
        if (requestParameters['rawContractId'] == null) {
            throw new runtime.RequiredError(
                'rawContractId',
                'Required parameter "rawContractId" was null or undefined when calling updateRawContractContractTerms().'
            );
        }

        if (requestParameters['contractTerms'] == null) {
            throw new runtime.RequiredError(
                'contractTerms',
                'Required parameter "contractTerms" was null or undefined when calling updateRawContractContractTerms().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Oauth2", []);
        }


        let urlPath = `/api/v1/raw_contracts/{raw_contractId}/contract_terms`;
        urlPath = urlPath.replace(`{${"raw_contractId"}}`, encodeURIComponent(String(requestParameters['rawContractId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ContractTermsToJSON(requestParameters['contractTerms']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RawContractTermsFromJSON(jsonValue));
    }

    /**
     * Replace the whole contract_terms document on a RawContract (WINAD-10633). The body is the document itself: a JSON object with a `schema` string (for example \"ticketing-terms-v1\" or \"coach-terms-v1\") and a `source` object (`rendition_sha256`, `run_id`, `extracted_at`, `method`). Every other key is a term and is stored as sent; terms are not validated beyond the envelope. `source.rendition_sha256` is the SHA-256 (hex) of the OCR text the terms were read from (the `text` returned by GET /raw_contracts/{id}/ocr_text); when that text later changes, `contract_terms_stale` is true.  Every change is recorded in the audit trail (who, old and new value, when), so this requires the winad_write scope and a user-backed token (client-credentials tokens are refused) with permission to update the RawContract. 
     */
    async updateRawContractContractTerms(requestParameters: RawContractsApiUpdateRawContractContractTermsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RawContractTerms> {
        const response = await this.updateRawContractContractTermsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
