/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.26
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FinancialQc,
  FoiaFollowUpReportResponse,
  InvoiceReportResult,
} from '../models/index';
import {
    FinancialQcFromJSON,
    FinancialQcToJSON,
    FoiaFollowUpReportResponseFromJSON,
    FoiaFollowUpReportResponseToJSON,
    InvoiceReportResultFromJSON,
    InvoiceReportResultToJSON,
} from '../models/index';

export interface ReportingApiGetCoachContractRequestsRequest {
    page?: number;
    q?: object;
}

export interface ReportingApiGetCoachHistoryRequest {
    page?: number;
    q?: object;
}

export interface ReportingApiGetConferenceshipsRequest {
    page?: number;
    q?: object;
}

export interface ReportingApiGetFoiaDetailsRequest {
    page?: number;
    q?: object;
}

export interface ReportingApiGetFoiaFollowUpReportRequest {
    scope: GetFoiaFollowUpReportScopeEnum;
    page?: number;
    perPage?: number;
    sortBy?: GetFoiaFollowUpReportSortByEnum;
    foiaLabelId?: number;
    schoolId?: number;
    state?: string;
    followUpDateLte?: Date;
    includeNotDue?: boolean;
    showProcessedToday?: GetFoiaFollowUpReportShowProcessedTodayEnum;
    includeDirectContact?: boolean;
}

export interface ReportingApiGetGamesRequest {
    page?: number;
    q?: object;
}

export interface ReportingApiGetInvoicesRequest {
    page?: number;
    q?: object;
}

export interface ReportingApiGetSchoolContractRequestsRequest {
    page?: number;
    q?: object;
}

export interface ReportingApiGetSchoolsFinancialsQcRequest {
    page?: number;
    q?: object;
}

export interface ReportingApiGetSubscriptionsRequest {
    page?: number;
    q?: object;
}

/**
 * 
 */
export class ReportingApi extends runtime.BaseAPI {

    /**
     * Retrieve some or all coach contract requests
     */
    async getCoachContractRequestsRaw(requestParameters: ReportingApiGetCoachContractRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Oauth2", []);
        }


        let urlPath = `/api/v1/reports/coach_contract_requests`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Retrieve some or all coach contract requests
     */
    async getCoachContractRequests(requestParameters: ReportingApiGetCoachContractRequestsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getCoachContractRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve some or all coach history
     */
    async getCoachHistoryRaw(requestParameters: ReportingApiGetCoachHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Oauth2", []);
        }


        let urlPath = `/api/v1/reports/coach_history`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Retrieve some or all coach history
     */
    async getCoachHistory(requestParameters: ReportingApiGetCoachHistoryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getCoachHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve some or all conferenceships
     */
    async getConferenceshipsRaw(requestParameters: ReportingApiGetConferenceshipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Oauth2", []);
        }


        let urlPath = `/api/v1/reports/conferenceships`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Retrieve some or all conferenceships
     */
    async getConferenceships(requestParameters: ReportingApiGetConferenceshipsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getConferenceshipsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve some or all foia details
     */
    async getFoiaDetailsRaw(requestParameters: ReportingApiGetFoiaDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Oauth2", []);
        }


        let urlPath = `/api/v1/reports/foia_details`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Retrieve some or all foia details
     */
    async getFoiaDetails(requestParameters: ReportingApiGetFoiaDetailsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getFoiaDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve read-only FOIA follow-up rows for Codex follow-up drafting and FOIA freshness dashboards
     */
    async getFoiaFollowUpReportRaw(requestParameters: ReportingApiGetFoiaFollowUpReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FoiaFollowUpReportResponse>> {
        if (requestParameters['scope'] == null) {
            throw new runtime.RequiredError(
                'scope',
                'Required parameter "scope" was null or undefined when calling getFoiaFollowUpReport().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sort_by'] = requestParameters['sortBy'];
        }

        if (requestParameters['foiaLabelId'] != null) {
            queryParameters['foia_label_id'] = requestParameters['foiaLabelId'];
        }

        if (requestParameters['schoolId'] != null) {
            queryParameters['school_id'] = requestParameters['schoolId'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['followUpDateLte'] != null) {
            queryParameters['follow_up_date_lte'] = (requestParameters['followUpDateLte'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['includeNotDue'] != null) {
            queryParameters['include_not_due'] = requestParameters['includeNotDue'];
        }

        if (requestParameters['showProcessedToday'] != null) {
            queryParameters['show_processed_today'] = requestParameters['showProcessedToday'];
        }

        if (requestParameters['includeDirectContact'] != null) {
            queryParameters['include_direct_contact'] = requestParameters['includeDirectContact'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Oauth2", []);
        }


        let urlPath = `/api/v1/reports/foia_follow_up_report`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FoiaFollowUpReportResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve read-only FOIA follow-up rows for Codex follow-up drafting and FOIA freshness dashboards
     */
    async getFoiaFollowUpReport(requestParameters: ReportingApiGetFoiaFollowUpReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FoiaFollowUpReportResponse> {
        const response = await this.getFoiaFollowUpReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve some or all games
     */
    async getGamesRaw(requestParameters: ReportingApiGetGamesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Oauth2", []);
        }


        let urlPath = `/api/v1/reports/games`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Retrieve some or all games
     */
    async getGames(requestParameters: ReportingApiGetGamesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getGamesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve some or all client invoices
     */
    async getInvoicesRaw(requestParameters: ReportingApiGetInvoicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceReportResult>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Oauth2", []);
        }


        let urlPath = `/api/v1/reports/invoices`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceReportResultFromJSON(jsonValue));
    }

    /**
     * Retrieve some or all client invoices
     */
    async getInvoices(requestParameters: ReportingApiGetInvoicesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceReportResult> {
        const response = await this.getInvoicesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve some or all school contract requests
     */
    async getSchoolContractRequestsRaw(requestParameters: ReportingApiGetSchoolContractRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Oauth2", []);
        }


        let urlPath = `/api/v1/reports/school_contract_requests`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Retrieve some or all school contract requests
     */
    async getSchoolContractRequests(requestParameters: ReportingApiGetSchoolContractRequestsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getSchoolContractRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve schools with thier financials qc
     */
    async getSchoolsFinancialsQcRaw(requestParameters: ReportingApiGetSchoolsFinancialsQcRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FinancialQc>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Oauth2", []);
        }


        let urlPath = `/api/v1/financials_qc`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FinancialQcFromJSON(jsonValue));
    }

    /**
     * Retrieve schools with thier financials qc
     */
    async getSchoolsFinancialsQc(requestParameters: ReportingApiGetSchoolsFinancialsQcRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FinancialQc> {
        const response = await this.getSchoolsFinancialsQcRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve subscriptions
     */
    async getSubscriptionsRaw(requestParameters: ReportingApiGetSubscriptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Oauth2", []);
        }


        let urlPath = `/api/v1/reports/subscriptions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Retrieve subscriptions
     */
    async getSubscriptions(requestParameters: ReportingApiGetSubscriptionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getSubscriptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetFoiaFollowUpReportScopeEnum = {
    DueFollowupQueue: 'due_followup_queue',
    FreshnessDashboard: 'freshness_dashboard'
} as const;
export type GetFoiaFollowUpReportScopeEnum = typeof GetFoiaFollowUpReportScopeEnum[keyof typeof GetFoiaFollowUpReportScopeEnum];
/**
 * @export
 */
export const GetFoiaFollowUpReportSortByEnum = {
    FollowUpDateAsc: 'follow_up_date_asc',
    FollowUpDateDesc: 'follow_up_date_desc',
    DateSentAsc: 'date_sent_asc',
    DateSentDesc: 'date_sent_desc',
    UpdatedBySchoolAsc: 'updated_by_school_asc',
    UpdatedBySchoolDesc: 'updated_by_school_desc',
    UpdatedByWiAsc: 'updated_by_wi_asc',
    UpdatedByWiDesc: 'updated_by_wi_desc',
    IdAsc: 'id_asc',
    IdDesc: 'id_desc'
} as const;
export type GetFoiaFollowUpReportSortByEnum = typeof GetFoiaFollowUpReportSortByEnum[keyof typeof GetFoiaFollowUpReportSortByEnum];
/**
 * @export
 */
export const GetFoiaFollowUpReportShowProcessedTodayEnum = {
    False: 'false',
    True: 'true',
    All: 'all'
} as const;
export type GetFoiaFollowUpReportShowProcessedTodayEnum = typeof GetFoiaFollowUpReportShowProcessedTodayEnum[keyof typeof GetFoiaFollowUpReportShowProcessedTodayEnum];
