/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountUser
 */
export interface AccountUser {
    /**
     * 
     * @type {number}
     * @memberof AccountUser
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AccountUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountUser
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountUser
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountUser
     */
    title?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AccountUser
     */
    isAccountAdmin?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccountUser
     */
    abilities?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccountUser
     */
    scheduleSports?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AccountUser
     */
    permissibleSports?: Array<string> | null;
}

/**
 * Check if a given object implements the AccountUser interface.
 */
export function instanceOfAccountUser(value: object): value is AccountUser {
    return true;
}

export function AccountUserFromJSON(json: any): AccountUser {
    return AccountUserFromJSONTyped(json, false);
}

export function AccountUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'state': json['state'] == null ? undefined : json['state'],
        'title': json['title'] == null ? undefined : json['title'],
        'isAccountAdmin': json['is_account_admin'] == null ? undefined : json['is_account_admin'],
        'abilities': json['abilities'] == null ? undefined : json['abilities'],
        'scheduleSports': json['schedule_sports'] == null ? undefined : json['schedule_sports'],
        'permissibleSports': json['permissible_sports'] == null ? undefined : json['permissible_sports'],
    };
}

export function AccountUserToJSON(json: any): AccountUser {
    return AccountUserToJSONTyped(json, false);
}

export function AccountUserToJSONTyped(value?: AccountUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'state': value['state'],
        'title': value['title'],
        'is_account_admin': value['isAccountAdmin'],
        'abilities': value['abilities'],
        'schedule_sports': value['scheduleSports'],
        'permissible_sports': value['permissibleSports'],
    };
}

