/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31383324583
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminRiNoteInputRiNoteQuickActions } from './AdminRiNoteInputRiNoteQuickActions';
import {
    AdminRiNoteInputRiNoteQuickActionsFromJSON,
    AdminRiNoteInputRiNoteQuickActionsFromJSONTyped,
    AdminRiNoteInputRiNoteQuickActionsToJSON,
    AdminRiNoteInputRiNoteQuickActionsToJSONTyped,
} from './AdminRiNoteInputRiNoteQuickActions';

/**
 * 
 * @export
 * @interface AdminRiNoteInputRiNote
 */
export interface AdminRiNoteInputRiNote {
    /**
     * 
     * @type {string}
     * @memberof AdminRiNoteInputRiNote
     */
    note?: string;
    /**
     * Author of the note. Defaults to the current admin user when omitted.
     * @type {number}
     * @memberof AdminRiNoteInputRiNote
     */
    userId?: number;
    /**
     * 
     * @type {AdminRiNoteInputRiNoteQuickActions}
     * @memberof AdminRiNoteInputRiNote
     */
    quickActions?: AdminRiNoteInputRiNoteQuickActions | null;
}

/**
 * Check if a given object implements the AdminRiNoteInputRiNote interface.
 */
export function instanceOfAdminRiNoteInputRiNote(value: object): value is AdminRiNoteInputRiNote {
    return true;
}

export function AdminRiNoteInputRiNoteFromJSON(json: any): AdminRiNoteInputRiNote {
    return AdminRiNoteInputRiNoteFromJSONTyped(json, false);
}

export function AdminRiNoteInputRiNoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminRiNoteInputRiNote {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'] == null ? undefined : json['note'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'quickActions': json['quick_actions'] == null ? undefined : AdminRiNoteInputRiNoteQuickActionsFromJSON(json['quick_actions']),
    };
}

export function AdminRiNoteInputRiNoteToJSON(json: any): AdminRiNoteInputRiNote {
    return AdminRiNoteInputRiNoteToJSONTyped(json, false);
}

export function AdminRiNoteInputRiNoteToJSONTyped(value?: AdminRiNoteInputRiNote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'note': value['note'],
        'user_id': value['userId'],
        'quick_actions': AdminRiNoteInputRiNoteQuickActionsToJSON(value['quickActions']),
    };
}

