/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31393187616
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IdName } from './IdName';
import {
    IdNameFromJSON,
    IdNameFromJSONTyped,
    IdNameToJSON,
    IdNameToJSONTyped,
} from './IdName';

/**
 * 
 * @export
 * @interface AdminCoachMergeLogListMetaFilterOptions
 */
export interface AdminCoachMergeLogListMetaFilterOptions {
    /**
     * 
     * @type {Array<IdName>}
     * @memberof AdminCoachMergeLogListMetaFilterOptions
     */
    users?: Array<IdName>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdminCoachMergeLogListMetaFilterOptions
     */
    statuses?: Array<string>;
}

/**
 * Check if a given object implements the AdminCoachMergeLogListMetaFilterOptions interface.
 */
export function instanceOfAdminCoachMergeLogListMetaFilterOptions(value: object): value is AdminCoachMergeLogListMetaFilterOptions {
    return true;
}

export function AdminCoachMergeLogListMetaFilterOptionsFromJSON(json: any): AdminCoachMergeLogListMetaFilterOptions {
    return AdminCoachMergeLogListMetaFilterOptionsFromJSONTyped(json, false);
}

export function AdminCoachMergeLogListMetaFilterOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminCoachMergeLogListMetaFilterOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(IdNameFromJSON)),
        'statuses': json['statuses'] == null ? undefined : json['statuses'],
    };
}

export function AdminCoachMergeLogListMetaFilterOptionsToJSON(json: any): AdminCoachMergeLogListMetaFilterOptions {
    return AdminCoachMergeLogListMetaFilterOptionsToJSONTyped(json, false);
}

export function AdminCoachMergeLogListMetaFilterOptionsToJSONTyped(value?: AdminCoachMergeLogListMetaFilterOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(IdNameToJSON)),
        'statuses': value['statuses'],
    };
}

