/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31383324583
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminYoutubeVideoCoach
 */
export interface AdminYoutubeVideoCoach {
    /**
     * 
     * @type {number}
     * @memberof AdminYoutubeVideoCoach
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AdminYoutubeVideoCoach
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminYoutubeVideoCoach
     */
    avatarUrl?: string | null;
}

/**
 * Check if a given object implements the AdminYoutubeVideoCoach interface.
 */
export function instanceOfAdminYoutubeVideoCoach(value: object): value is AdminYoutubeVideoCoach {
    return true;
}

export function AdminYoutubeVideoCoachFromJSON(json: any): AdminYoutubeVideoCoach {
    return AdminYoutubeVideoCoachFromJSONTyped(json, false);
}

export function AdminYoutubeVideoCoachFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminYoutubeVideoCoach {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
    };
}

export function AdminYoutubeVideoCoachToJSON(json: any): AdminYoutubeVideoCoach {
    return AdminYoutubeVideoCoachToJSONTyped(json, false);
}

export function AdminYoutubeVideoCoachToJSONTyped(value?: AdminYoutubeVideoCoach | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'avatar_url': value['avatarUrl'],
    };
}

