/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31393187616
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminContractRawContract } from './AdminContractRawContract';
import {
    AdminContractRawContractFromJSON,
    AdminContractRawContractFromJSONTyped,
    AdminContractRawContractToJSON,
    AdminContractRawContractToJSONTyped,
} from './AdminContractRawContract';
import type { AdminContractCoach } from './AdminContractCoach';
import {
    AdminContractCoachFromJSON,
    AdminContractCoachFromJSONTyped,
    AdminContractCoachToJSON,
    AdminContractCoachToJSONTyped,
} from './AdminContractCoach';

/**
 * 
 * @export
 * @interface AdminContract
 */
export interface AdminContract {
    /**
     * 
     * @type {number}
     * @memberof AdminContract
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof AdminContract
     */
    startOn?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AdminContract
     */
    endOn?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminContract
     */
    atWill?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminContract
     */
    contingentChange?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AdminContract
     */
    executedOn?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AdminContract
     */
    expiresOn?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminContract
     */
    verified?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AdminContract
     */
    driveId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AdminContract
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdminContract
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof AdminContract
     */
    coachId?: number | null;
    /**
     * 
     * @type {AdminContractCoach}
     * @memberof AdminContract
     */
    coach?: AdminContractCoach | null;
    /**
     * 
     * @type {AdminContractRawContract}
     * @memberof AdminContract
     */
    rawContract?: AdminContractRawContract | null;
}

/**
 * Check if a given object implements the AdminContract interface.
 */
export function instanceOfAdminContract(value: object): value is AdminContract {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AdminContractFromJSON(json: any): AdminContract {
    return AdminContractFromJSONTyped(json, false);
}

export function AdminContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminContract {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'startOn': json['start_on'] == null ? undefined : (new Date(json['start_on'])),
        'endOn': json['end_on'] == null ? undefined : (new Date(json['end_on'])),
        'atWill': json['at_will'] == null ? undefined : json['at_will'],
        'contingentChange': json['contingent_change'] == null ? undefined : json['contingent_change'],
        'executedOn': json['executed_on'] == null ? undefined : (new Date(json['executed_on'])),
        'expiresOn': json['expires_on'] == null ? undefined : (new Date(json['expires_on'])),
        'verified': json['verified'] == null ? undefined : json['verified'],
        'driveId': json['drive_id'] == null ? undefined : json['drive_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'coachId': json['coach_id'] == null ? undefined : json['coach_id'],
        'coach': json['coach'] == null ? undefined : AdminContractCoachFromJSON(json['coach']),
        'rawContract': json['raw_contract'] == null ? undefined : AdminContractRawContractFromJSON(json['raw_contract']),
    };
}

export function AdminContractToJSON(json: any): AdminContract {
    return AdminContractToJSONTyped(json, false);
}

export function AdminContractToJSONTyped(value?: AdminContract | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'start_on': value['startOn'] == null ? value['startOn'] : value['startOn'].toISOString().substring(0,10),
        'end_on': value['endOn'] == null ? value['endOn'] : value['endOn'].toISOString().substring(0,10),
        'at_will': value['atWill'],
        'contingent_change': value['contingentChange'],
        'executed_on': value['executedOn'] == null ? value['executedOn'] : value['executedOn'].toISOString().substring(0,10),
        'expires_on': value['expiresOn'] == null ? value['expiresOn'] : value['expiresOn'].toISOString().substring(0,10),
        'verified': value['verified'],
        'drive_id': value['driveId'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'coach_id': value['coachId'],
        'coach': AdminContractCoachToJSON(value['coach']),
        'raw_contract': AdminContractRawContractToJSON(value['rawContract']),
    };
}

