/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31383324583
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminRawContractGameMatch
 */
export interface AdminRawContractGameMatch {
    /**
     * 
     * @type {number}
     * @memberof AdminRawContractGameMatch
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AdminRawContractGameMatch
     */
    assetFileName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AdminRawContractGameMatch
     */
    homeSchoolId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AdminRawContractGameMatch
     */
    homeSchoolName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AdminRawContractGameMatch
     */
    awaySchoolId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AdminRawContractGameMatch
     */
    awaySchoolName?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof AdminRawContractGameMatch
     */
    years?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof AdminRawContractGameMatch
     */
    label?: string | null;
}

/**
 * Check if a given object implements the AdminRawContractGameMatch interface.
 */
export function instanceOfAdminRawContractGameMatch(value: object): value is AdminRawContractGameMatch {
    return true;
}

export function AdminRawContractGameMatchFromJSON(json: any): AdminRawContractGameMatch {
    return AdminRawContractGameMatchFromJSONTyped(json, false);
}

export function AdminRawContractGameMatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminRawContractGameMatch {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'assetFileName': json['asset_file_name'] == null ? undefined : json['asset_file_name'],
        'homeSchoolId': json['home_school_id'] == null ? undefined : json['home_school_id'],
        'homeSchoolName': json['home_school_name'] == null ? undefined : json['home_school_name'],
        'awaySchoolId': json['away_school_id'] == null ? undefined : json['away_school_id'],
        'awaySchoolName': json['away_school_name'] == null ? undefined : json['away_school_name'],
        'years': json['years'] == null ? undefined : json['years'],
        'label': json['label'] == null ? undefined : json['label'],
    };
}

export function AdminRawContractGameMatchToJSON(json: any): AdminRawContractGameMatch {
    return AdminRawContractGameMatchToJSONTyped(json, false);
}

export function AdminRawContractGameMatchToJSONTyped(value?: AdminRawContractGameMatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'asset_file_name': value['assetFileName'],
        'home_school_id': value['homeSchoolId'],
        'home_school_name': value['homeSchoolName'],
        'away_school_id': value['awaySchoolId'],
        'away_school_name': value['awaySchoolName'],
        'years': value['years'],
        'label': value['label'],
    };
}

