/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.36578055122
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminInvoiceCreateInvoiceRecipientEdits } from './AdminInvoiceCreateInvoiceRecipientEdits';
import {
    AdminInvoiceCreateInvoiceRecipientEditsFromJSON,
    AdminInvoiceCreateInvoiceRecipientEditsFromJSONTyped,
    AdminInvoiceCreateInvoiceRecipientEditsToJSON,
    AdminInvoiceCreateInvoiceRecipientEditsToJSONTyped,
} from './AdminInvoiceCreateInvoiceRecipientEdits';

/**
 * 
 * @export
 * @interface AdminInvoiceCreateInvoice
 */
export interface AdminInvoiceCreateInvoice {
    /**
     * 
     * @type {number}
     * @memberof AdminInvoiceCreateInvoice
     */
    subscriptionYearId: number;
    /**
     * 
     * @type {Date}
     * @memberof AdminInvoiceCreateInvoice
     */
    invoiceDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof AdminInvoiceCreateInvoice
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof AdminInvoiceCreateInvoice
     */
    amountCents?: number;
    /**
     * 
     * @type {Date}
     * @memberof AdminInvoiceCreateInvoice
     */
    dueDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof AdminInvoiceCreateInvoice
     */
    dueDateNotes?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminInvoiceCreateInvoice
     */
    purchaseOrderNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminInvoiceCreateInvoice
     */
    notes?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AdminInvoiceCreateInvoice
     */
    reminders?: boolean;
    /**
     * 
     * @type {AdminInvoiceCreateInvoiceRecipientEdits}
     * @memberof AdminInvoiceCreateInvoice
     */
    recipientEdits?: AdminInvoiceCreateInvoiceRecipientEdits;
}

/**
 * Check if a given object implements the AdminInvoiceCreateInvoice interface.
 */
export function instanceOfAdminInvoiceCreateInvoice(value: object): value is AdminInvoiceCreateInvoice {
    if (!('subscriptionYearId' in value) || value['subscriptionYearId'] === undefined) return false;
    return true;
}

export function AdminInvoiceCreateInvoiceFromJSON(json: any): AdminInvoiceCreateInvoice {
    return AdminInvoiceCreateInvoiceFromJSONTyped(json, false);
}

export function AdminInvoiceCreateInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminInvoiceCreateInvoice {
    if (json == null) {
        return json;
    }
    return {
        
        'subscriptionYearId': json['subscription_year_id'],
        'invoiceDate': json['invoice_date'] == null ? undefined : (new Date(json['invoice_date'])),
        'description': json['description'] == null ? undefined : json['description'],
        'amountCents': json['amount_cents'] == null ? undefined : json['amount_cents'],
        'dueDate': json['due_date'] == null ? undefined : (new Date(json['due_date'])),
        'dueDateNotes': json['due_date_notes'] == null ? undefined : json['due_date_notes'],
        'purchaseOrderNumber': json['purchase_order_number'] == null ? undefined : json['purchase_order_number'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'reminders': json['reminders'] == null ? undefined : json['reminders'],
        'recipientEdits': json['recipient_edits'] == null ? undefined : AdminInvoiceCreateInvoiceRecipientEditsFromJSON(json['recipient_edits']),
    };
}

export function AdminInvoiceCreateInvoiceToJSON(json: any): AdminInvoiceCreateInvoice {
    return AdminInvoiceCreateInvoiceToJSONTyped(json, false);
}

export function AdminInvoiceCreateInvoiceToJSONTyped(value?: AdminInvoiceCreateInvoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscription_year_id': value['subscriptionYearId'],
        'invoice_date': value['invoiceDate'] == null ? value['invoiceDate'] : value['invoiceDate'].toISOString().substring(0,10),
        'description': value['description'],
        'amount_cents': value['amountCents'],
        'due_date': value['dueDate'] == null ? value['dueDate'] : value['dueDate'].toISOString().substring(0,10),
        'due_date_notes': value['dueDateNotes'],
        'purchase_order_number': value['purchaseOrderNumber'],
        'notes': value['notes'],
        'reminders': value['reminders'],
        'recipient_edits': AdminInvoiceCreateInvoiceRecipientEditsToJSON(value['recipientEdits']),
    };
}

