/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.55.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ApparelDealUpdateSportsInner
 * 
 * @export
 */
export type ApparelDealUpdateSportsInner = number | string;

export function ApparelDealUpdateSportsInnerFromJSON(json: any): ApparelDealUpdateSportsInner {
    return ApparelDealUpdateSportsInnerFromJSONTyped(json, false);
}

export function ApparelDealUpdateSportsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApparelDealUpdateSportsInner {
    if (json == null) {
        return json;
    }
    if (typeof json === 'number') {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function ApparelDealUpdateSportsInnerToJSON(json: any): any {
    return ApparelDealUpdateSportsInnerToJSONTyped(json, false);
}

export function ApparelDealUpdateSportsInnerToJSONTyped(value?: ApparelDealUpdateSportsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'number') {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

