/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.57-dev.9983
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AthleticProfileShowSportOverviewGuaranteesUpcomingInner } from './AthleticProfileShowSportOverviewGuaranteesUpcomingInner';
import {
    AthleticProfileShowSportOverviewGuaranteesUpcomingInnerFromJSON,
    AthleticProfileShowSportOverviewGuaranteesUpcomingInnerFromJSONTyped,
    AthleticProfileShowSportOverviewGuaranteesUpcomingInnerToJSON,
    AthleticProfileShowSportOverviewGuaranteesUpcomingInnerToJSONTyped,
} from './AthleticProfileShowSportOverviewGuaranteesUpcomingInner';

/**
 * 
 * @export
 * @interface AthleticProfileShowSportOverviewGuarantees
 */
export interface AthleticProfileShowSportOverviewGuarantees {
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportOverviewGuarantees
     */
    agreementsCount?: number;
    /**
     * Agreements whose amount is filed (not comp_tbd)
     * @type {number}
     * @memberof AthleticProfileShowSportOverviewGuarantees
     */
    pricedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportOverviewGuarantees
     */
    outCents?: number;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportOverviewGuarantees
     */
    inCents?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AthleticProfileShowSportOverviewGuarantees
     */
    allOnFile?: boolean;
    /**
     * 
     * @type {Array<AthleticProfileShowSportOverviewGuaranteesUpcomingInner>}
     * @memberof AthleticProfileShowSportOverviewGuarantees
     */
    upcoming?: Array<AthleticProfileShowSportOverviewGuaranteesUpcomingInner>;
}

/**
 * Check if a given object implements the AthleticProfileShowSportOverviewGuarantees interface.
 */
export function instanceOfAthleticProfileShowSportOverviewGuarantees(value: object): value is AthleticProfileShowSportOverviewGuarantees {
    return true;
}

export function AthleticProfileShowSportOverviewGuaranteesFromJSON(json: any): AthleticProfileShowSportOverviewGuarantees {
    return AthleticProfileShowSportOverviewGuaranteesFromJSONTyped(json, false);
}

export function AthleticProfileShowSportOverviewGuaranteesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AthleticProfileShowSportOverviewGuarantees {
    if (json == null) {
        return json;
    }
    return {
        
        'agreementsCount': json['agreements_count'] == null ? undefined : json['agreements_count'],
        'pricedCount': json['priced_count'] == null ? undefined : json['priced_count'],
        'outCents': json['out_cents'] == null ? undefined : json['out_cents'],
        'inCents': json['in_cents'] == null ? undefined : json['in_cents'],
        'allOnFile': json['all_on_file'] == null ? undefined : json['all_on_file'],
        'upcoming': json['upcoming'] == null ? undefined : ((json['upcoming'] as Array<any>).map(AthleticProfileShowSportOverviewGuaranteesUpcomingInnerFromJSON)),
    };
}

export function AthleticProfileShowSportOverviewGuaranteesToJSON(json: any): AthleticProfileShowSportOverviewGuarantees {
    return AthleticProfileShowSportOverviewGuaranteesToJSONTyped(json, false);
}

export function AthleticProfileShowSportOverviewGuaranteesToJSONTyped(value?: AthleticProfileShowSportOverviewGuarantees | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agreements_count': value['agreementsCount'],
        'priced_count': value['pricedCount'],
        'out_cents': value['outCents'],
        'in_cents': value['inCents'],
        'all_on_file': value['allOnFile'],
        'upcoming': value['upcoming'] == null ? undefined : ((value['upcoming'] as Array<any>).map(AthleticProfileShowSportOverviewGuaranteesUpcomingInnerToJSON)),
    };
}

