/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.33871411157
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AthleticProfileShowSportFinancialsCostBuildGuaranteesNet
 */
export interface AthleticProfileShowSportFinancialsCostBuildGuaranteesNet {
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportFinancialsCostBuildGuaranteesNet
     */
    outCents?: number;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportFinancialsCostBuildGuaranteesNet
     */
    inCents?: number;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportFinancialsCostBuildGuaranteesNet
     */
    agreementsCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportFinancialsCostBuildGuaranteesNet
     */
    pricedCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AthleticProfileShowSportFinancialsCostBuildGuaranteesNet
     */
    allOnFile?: boolean;
}

/**
 * Check if a given object implements the AthleticProfileShowSportFinancialsCostBuildGuaranteesNet interface.
 */
export function instanceOfAthleticProfileShowSportFinancialsCostBuildGuaranteesNet(value: object): value is AthleticProfileShowSportFinancialsCostBuildGuaranteesNet {
    return true;
}

export function AthleticProfileShowSportFinancialsCostBuildGuaranteesNetFromJSON(json: any): AthleticProfileShowSportFinancialsCostBuildGuaranteesNet {
    return AthleticProfileShowSportFinancialsCostBuildGuaranteesNetFromJSONTyped(json, false);
}

export function AthleticProfileShowSportFinancialsCostBuildGuaranteesNetFromJSONTyped(json: any, ignoreDiscriminator: boolean): AthleticProfileShowSportFinancialsCostBuildGuaranteesNet {
    if (json == null) {
        return json;
    }
    return {
        
        'outCents': json['out_cents'] == null ? undefined : json['out_cents'],
        'inCents': json['in_cents'] == null ? undefined : json['in_cents'],
        'agreementsCount': json['agreements_count'] == null ? undefined : json['agreements_count'],
        'pricedCount': json['priced_count'] == null ? undefined : json['priced_count'],
        'allOnFile': json['all_on_file'] == null ? undefined : json['all_on_file'],
    };
}

export function AthleticProfileShowSportFinancialsCostBuildGuaranteesNetToJSON(json: any): AthleticProfileShowSportFinancialsCostBuildGuaranteesNet {
    return AthleticProfileShowSportFinancialsCostBuildGuaranteesNetToJSONTyped(json, false);
}

export function AthleticProfileShowSportFinancialsCostBuildGuaranteesNetToJSONTyped(value?: AthleticProfileShowSportFinancialsCostBuildGuaranteesNet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'out_cents': value['outCents'],
        'in_cents': value['inCents'],
        'agreements_count': value['agreementsCount'],
        'priced_count': value['pricedCount'],
        'all_on_file': value['allOnFile'],
    };
}

