/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31386082920
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AthleticProfileShowSportCoachStaffQuadrantPointsInner
 */
export interface AthleticProfileShowSportCoachStaffQuadrantPointsInner {
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportCoachStaffQuadrantPointsInner
     */
    schoolId?: number;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowSportCoachStaffQuadrantPointsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowSportCoachStaffQuadrantPointsInner
     */
    shortName?: string;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowSportCoachStaffQuadrantPointsInner
     */
    colors?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AthleticProfileShowSportCoachStaffQuadrantPointsInner
     */
    isSubject?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowSportCoachStaffQuadrantPointsInner
     */
    coachName?: string | null;
    /**
     * Structured last name — may be multi-word ("Hughley Jr").
     * @type {string}
     * @memberof AthleticProfileShowSportCoachStaffQuadrantPointsInner
     */
    coachLastName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportCoachStaffQuadrantPointsInner
     */
    compCents?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportCoachStaffQuadrantPointsInner
     */
    netRank?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportCoachStaffQuadrantPointsInner
     */
    rpi?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowSportCoachStaffQuadrantPointsInner
     */
    record?: string | null;
}

/**
 * Check if a given object implements the AthleticProfileShowSportCoachStaffQuadrantPointsInner interface.
 */
export function instanceOfAthleticProfileShowSportCoachStaffQuadrantPointsInner(value: object): value is AthleticProfileShowSportCoachStaffQuadrantPointsInner {
    return true;
}

export function AthleticProfileShowSportCoachStaffQuadrantPointsInnerFromJSON(json: any): AthleticProfileShowSportCoachStaffQuadrantPointsInner {
    return AthleticProfileShowSportCoachStaffQuadrantPointsInnerFromJSONTyped(json, false);
}

export function AthleticProfileShowSportCoachStaffQuadrantPointsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AthleticProfileShowSportCoachStaffQuadrantPointsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'schoolId': json['school_id'] == null ? undefined : json['school_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'shortName': json['short_name'] == null ? undefined : json['short_name'],
        'colors': json['colors'] == null ? undefined : json['colors'],
        'isSubject': json['is_subject'] == null ? undefined : json['is_subject'],
        'coachName': json['coach_name'] == null ? undefined : json['coach_name'],
        'coachLastName': json['coach_last_name'] == null ? undefined : json['coach_last_name'],
        'compCents': json['comp_cents'] == null ? undefined : json['comp_cents'],
        'netRank': json['net_rank'] == null ? undefined : json['net_rank'],
        'rpi': json['rpi'] == null ? undefined : json['rpi'],
        'record': json['record'] == null ? undefined : json['record'],
    };
}

export function AthleticProfileShowSportCoachStaffQuadrantPointsInnerToJSON(json: any): AthleticProfileShowSportCoachStaffQuadrantPointsInner {
    return AthleticProfileShowSportCoachStaffQuadrantPointsInnerToJSONTyped(json, false);
}

export function AthleticProfileShowSportCoachStaffQuadrantPointsInnerToJSONTyped(value?: AthleticProfileShowSportCoachStaffQuadrantPointsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'school_id': value['schoolId'],
        'name': value['name'],
        'short_name': value['shortName'],
        'colors': value['colors'],
        'is_subject': value['isSubject'],
        'coach_name': value['coachName'],
        'coach_last_name': value['coachLastName'],
        'comp_cents': value['compCents'],
        'net_rank': value['netRank'],
        'rpi': value['rpi'],
        'record': value['record'],
    };
}

