/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.33181572003
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AthleticProfileShowSportCoachStaffAssistantsInner
 */
export interface AthleticProfileShowSportCoachStaffAssistantsInner {
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportCoachStaffAssistantsInner
     */
    coachId?: number;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowSportCoachStaffAssistantsInner
     */
    name?: string;
    /**
     * Structured last name — may be multi-word ("Hughley Jr").
     * @type {string}
     * @memberof AthleticProfileShowSportCoachStaffAssistantsInner
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowSportCoachStaffAssistantsInner
     */
    title?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportCoachStaffAssistantsInner
     */
    compCents?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof AthleticProfileShowSportCoachStaffAssistantsInner
     */
    contractEndOn?: Date | null;
    /**
     * True when no term is stated (no contract, at-will contract, or no end date). Null when compensation is not permitted.
     * @type {boolean}
     * @memberof AthleticProfileShowSportCoachStaffAssistantsInner
     */
    atWill?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AthleticProfileShowSportCoachStaffAssistantsInner
     */
    onFile?: boolean | null;
}

/**
 * Check if a given object implements the AthleticProfileShowSportCoachStaffAssistantsInner interface.
 */
export function instanceOfAthleticProfileShowSportCoachStaffAssistantsInner(value: object): value is AthleticProfileShowSportCoachStaffAssistantsInner {
    return true;
}

export function AthleticProfileShowSportCoachStaffAssistantsInnerFromJSON(json: any): AthleticProfileShowSportCoachStaffAssistantsInner {
    return AthleticProfileShowSportCoachStaffAssistantsInnerFromJSONTyped(json, false);
}

export function AthleticProfileShowSportCoachStaffAssistantsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AthleticProfileShowSportCoachStaffAssistantsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'coachId': json['coach_id'] == null ? undefined : json['coach_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'title': json['title'] == null ? undefined : json['title'],
        'compCents': json['comp_cents'] == null ? undefined : json['comp_cents'],
        'contractEndOn': json['contract_end_on'] == null ? undefined : (new Date(json['contract_end_on'])),
        'atWill': json['at_will'] == null ? undefined : json['at_will'],
        'onFile': json['on_file'] == null ? undefined : json['on_file'],
    };
}

export function AthleticProfileShowSportCoachStaffAssistantsInnerToJSON(json: any): AthleticProfileShowSportCoachStaffAssistantsInner {
    return AthleticProfileShowSportCoachStaffAssistantsInnerToJSONTyped(json, false);
}

export function AthleticProfileShowSportCoachStaffAssistantsInnerToJSONTyped(value?: AthleticProfileShowSportCoachStaffAssistantsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coach_id': value['coachId'],
        'name': value['name'],
        'last_name': value['lastName'],
        'title': value['title'],
        'comp_cents': value['compCents'],
        'contract_end_on': value['contractEndOn'] == null ? value['contractEndOn'] : value['contractEndOn'].toISOString().substring(0,10),
        'at_will': value['atWill'],
        'on_file': value['onFile'],
    };
}

