/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31184208220
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AthleticProfileShowSportGuaranteesAgreementsInner
 */
export interface AthleticProfileShowSportGuaranteesAgreementsInner {
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportGuaranteesAgreementsInner
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportGuaranteesAgreementsInner
     */
    opponentId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowSportGuaranteesAgreementsInner
     */
    opponentName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowSportGuaranteesAgreementsInner
     */
    opponentShortName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AthleticProfileShowSportGuaranteesAgreementsInner
     */
    isHome?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowSportGuaranteesAgreementsInner
     */
    gameType?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AthleticProfileShowSportGuaranteesAgreementsInner
     */
    gameDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowSportGuaranteesAgreementsInner
     */
    gameDateTbd?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportGuaranteesAgreementsInner
     */
    compCents?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof AthleticProfileShowSportGuaranteesAgreementsInner
     */
    compTbd?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowSportGuaranteesAgreementsInner
     */
    offSiteLocation?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportGuaranteesAgreementsInner
     */
    rawContractId?: number | null;
}

/**
 * Check if a given object implements the AthleticProfileShowSportGuaranteesAgreementsInner interface.
 */
export function instanceOfAthleticProfileShowSportGuaranteesAgreementsInner(value: object): value is AthleticProfileShowSportGuaranteesAgreementsInner {
    return true;
}

export function AthleticProfileShowSportGuaranteesAgreementsInnerFromJSON(json: any): AthleticProfileShowSportGuaranteesAgreementsInner {
    return AthleticProfileShowSportGuaranteesAgreementsInnerFromJSONTyped(json, false);
}

export function AthleticProfileShowSportGuaranteesAgreementsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AthleticProfileShowSportGuaranteesAgreementsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'opponentId': json['opponent_id'] == null ? undefined : json['opponent_id'],
        'opponentName': json['opponent_name'] == null ? undefined : json['opponent_name'],
        'opponentShortName': json['opponent_short_name'] == null ? undefined : json['opponent_short_name'],
        'isHome': json['is_home'] == null ? undefined : json['is_home'],
        'gameType': json['game_type'] == null ? undefined : json['game_type'],
        'gameDate': json['game_date'] == null ? undefined : (new Date(json['game_date'])),
        'gameDateTbd': json['game_date_tbd'] == null ? undefined : json['game_date_tbd'],
        'compCents': json['comp_cents'] == null ? undefined : json['comp_cents'],
        'compTbd': json['comp_tbd'] == null ? undefined : json['comp_tbd'],
        'offSiteLocation': json['off_site_location'] == null ? undefined : json['off_site_location'],
        'rawContractId': json['raw_contract_id'] == null ? undefined : json['raw_contract_id'],
    };
}

export function AthleticProfileShowSportGuaranteesAgreementsInnerToJSON(json: any): AthleticProfileShowSportGuaranteesAgreementsInner {
    return AthleticProfileShowSportGuaranteesAgreementsInnerToJSONTyped(json, false);
}

export function AthleticProfileShowSportGuaranteesAgreementsInnerToJSONTyped(value?: AthleticProfileShowSportGuaranteesAgreementsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'opponent_id': value['opponentId'],
        'opponent_name': value['opponentName'],
        'opponent_short_name': value['opponentShortName'],
        'is_home': value['isHome'],
        'game_type': value['gameType'],
        'game_date': value['gameDate'] == null ? value['gameDate'] : value['gameDate'].toISOString().substring(0,10),
        'game_date_tbd': value['gameDateTbd'],
        'comp_cents': value['compCents'],
        'comp_tbd': value['compTbd'],
        'off_site_location': value['offSiteLocation'],
        'raw_contract_id': value['rawContractId'],
    };
}

