/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31476617449
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AthleticProfileShowSportFinancialsQuadrantPointsInner
 */
export interface AthleticProfileShowSportFinancialsQuadrantPointsInner {
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportFinancialsQuadrantPointsInner
     */
    schoolId?: number;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowSportFinancialsQuadrantPointsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowSportFinancialsQuadrantPointsInner
     */
    shortName?: string;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowSportFinancialsQuadrantPointsInner
     */
    colors?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AthleticProfileShowSportFinancialsQuadrantPointsInner
     */
    isSubject?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportFinancialsQuadrantPointsInner
     */
    spendCents?: number;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportFinancialsQuadrantPointsInner
     */
    revenueCents?: number;
}

/**
 * Check if a given object implements the AthleticProfileShowSportFinancialsQuadrantPointsInner interface.
 */
export function instanceOfAthleticProfileShowSportFinancialsQuadrantPointsInner(value: object): value is AthleticProfileShowSportFinancialsQuadrantPointsInner {
    return true;
}

export function AthleticProfileShowSportFinancialsQuadrantPointsInnerFromJSON(json: any): AthleticProfileShowSportFinancialsQuadrantPointsInner {
    return AthleticProfileShowSportFinancialsQuadrantPointsInnerFromJSONTyped(json, false);
}

export function AthleticProfileShowSportFinancialsQuadrantPointsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AthleticProfileShowSportFinancialsQuadrantPointsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'schoolId': json['school_id'] == null ? undefined : json['school_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'shortName': json['short_name'] == null ? undefined : json['short_name'],
        'colors': json['colors'] == null ? undefined : json['colors'],
        'isSubject': json['is_subject'] == null ? undefined : json['is_subject'],
        'spendCents': json['spend_cents'] == null ? undefined : json['spend_cents'],
        'revenueCents': json['revenue_cents'] == null ? undefined : json['revenue_cents'],
    };
}

export function AthleticProfileShowSportFinancialsQuadrantPointsInnerToJSON(json: any): AthleticProfileShowSportFinancialsQuadrantPointsInner {
    return AthleticProfileShowSportFinancialsQuadrantPointsInnerToJSONTyped(json, false);
}

export function AthleticProfileShowSportFinancialsQuadrantPointsInnerToJSONTyped(value?: AthleticProfileShowSportFinancialsQuadrantPointsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'school_id': value['schoolId'],
        'name': value['name'],
        'short_name': value['shortName'],
        'colors': value['colors'],
        'is_subject': value['isSubject'],
        'spend_cents': value['spendCents'],
        'revenue_cents': value['revenueCents'],
    };
}

