/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.54.2-dev.10366
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AthleticProfileShowSportFinancialsCostBuildHeadCoach
 */
export interface AthleticProfileShowSportFinancialsCostBuildHeadCoach {
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowSportFinancialsCostBuildHeadCoach
     */
    name?: string;
    /**
     * Structured last name — may be multi-word ("Hughley Jr").
     * @type {string}
     * @memberof AthleticProfileShowSportFinancialsCostBuildHeadCoach
     */
    lastName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportFinancialsCostBuildHeadCoach
     */
    compCents?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AthleticProfileShowSportFinancialsCostBuildHeadCoach
     */
    onFile?: boolean;
    /**
     * Which filing the figure is read from — a contract, or the school's IRS 990 for a private school.
     * @type {string}
     * @memberof AthleticProfileShowSportFinancialsCostBuildHeadCoach
     */
    compBasis?: AthleticProfileShowSportFinancialsCostBuildHeadCoachCompBasisEnum;
    /**
     * The 990's filing year; null for a contract figure.
     * @type {number}
     * @memberof AthleticProfileShowSportFinancialsCostBuildHeadCoach
     */
    compFiscalYear?: number | null;
}


/**
 * @export
 */
export const AthleticProfileShowSportFinancialsCostBuildHeadCoachCompBasisEnum = {
    Contract: 'contract',
    _990: '990'
} as const;
export type AthleticProfileShowSportFinancialsCostBuildHeadCoachCompBasisEnum = typeof AthleticProfileShowSportFinancialsCostBuildHeadCoachCompBasisEnum[keyof typeof AthleticProfileShowSportFinancialsCostBuildHeadCoachCompBasisEnum];


/**
 * Check if a given object implements the AthleticProfileShowSportFinancialsCostBuildHeadCoach interface.
 */
export function instanceOfAthleticProfileShowSportFinancialsCostBuildHeadCoach(value: object): value is AthleticProfileShowSportFinancialsCostBuildHeadCoach {
    return true;
}

export function AthleticProfileShowSportFinancialsCostBuildHeadCoachFromJSON(json: any): AthleticProfileShowSportFinancialsCostBuildHeadCoach {
    return AthleticProfileShowSportFinancialsCostBuildHeadCoachFromJSONTyped(json, false);
}

export function AthleticProfileShowSportFinancialsCostBuildHeadCoachFromJSONTyped(json: any, ignoreDiscriminator: boolean): AthleticProfileShowSportFinancialsCostBuildHeadCoach {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'compCents': json['comp_cents'] == null ? undefined : json['comp_cents'],
        'onFile': json['on_file'] == null ? undefined : json['on_file'],
        'compBasis': json['comp_basis'] == null ? undefined : json['comp_basis'],
        'compFiscalYear': json['comp_fiscal_year'] == null ? undefined : json['comp_fiscal_year'],
    };
}

export function AthleticProfileShowSportFinancialsCostBuildHeadCoachToJSON(json: any): AthleticProfileShowSportFinancialsCostBuildHeadCoach {
    return AthleticProfileShowSportFinancialsCostBuildHeadCoachToJSONTyped(json, false);
}

export function AthleticProfileShowSportFinancialsCostBuildHeadCoachToJSONTyped(value?: AthleticProfileShowSportFinancialsCostBuildHeadCoach | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'last_name': value['lastName'],
        'comp_cents': value['compCents'],
        'on_file': value['onFile'],
        'comp_basis': value['compBasis'],
        'comp_fiscal_year': value['compFiscalYear'],
    };
}

