/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.44.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AthleticProfileShowPersonnelInner
 */
export interface AthleticProfileShowPersonnelInner {
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowPersonnelInner
     */
    coachId?: number;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowPersonnelInner
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowPersonnelInner
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowPersonnelInner
     */
    positionName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AthleticProfileShowPersonnelInner
     */
    departing?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowPersonnelInner
     */
    avatarUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowPersonnelInner
     */
    salaryCents?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AthleticProfileShowPersonnelInner
     */
    salaryDisplay?: string | null;
}

/**
 * Check if a given object implements the AthleticProfileShowPersonnelInner interface.
 */
export function instanceOfAthleticProfileShowPersonnelInner(value: object): value is AthleticProfileShowPersonnelInner {
    return true;
}

export function AthleticProfileShowPersonnelInnerFromJSON(json: any): AthleticProfileShowPersonnelInner {
    return AthleticProfileShowPersonnelInnerFromJSONTyped(json, false);
}

export function AthleticProfileShowPersonnelInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AthleticProfileShowPersonnelInner {
    if (json == null) {
        return json;
    }
    return {
        
        'coachId': json['coach_id'] == null ? undefined : json['coach_id'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'positionName': json['position_name'] == null ? undefined : json['position_name'],
        'departing': json['departing'] == null ? undefined : json['departing'],
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'salaryCents': json['salary_cents'] == null ? undefined : json['salary_cents'],
        'salaryDisplay': json['salary_display'] == null ? undefined : json['salary_display'],
    };
}

export function AthleticProfileShowPersonnelInnerToJSON(json: any): AthleticProfileShowPersonnelInner {
    return AthleticProfileShowPersonnelInnerToJSONTyped(json, false);
}

export function AthleticProfileShowPersonnelInnerToJSONTyped(value?: AthleticProfileShowPersonnelInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coach_id': value['coachId'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'position_name': value['positionName'],
        'departing': value['departing'],
        'avatar_url': value['avatarUrl'],
        'salary_cents': value['salaryCents'],
        'salary_display': value['salaryDisplay'],
    };
}

