/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31153399906
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AthleticProfileShowSportFinancialsCostBuildHeadCoach } from './AthleticProfileShowSportFinancialsCostBuildHeadCoach';
import {
    AthleticProfileShowSportFinancialsCostBuildHeadCoachFromJSON,
    AthleticProfileShowSportFinancialsCostBuildHeadCoachFromJSONTyped,
    AthleticProfileShowSportFinancialsCostBuildHeadCoachToJSON,
    AthleticProfileShowSportFinancialsCostBuildHeadCoachToJSONTyped,
} from './AthleticProfileShowSportFinancialsCostBuildHeadCoach';
import type { AthleticProfileShowSportFinancialsCostBuildSupportStaffInner } from './AthleticProfileShowSportFinancialsCostBuildSupportStaffInner';
import {
    AthleticProfileShowSportFinancialsCostBuildSupportStaffInnerFromJSON,
    AthleticProfileShowSportFinancialsCostBuildSupportStaffInnerFromJSONTyped,
    AthleticProfileShowSportFinancialsCostBuildSupportStaffInnerToJSON,
    AthleticProfileShowSportFinancialsCostBuildSupportStaffInnerToJSONTyped,
} from './AthleticProfileShowSportFinancialsCostBuildSupportStaffInner';
import type { AthleticProfileShowSportFinancialsCostBuildGuaranteesNet } from './AthleticProfileShowSportFinancialsCostBuildGuaranteesNet';
import {
    AthleticProfileShowSportFinancialsCostBuildGuaranteesNetFromJSON,
    AthleticProfileShowSportFinancialsCostBuildGuaranteesNetFromJSONTyped,
    AthleticProfileShowSportFinancialsCostBuildGuaranteesNetToJSON,
    AthleticProfileShowSportFinancialsCostBuildGuaranteesNetToJSONTyped,
} from './AthleticProfileShowSportFinancialsCostBuildGuaranteesNet';
import type { AthleticProfileShowSportFinancialsCostBuildAssistantPool } from './AthleticProfileShowSportFinancialsCostBuildAssistantPool';
import {
    AthleticProfileShowSportFinancialsCostBuildAssistantPoolFromJSON,
    AthleticProfileShowSportFinancialsCostBuildAssistantPoolFromJSONTyped,
    AthleticProfileShowSportFinancialsCostBuildAssistantPoolToJSON,
    AthleticProfileShowSportFinancialsCostBuildAssistantPoolToJSONTyped,
} from './AthleticProfileShowSportFinancialsCostBuildAssistantPool';

/**
 * 
 * @export
 * @interface AthleticProfileShowSportFinancialsCostBuild
 */
export interface AthleticProfileShowSportFinancialsCostBuild {
    /**
     * 
     * @type {AthleticProfileShowSportFinancialsCostBuildHeadCoach}
     * @memberof AthleticProfileShowSportFinancialsCostBuild
     */
    headCoach?: AthleticProfileShowSportFinancialsCostBuildHeadCoach | null;
    /**
     * 
     * @type {AthleticProfileShowSportFinancialsCostBuildAssistantPool}
     * @memberof AthleticProfileShowSportFinancialsCostBuild
     */
    assistantPool?: AthleticProfileShowSportFinancialsCostBuildAssistantPool | null;
    /**
     * 
     * @type {AthleticProfileShowSportFinancialsCostBuildGuaranteesNet}
     * @memberof AthleticProfileShowSportFinancialsCostBuild
     */
    guaranteesNet?: AthleticProfileShowSportFinancialsCostBuildGuaranteesNet | null;
    /**
     * 
     * @type {Array<AthleticProfileShowSportFinancialsCostBuildSupportStaffInner>}
     * @memberof AthleticProfileShowSportFinancialsCostBuild
     */
    supportStaff?: Array<AthleticProfileShowSportFinancialsCostBuildSupportStaffInner>;
    /**
     * 
     * @type {number}
     * @memberof AthleticProfileShowSportFinancialsCostBuild
     */
    totalCents?: number | null;
}

/**
 * Check if a given object implements the AthleticProfileShowSportFinancialsCostBuild interface.
 */
export function instanceOfAthleticProfileShowSportFinancialsCostBuild(value: object): value is AthleticProfileShowSportFinancialsCostBuild {
    return true;
}

export function AthleticProfileShowSportFinancialsCostBuildFromJSON(json: any): AthleticProfileShowSportFinancialsCostBuild {
    return AthleticProfileShowSportFinancialsCostBuildFromJSONTyped(json, false);
}

export function AthleticProfileShowSportFinancialsCostBuildFromJSONTyped(json: any, ignoreDiscriminator: boolean): AthleticProfileShowSportFinancialsCostBuild {
    if (json == null) {
        return json;
    }
    return {
        
        'headCoach': json['head_coach'] == null ? undefined : AthleticProfileShowSportFinancialsCostBuildHeadCoachFromJSON(json['head_coach']),
        'assistantPool': json['assistant_pool'] == null ? undefined : AthleticProfileShowSportFinancialsCostBuildAssistantPoolFromJSON(json['assistant_pool']),
        'guaranteesNet': json['guarantees_net'] == null ? undefined : AthleticProfileShowSportFinancialsCostBuildGuaranteesNetFromJSON(json['guarantees_net']),
        'supportStaff': json['support_staff'] == null ? undefined : ((json['support_staff'] as Array<any>).map(AthleticProfileShowSportFinancialsCostBuildSupportStaffInnerFromJSON)),
        'totalCents': json['total_cents'] == null ? undefined : json['total_cents'],
    };
}

export function AthleticProfileShowSportFinancialsCostBuildToJSON(json: any): AthleticProfileShowSportFinancialsCostBuild {
    return AthleticProfileShowSportFinancialsCostBuildToJSONTyped(json, false);
}

export function AthleticProfileShowSportFinancialsCostBuildToJSONTyped(value?: AthleticProfileShowSportFinancialsCostBuild | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'head_coach': AthleticProfileShowSportFinancialsCostBuildHeadCoachToJSON(value['headCoach']),
        'assistant_pool': AthleticProfileShowSportFinancialsCostBuildAssistantPoolToJSON(value['assistantPool']),
        'guarantees_net': AthleticProfileShowSportFinancialsCostBuildGuaranteesNetToJSON(value['guaranteesNet']),
        'support_staff': value['supportStaff'] == null ? undefined : ((value['supportStaff'] as Array<any>).map(AthleticProfileShowSportFinancialsCostBuildSupportStaffInnerToJSON)),
        'total_cents': value['totalCents'],
    };
}

