/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.37
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkCreateGamePostSearchesRequestIntentsInner
 */
export interface BulkCreateGamePostSearchesRequestIntentsInner {
    /**
     * 
     * @type {number}
     * @memberof BulkCreateGamePostSearchesRequestIntentsInner
     */
    sportId: number;
    /**
     * 
     * @type {Date}
     * @memberof BulkCreateGamePostSearchesRequestIntentsInner
     */
    date?: Date;
    /**
     * 
     * @type {Array<number>}
     * @memberof BulkCreateGamePostSearchesRequestIntentsInner
     */
    gameTypeIds?: Array<number>;
}

/**
 * Check if a given object implements the BulkCreateGamePostSearchesRequestIntentsInner interface.
 */
export function instanceOfBulkCreateGamePostSearchesRequestIntentsInner(value: object): value is BulkCreateGamePostSearchesRequestIntentsInner {
    if (!('sportId' in value) || value['sportId'] === undefined) return false;
    return true;
}

export function BulkCreateGamePostSearchesRequestIntentsInnerFromJSON(json: any): BulkCreateGamePostSearchesRequestIntentsInner {
    return BulkCreateGamePostSearchesRequestIntentsInnerFromJSONTyped(json, false);
}

export function BulkCreateGamePostSearchesRequestIntentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkCreateGamePostSearchesRequestIntentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'sportId': json['sport_id'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'gameTypeIds': json['game_type_ids'] == null ? undefined : json['game_type_ids'],
    };
}

export function BulkCreateGamePostSearchesRequestIntentsInnerToJSON(json: any): BulkCreateGamePostSearchesRequestIntentsInner {
    return BulkCreateGamePostSearchesRequestIntentsInnerToJSONTyped(json, false);
}

export function BulkCreateGamePostSearchesRequestIntentsInnerToJSONTyped(value?: BulkCreateGamePostSearchesRequestIntentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sport_id': value['sportId'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString().substring(0,10),
        'game_type_ids': value['gameTypeIds'],
    };
}

