/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.44.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ComparisonSection } from './ComparisonSection';
import {
    ComparisonSectionFromJSON,
    ComparisonSectionFromJSONTyped,
    ComparisonSectionToJSON,
    ComparisonSectionToJSONTyped,
} from './ComparisonSection';

/**
 * 
 * @export
 * @interface CoachCompensationTabComparisons
 */
export interface CoachCompensationTabComparisons {
    /**
     * 
     * @type {ComparisonSection}
     * @memberof CoachCompensationTabComparisons
     */
    conference?: ComparisonSection;
    /**
     * 
     * @type {ComparisonSection}
     * @memberof CoachCompensationTabComparisons
     */
    division?: ComparisonSection;
}

/**
 * Check if a given object implements the CoachCompensationTabComparisons interface.
 */
export function instanceOfCoachCompensationTabComparisons(value: object): value is CoachCompensationTabComparisons {
    return true;
}

export function CoachCompensationTabComparisonsFromJSON(json: any): CoachCompensationTabComparisons {
    return CoachCompensationTabComparisonsFromJSONTyped(json, false);
}

export function CoachCompensationTabComparisonsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoachCompensationTabComparisons {
    if (json == null) {
        return json;
    }
    return {
        
        'conference': json['conference'] == null ? undefined : ComparisonSectionFromJSON(json['conference']),
        'division': json['division'] == null ? undefined : ComparisonSectionFromJSON(json['division']),
    };
}

export function CoachCompensationTabComparisonsToJSON(json: any): CoachCompensationTabComparisons {
    return CoachCompensationTabComparisonsToJSONTyped(json, false);
}

export function CoachCompensationTabComparisonsToJSONTyped(value?: CoachCompensationTabComparisons | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conference': ComparisonSectionToJSON(value['conference']),
        'division': ComparisonSectionToJSON(value['division']),
    };
}

