/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.44.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecruitingBudgetEntry } from './RecruitingBudgetEntry';
import {
    RecruitingBudgetEntryFromJSON,
    RecruitingBudgetEntryFromJSONTyped,
    RecruitingBudgetEntryToJSON,
    RecruitingBudgetEntryToJSONTyped,
} from './RecruitingBudgetEntry';

/**
 * 
 * @export
 * @interface CoachRecruitingTabRecruitingBudgets
 */
export interface CoachRecruitingTabRecruitingBudgets {
    /**
     * 
     * @type {string}
     * @memberof CoachRecruitingTabRecruitingBudgets
     */
    title: string;
    /**
     * 
     * @type {Array<RecruitingBudgetEntry>}
     * @memberof CoachRecruitingTabRecruitingBudgets
     */
    entries: Array<RecruitingBudgetEntry>;
}

/**
 * Check if a given object implements the CoachRecruitingTabRecruitingBudgets interface.
 */
export function instanceOfCoachRecruitingTabRecruitingBudgets(value: object): value is CoachRecruitingTabRecruitingBudgets {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('entries' in value) || value['entries'] === undefined) return false;
    return true;
}

export function CoachRecruitingTabRecruitingBudgetsFromJSON(json: any): CoachRecruitingTabRecruitingBudgets {
    return CoachRecruitingTabRecruitingBudgetsFromJSONTyped(json, false);
}

export function CoachRecruitingTabRecruitingBudgetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoachRecruitingTabRecruitingBudgets {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'entries': ((json['entries'] as Array<any>).map(RecruitingBudgetEntryFromJSON)),
    };
}

export function CoachRecruitingTabRecruitingBudgetsToJSON(json: any): CoachRecruitingTabRecruitingBudgets {
    return CoachRecruitingTabRecruitingBudgetsToJSONTyped(json, false);
}

export function CoachRecruitingTabRecruitingBudgetsToJSONTyped(value?: CoachRecruitingTabRecruitingBudgets | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'entries': ((value['entries'] as Array<any>).map(RecruitingBudgetEntryToJSON)),
    };
}

