/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.44.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoachCompensationTabChartDataTotalCompOverTimeInner
 */
export interface CoachCompensationTabChartDataTotalCompOverTimeInner {
    /**
     * 
     * @type {number}
     * @memberof CoachCompensationTabChartDataTotalCompOverTimeInner
     */
    year?: number;
    /**
     * 
     * @type {number}
     * @memberof CoachCompensationTabChartDataTotalCompOverTimeInner
     */
    compCents?: number;
    /**
     * 
     * @type {string}
     * @memberof CoachCompensationTabChartDataTotalCompOverTimeInner
     */
    position?: string;
}

/**
 * Check if a given object implements the CoachCompensationTabChartDataTotalCompOverTimeInner interface.
 */
export function instanceOfCoachCompensationTabChartDataTotalCompOverTimeInner(value: object): value is CoachCompensationTabChartDataTotalCompOverTimeInner {
    return true;
}

export function CoachCompensationTabChartDataTotalCompOverTimeInnerFromJSON(json: any): CoachCompensationTabChartDataTotalCompOverTimeInner {
    return CoachCompensationTabChartDataTotalCompOverTimeInnerFromJSONTyped(json, false);
}

export function CoachCompensationTabChartDataTotalCompOverTimeInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoachCompensationTabChartDataTotalCompOverTimeInner {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'compCents': json['comp_cents'] == null ? undefined : json['comp_cents'],
        'position': json['position'] == null ? undefined : json['position'],
    };
}

export function CoachCompensationTabChartDataTotalCompOverTimeInnerToJSON(json: any): CoachCompensationTabChartDataTotalCompOverTimeInner {
    return CoachCompensationTabChartDataTotalCompOverTimeInnerToJSONTyped(json, false);
}

export function CoachCompensationTabChartDataTotalCompOverTimeInnerToJSONTyped(value?: CoachCompensationTabChartDataTotalCompOverTimeInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'comp_cents': value['compCents'],
        'position': value['position'],
    };
}

