/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoachCompensationEntry
 */
export interface CoachCompensationEntry {
    /**
     * 
     * @type {string}
     * @memberof CoachCompensationEntry
     */
    yearStr: string;
    /**
     * 
     * @type {string}
     * @memberof CoachCompensationEntry
     */
    schoolName: string;
    /**
     * 
     * @type {number}
     * @memberof CoachCompensationEntry
     */
    schoolId: number;
    /**
     * 
     * @type {string}
     * @memberof CoachCompensationEntry
     */
    positionSport: string;
    /**
     * 
     * @type {number}
     * @memberof CoachCompensationEntry
     */
    totalCents?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CoachCompensationEntry
     */
    baseSalaryCents?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CoachCompensationEntry
     */
    talentFeeCents?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CoachCompensationEntry
     */
    deferredCompCents?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CoachCompensationEntry
     */
    compensationType: string;
    /**
     * 
     * @type {string}
     * @memberof CoachCompensationEntry
     */
    mediaLink?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CoachCompensationEntry
     */
    rawContractId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CoachCompensationEntry
     */
    oneTimeBonusCents?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CoachCompensationEntry
     */
    outsideIncomeCents?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof CoachCompensationEntry
     */
    contingentBonus?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof CoachCompensationEntry
     */
    buyoutTerms?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CoachCompensationEntry
     */
    isCarProvided?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CoachCompensationEntry
     */
    countryClubMembership?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CoachCompensationEntry
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the CoachCompensationEntry interface.
 */
export function instanceOfCoachCompensationEntry(value: object): value is CoachCompensationEntry {
    if (!('yearStr' in value) || value['yearStr'] === undefined) return false;
    if (!('schoolName' in value) || value['schoolName'] === undefined) return false;
    if (!('schoolId' in value) || value['schoolId'] === undefined) return false;
    if (!('positionSport' in value) || value['positionSport'] === undefined) return false;
    if (!('compensationType' in value) || value['compensationType'] === undefined) return false;
    return true;
}

export function CoachCompensationEntryFromJSON(json: any): CoachCompensationEntry {
    return CoachCompensationEntryFromJSONTyped(json, false);
}

export function CoachCompensationEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoachCompensationEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'yearStr': json['year_str'],
        'schoolName': json['school_name'],
        'schoolId': json['school_id'],
        'positionSport': json['position_sport'],
        'totalCents': json['total_cents'] == null ? undefined : json['total_cents'],
        'baseSalaryCents': json['base_salary_cents'] == null ? undefined : json['base_salary_cents'],
        'talentFeeCents': json['talent_fee_cents'] == null ? undefined : json['talent_fee_cents'],
        'deferredCompCents': json['deferred_comp_cents'] == null ? undefined : json['deferred_comp_cents'],
        'compensationType': json['compensation_type'],
        'mediaLink': json['media_link'] == null ? undefined : json['media_link'],
        'rawContractId': json['raw_contract_id'] == null ? undefined : json['raw_contract_id'],
        'oneTimeBonusCents': json['one_time_bonus_cents'] == null ? undefined : json['one_time_bonus_cents'],
        'outsideIncomeCents': json['outside_income_cents'] == null ? undefined : json['outside_income_cents'],
        'contingentBonus': json['contingent_bonus'] == null ? undefined : json['contingent_bonus'],
        'buyoutTerms': json['buyout_terms'] == null ? undefined : json['buyout_terms'],
        'isCarProvided': json['is_car_provided'] == null ? undefined : json['is_car_provided'],
        'countryClubMembership': json['country_club_membership'] == null ? undefined : json['country_club_membership'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function CoachCompensationEntryToJSON(json: any): CoachCompensationEntry {
    return CoachCompensationEntryToJSONTyped(json, false);
}

export function CoachCompensationEntryToJSONTyped(value?: CoachCompensationEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year_str': value['yearStr'],
        'school_name': value['schoolName'],
        'school_id': value['schoolId'],
        'position_sport': value['positionSport'],
        'total_cents': value['totalCents'],
        'base_salary_cents': value['baseSalaryCents'],
        'talent_fee_cents': value['talentFeeCents'],
        'deferred_comp_cents': value['deferredCompCents'],
        'compensation_type': value['compensationType'],
        'media_link': value['mediaLink'],
        'raw_contract_id': value['rawContractId'],
        'one_time_bonus_cents': value['oneTimeBonusCents'],
        'outside_income_cents': value['outsideIncomeCents'],
        'contingent_bonus': value['contingentBonus'],
        'buyout_terms': value['buyoutTerms'],
        'is_car_provided': value['isCarProvided'],
        'country_club_membership': value['countryClubMembership'],
        'notes': value['notes'],
    };
}

