/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.44.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoachCompensationTabSidebarIncomeReportsInner
 */
export interface CoachCompensationTabSidebarIncomeReportsInner {
    /**
     * 
     * @type {number}
     * @memberof CoachCompensationTabSidebarIncomeReportsInner
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof CoachCompensationTabSidebarIncomeReportsInner
     */
    rawContractId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CoachCompensationTabSidebarIncomeReportsInner
     */
    year?: number;
}

/**
 * Check if a given object implements the CoachCompensationTabSidebarIncomeReportsInner interface.
 */
export function instanceOfCoachCompensationTabSidebarIncomeReportsInner(value: object): value is CoachCompensationTabSidebarIncomeReportsInner {
    return true;
}

export function CoachCompensationTabSidebarIncomeReportsInnerFromJSON(json: any): CoachCompensationTabSidebarIncomeReportsInner {
    return CoachCompensationTabSidebarIncomeReportsInnerFromJSONTyped(json, false);
}

export function CoachCompensationTabSidebarIncomeReportsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoachCompensationTabSidebarIncomeReportsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'rawContractId': json['raw_contract_id'] == null ? undefined : json['raw_contract_id'],
        'year': json['year'] == null ? undefined : json['year'],
    };
}

export function CoachCompensationTabSidebarIncomeReportsInnerToJSON(json: any): CoachCompensationTabSidebarIncomeReportsInner {
    return CoachCompensationTabSidebarIncomeReportsInnerToJSONTyped(json, false);
}

export function CoachCompensationTabSidebarIncomeReportsInnerToJSONTyped(value?: CoachCompensationTabSidebarIncomeReportsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'raw_contract_id': value['rawContractId'],
        'year': value['year'],
    };
}

