/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.29925696441
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompensationComparisonCompVisibility } from './CompensationComparisonCompVisibility';
import {
    CompensationComparisonCompVisibilityFromJSON,
    CompensationComparisonCompVisibilityFromJSONTyped,
    CompensationComparisonCompVisibilityToJSON,
    CompensationComparisonCompVisibilityToJSONTyped,
} from './CompensationComparisonCompVisibility';
import type { CompensationComparisonRow } from './CompensationComparisonRow';
import {
    CompensationComparisonRowFromJSON,
    CompensationComparisonRowFromJSONTyped,
    CompensationComparisonRowToJSON,
    CompensationComparisonRowToJSONTyped,
} from './CompensationComparisonRow';
import type { CompensationComparisonCohortStats } from './CompensationComparisonCohortStats';
import {
    CompensationComparisonCohortStatsFromJSON,
    CompensationComparisonCohortStatsFromJSONTyped,
    CompensationComparisonCohortStatsToJSON,
    CompensationComparisonCohortStatsToJSONTyped,
} from './CompensationComparisonCohortStats';
import type { CompensationComparisonResolvedScope } from './CompensationComparisonResolvedScope';
import {
    CompensationComparisonResolvedScopeFromJSON,
    CompensationComparisonResolvedScopeFromJSONTyped,
    CompensationComparisonResolvedScopeToJSON,
    CompensationComparisonResolvedScopeToJSONTyped,
} from './CompensationComparisonResolvedScope';

/**
 * 
 * @export
 * @interface CompensationComparisonResult
 */
export interface CompensationComparisonResult {
    /**
     * 
     * @type {CompensationComparisonResolvedScope}
     * @memberof CompensationComparisonResult
     */
    resolvedScope: CompensationComparisonResolvedScope;
    /**
     * 
     * @type {Array<CompensationComparisonRow>}
     * @memberof CompensationComparisonResult
     */
    rows: Array<CompensationComparisonRow>;
    /**
     * 
     * @type {CompensationComparisonCohortStats}
     * @memberof CompensationComparisonResult
     */
    cohortStats: CompensationComparisonCohortStats;
    /**
     * 
     * @type {CompensationComparisonCompVisibility}
     * @memberof CompensationComparisonResult
     */
    compVisibility: CompensationComparisonCompVisibility;
    /**
     * 
     * @type {Array<string>}
     * @memberof CompensationComparisonResult
     */
    warnings: Array<string>;
}

/**
 * Check if a given object implements the CompensationComparisonResult interface.
 */
export function instanceOfCompensationComparisonResult(value: object): value is CompensationComparisonResult {
    if (!('resolvedScope' in value) || value['resolvedScope'] === undefined) return false;
    if (!('rows' in value) || value['rows'] === undefined) return false;
    if (!('cohortStats' in value) || value['cohortStats'] === undefined) return false;
    if (!('compVisibility' in value) || value['compVisibility'] === undefined) return false;
    if (!('warnings' in value) || value['warnings'] === undefined) return false;
    return true;
}

export function CompensationComparisonResultFromJSON(json: any): CompensationComparisonResult {
    return CompensationComparisonResultFromJSONTyped(json, false);
}

export function CompensationComparisonResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompensationComparisonResult {
    if (json == null) {
        return json;
    }
    return {
        
        'resolvedScope': CompensationComparisonResolvedScopeFromJSON(json['resolved_scope']),
        'rows': ((json['rows'] as Array<any>).map(CompensationComparisonRowFromJSON)),
        'cohortStats': CompensationComparisonCohortStatsFromJSON(json['cohort_stats']),
        'compVisibility': CompensationComparisonCompVisibilityFromJSON(json['comp_visibility']),
        'warnings': json['warnings'],
    };
}

export function CompensationComparisonResultToJSON(json: any): CompensationComparisonResult {
    return CompensationComparisonResultToJSONTyped(json, false);
}

export function CompensationComparisonResultToJSONTyped(value?: CompensationComparisonResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resolved_scope': CompensationComparisonResolvedScopeToJSON(value['resolvedScope']),
        'rows': ((value['rows'] as Array<any>).map(CompensationComparisonRowToJSON)),
        'cohort_stats': CompensationComparisonCohortStatsToJSON(value['cohortStats']),
        'comp_visibility': CompensationComparisonCompVisibilityToJSON(value['compVisibility']),
        'warnings': value['warnings'],
    };
}

