/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Conferenceship
 */
export interface Conferenceship {
    /**
     * 
     * @type {number}
     * @memberof Conferenceship
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Conferenceship
     */
    schoolId?: number;
    /**
     * 
     * @type {number}
     * @memberof Conferenceship
     */
    sportId?: number;
    /**
     * 
     * @type {number}
     * @memberof Conferenceship
     */
    conferenceId?: number;
    /**
     * 
     * @type {Date}
     * @memberof Conferenceship
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Conferenceship
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Conferenceship interface.
 */
export function instanceOfConferenceship(value: object): value is Conferenceship {
    return true;
}

export function ConferenceshipFromJSON(json: any): Conferenceship {
    return ConferenceshipFromJSONTyped(json, false);
}

export function ConferenceshipFromJSONTyped(json: any, ignoreDiscriminator: boolean): Conferenceship {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'schoolId': json['school_id'] == null ? undefined : json['school_id'],
        'sportId': json['sport_id'] == null ? undefined : json['sport_id'],
        'conferenceId': json['conference_id'] == null ? undefined : json['conference_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function ConferenceshipToJSON(json: any): Conferenceship {
    return ConferenceshipToJSONTyped(json, false);
}

export function ConferenceshipToJSONTyped(value?: Conferenceship | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'school_id': value['schoolId'],
        'sport_id': value['sportId'],
        'conference_id': value['conferenceId'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

