/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.44.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Conference
 */
export interface Conference {
    /**
     * 
     * @type {number}
     * @memberof Conference
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Conference
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Conference
     */
    nameDisplay?: string;
    /**
     * 
     * @type {string}
     * @memberof Conference
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof Conference
     */
    headquarters?: string;
    /**
     * 
     * @type {number}
     * @memberof Conference
     */
    founded?: number;
    /**
     * 
     * @type {number}
     * @memberof Conference
     */
    divisionId?: number;
    /**
     * 
     * @type {number}
     * @memberof Conference
     */
    ord?: number;
    /**
     * 
     * @type {Date}
     * @memberof Conference
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Conference
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Conference
     */
    externalUrl?: string;
}

/**
 * Check if a given object implements the Conference interface.
 */
export function instanceOfConference(value: object): value is Conference {
    return true;
}

export function ConferenceFromJSON(json: any): Conference {
    return ConferenceFromJSONTyped(json, false);
}

export function ConferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Conference {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameDisplay': json['name_display'] == null ? undefined : json['name_display'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'headquarters': json['headquarters'] == null ? undefined : json['headquarters'],
        'founded': json['founded'] == null ? undefined : json['founded'],
        'divisionId': json['division_id'] == null ? undefined : json['division_id'],
        'ord': json['ord'] == null ? undefined : json['ord'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'externalUrl': json['external_url'] == null ? undefined : json['external_url'],
    };
}

export function ConferenceToJSON(json: any): Conference {
    return ConferenceToJSONTyped(json, false);
}

export function ConferenceToJSONTyped(value?: Conference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'name_display': value['nameDisplay'],
        'nickname': value['nickname'],
        'headquarters': value['headquarters'],
        'founded': value['founded'],
        'division_id': value['divisionId'],
        'ord': value['ord'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'external_url': value['externalUrl'],
    };
}

