/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.55.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContractTermsSource } from './ContractTermsSource';
import {
    ContractTermsSourceFromJSON,
    ContractTermsSourceFromJSONTyped,
    ContractTermsSourceToJSON,
    ContractTermsSourceToJSONTyped,
} from './ContractTermsSource';

/**
 * One document of structured terms per RawContract (WINAD-10633). Only `schema` and `source` are required and checked; every other key is a term, in a shape set by `schema`, and is stored as sent. Each term carries the quote and page number it was read from in the contract's OCR text.
 * 
 * @export
 * @interface ContractTerms
 */
export interface ContractTerms {
    [key: string]: any | any;
    /**
     * The terms' shape and version, for example ticketing-terms-v1, pouring-terms-v1 or coach-terms-v1
     * @type {string}
     * @memberof ContractTerms
     */
    schema: string;
    /**
     * 
     * @type {ContractTermsSource}
     * @memberof ContractTerms
     */
    source: ContractTermsSource;
}

/**
 * Check if a given object implements the ContractTerms interface.
 */
export function instanceOfContractTerms(value: object): value is ContractTerms {
    if (!('schema' in value) || value['schema'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function ContractTermsFromJSON(json: any): ContractTerms {
    return ContractTermsFromJSONTyped(json, false);
}

export function ContractTermsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractTerms {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'schema': json['schema'],
        'source': ContractTermsSourceFromJSON(json['source']),
    };
}

export function ContractTermsToJSON(json: any): ContractTerms {
    return ContractTermsToJSONTyped(json, false);
}

export function ContractTermsToJSONTyped(value?: ContractTerms | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'schema': value['schema'],
        'source': ContractTermsSourceToJSON(value['source']),
    };
}

