/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGameRequestGame
 */
export interface CreateGameRequestGame {
    /**
     * 
     * @type {number}
     * @memberof CreateGameRequestGame
     */
    homeSchoolId?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateGameRequestGame
     */
    awaySchoolId?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateGameRequestGame
     */
    sportId?: number;
    /**
     * 
     * @type {Date}
     * @memberof CreateGameRequestGame
     */
    gameDate?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof CreateGameRequestGame
     */
    neutral?: boolean;
}

/**
 * Check if a given object implements the CreateGameRequestGame interface.
 */
export function instanceOfCreateGameRequestGame(value: object): value is CreateGameRequestGame {
    return true;
}

export function CreateGameRequestGameFromJSON(json: any): CreateGameRequestGame {
    return CreateGameRequestGameFromJSONTyped(json, false);
}

export function CreateGameRequestGameFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGameRequestGame {
    if (json == null) {
        return json;
    }
    return {
        
        'homeSchoolId': json['home_school_id'] == null ? undefined : json['home_school_id'],
        'awaySchoolId': json['away_school_id'] == null ? undefined : json['away_school_id'],
        'sportId': json['sport_id'] == null ? undefined : json['sport_id'],
        'gameDate': json['game_date'] == null ? undefined : (new Date(json['game_date'])),
        'neutral': json['neutral'] == null ? undefined : json['neutral'],
    };
}

export function CreateGameRequestGameToJSON(json: any): CreateGameRequestGame {
    return CreateGameRequestGameToJSONTyped(json, false);
}

export function CreateGameRequestGameToJSONTyped(value?: CreateGameRequestGame | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'home_school_id': value['homeSchoolId'],
        'away_school_id': value['awaySchoolId'],
        'sport_id': value['sportId'],
        'game_date': value['gameDate'] == null ? value['gameDate'] : value['gameDate'].toISOString().substring(0,10),
        'neutral': value['neutral'],
    };
}

