/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePasswordReset200Response
 */
export interface CreatePasswordReset200Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreatePasswordReset200Response
     */
    sent?: boolean;
}

/**
 * Check if a given object implements the CreatePasswordReset200Response interface.
 */
export function instanceOfCreatePasswordReset200Response(value: object): value is CreatePasswordReset200Response {
    return true;
}

export function CreatePasswordReset200ResponseFromJSON(json: any): CreatePasswordReset200Response {
    return CreatePasswordReset200ResponseFromJSONTyped(json, false);
}

export function CreatePasswordReset200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePasswordReset200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'sent': json['sent'] == null ? undefined : json['sent'],
    };
}

export function CreatePasswordReset200ResponseToJSON(json: any): CreatePasswordReset200Response {
    return CreatePasswordReset200ResponseToJSONTyped(json, false);
}

export function CreatePasswordReset200ResponseToJSONTyped(value?: CreatePasswordReset200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sent': value['sent'],
    };
}

