/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31473027110
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAdminContractRequestContract
 */
export interface CreateAdminContractRequestContract {
    /**
     * 
     * @type {Date}
     * @memberof CreateAdminContractRequestContract
     */
    startOn?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateAdminContractRequestContract
     */
    endOn?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateAdminContractRequestContract
     */
    atWill?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateAdminContractRequestContract
     */
    contingentChange?: boolean;
}

/**
 * Check if a given object implements the CreateAdminContractRequestContract interface.
 */
export function instanceOfCreateAdminContractRequestContract(value: object): value is CreateAdminContractRequestContract {
    return true;
}

export function CreateAdminContractRequestContractFromJSON(json: any): CreateAdminContractRequestContract {
    return CreateAdminContractRequestContractFromJSONTyped(json, false);
}

export function CreateAdminContractRequestContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAdminContractRequestContract {
    if (json == null) {
        return json;
    }
    return {
        
        'startOn': json['start_on'] == null ? undefined : (new Date(json['start_on'])),
        'endOn': json['end_on'] == null ? undefined : (new Date(json['end_on'])),
        'atWill': json['at_will'] == null ? undefined : json['at_will'],
        'contingentChange': json['contingent_change'] == null ? undefined : json['contingent_change'],
    };
}

export function CreateAdminContractRequestContractToJSON(json: any): CreateAdminContractRequestContract {
    return CreateAdminContractRequestContractToJSONTyped(json, false);
}

export function CreateAdminContractRequestContractToJSONTyped(value?: CreateAdminContractRequestContract | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start_on': value['startOn'] == null ? value['startOn'] : value['startOn'].toISOString().substring(0,10),
        'end_on': value['endOn'] == null ? value['endOn'] : value['endOn'].toISOString().substring(0,10),
        'at_will': value['atWill'],
        'contingent_change': value['contingentChange'],
    };
}

