/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31383289480
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAdminCoachContractRequestImport
 */
export interface CreateAdminCoachContractRequestImport {
    /**
     * 
     * @type {Blob}
     * @memberof CreateAdminCoachContractRequestImport
     */
    file: Blob;
}

/**
 * Check if a given object implements the CreateAdminCoachContractRequestImport interface.
 */
export function instanceOfCreateAdminCoachContractRequestImport(value: object): value is CreateAdminCoachContractRequestImport {
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function CreateAdminCoachContractRequestImportFromJSON(json: any): CreateAdminCoachContractRequestImport {
    return CreateAdminCoachContractRequestImportFromJSONTyped(json, false);
}

export function CreateAdminCoachContractRequestImportFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAdminCoachContractRequestImport {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function CreateAdminCoachContractRequestImportToJSON(json: any): CreateAdminCoachContractRequestImport {
    return CreateAdminCoachContractRequestImportToJSONTyped(json, false);
}

export function CreateAdminCoachContractRequestImportToJSONTyped(value?: CreateAdminCoachContractRequestImport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file': value['file'],
    };
}

