/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.33880123533
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGamePostRequestGamePost
 */
export interface CreateGamePostRequestGamePost {
    /**
     * WINAD-10272 delegated write. Omit to use the current
     * user's own school. Naming another school requires a
     * school-unscoped grant (scheduling_staff / super_admin);
     * otherwise the request is refused with 403.
     * @type {number}
     * @memberof CreateGamePostRequestGamePost
     */
    schoolId?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateGamePostRequestGamePost
     */
    sportId: number;
    /**
     * 
     * @type {Date}
     * @memberof CreateGamePostRequestGamePost
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateGamePostRequestGamePost
     */
    endDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CreateGamePostRequestGamePost
     */
    description?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateGamePostRequestGamePost
     */
    gameTypeIds?: Array<number>;
}

/**
 * Check if a given object implements the CreateGamePostRequestGamePost interface.
 */
export function instanceOfCreateGamePostRequestGamePost(value: object): value is CreateGamePostRequestGamePost {
    if (!('sportId' in value) || value['sportId'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    return true;
}

export function CreateGamePostRequestGamePostFromJSON(json: any): CreateGamePostRequestGamePost {
    return CreateGamePostRequestGamePostFromJSONTyped(json, false);
}

export function CreateGamePostRequestGamePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGamePostRequestGamePost {
    if (json == null) {
        return json;
    }
    return {
        
        'schoolId': json['school_id'] == null ? undefined : json['school_id'],
        'sportId': json['sport_id'],
        'startDate': (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'description': json['description'] == null ? undefined : json['description'],
        'gameTypeIds': json['game_type_ids'] == null ? undefined : json['game_type_ids'],
    };
}

export function CreateGamePostRequestGamePostToJSON(json: any): CreateGamePostRequestGamePost {
    return CreateGamePostRequestGamePostToJSONTyped(json, false);
}

export function CreateGamePostRequestGamePostToJSONTyped(value?: CreateGamePostRequestGamePost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'school_id': value['schoolId'],
        'sport_id': value['sportId'],
        'start_date': value['startDate'].toISOString().substring(0,10),
        'end_date': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'description': value['description'],
        'game_type_ids': value['gameTypeIds'],
    };
}

