/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.52
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CtbGraduateAssistantCompensationApplyInput } from './CtbGraduateAssistantCompensationApplyInput';
import {
    instanceOfCtbGraduateAssistantCompensationApplyInput,
    CtbGraduateAssistantCompensationApplyInputFromJSON,
    CtbGraduateAssistantCompensationApplyInputFromJSONTyped,
    CtbGraduateAssistantCompensationApplyInputToJSON,
} from './CtbGraduateAssistantCompensationApplyInput';
import type { CtbNotEmployedCompensationApplyInput } from './CtbNotEmployedCompensationApplyInput';
import {
    instanceOfCtbNotEmployedCompensationApplyInput,
    CtbNotEmployedCompensationApplyInputFromJSON,
    CtbNotEmployedCompensationApplyInputFromJSONTyped,
    CtbNotEmployedCompensationApplyInputToJSON,
} from './CtbNotEmployedCompensationApplyInput';
import type { CtbVolunteerCompensationApplyInput } from './CtbVolunteerCompensationApplyInput';
import {
    instanceOfCtbVolunteerCompensationApplyInput,
    CtbVolunteerCompensationApplyInputFromJSON,
    CtbVolunteerCompensationApplyInputFromJSONTyped,
    CtbVolunteerCompensationApplyInputToJSON,
} from './CtbVolunteerCompensationApplyInput';

/**
 * @type CtbCompensationApplyInput
 * 
 * @export
 */
export type CtbCompensationApplyInput = { role: 'graduate_assistant' } & CtbGraduateAssistantCompensationApplyInput | { role: 'not_employed' } & CtbNotEmployedCompensationApplyInput | { role: 'volunteer' } & CtbVolunteerCompensationApplyInput;

export function CtbCompensationApplyInputFromJSON(json: any): CtbCompensationApplyInput {
    return CtbCompensationApplyInputFromJSONTyped(json, false);
}

export function CtbCompensationApplyInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CtbCompensationApplyInput {
    if (json == null) {
        return json;
    }
    switch (json['role']) {
        case 'graduate_assistant':
            return Object.assign({}, CtbGraduateAssistantCompensationApplyInputFromJSONTyped(json, true), { role: 'graduate_assistant' } as const);
        case 'not_employed':
            return Object.assign({}, CtbNotEmployedCompensationApplyInputFromJSONTyped(json, true), { role: 'not_employed' } as const);
        case 'volunteer':
            return Object.assign({}, CtbVolunteerCompensationApplyInputFromJSONTyped(json, true), { role: 'volunteer' } as const);
        default:
            return json;
    }
}

export function CtbCompensationApplyInputToJSON(json: any): any {
    return CtbCompensationApplyInputToJSONTyped(json, false);
}

export function CtbCompensationApplyInputToJSONTyped(value?: CtbCompensationApplyInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['role']) {
        case 'graduate_assistant':
            return Object.assign({}, CtbGraduateAssistantCompensationApplyInputToJSON(value), { role: 'graduate_assistant' } as const);
        case 'not_employed':
            return Object.assign({}, CtbNotEmployedCompensationApplyInputToJSON(value), { role: 'not_employed' } as const);
        case 'volunteer':
            return Object.assign({}, CtbVolunteerCompensationApplyInputToJSON(value), { role: 'volunteer' } as const);
        default:
            return value;
    }
}

