/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.55.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Nonnegative decimal with at most two decimal places, or null to clear.
 * @export
 * @interface DealUpdateAmount
 */
export interface DealUpdateAmount {
}

/**
 * Check if a given object implements the DealUpdateAmount interface.
 */
export function instanceOfDealUpdateAmount(value: object): value is DealUpdateAmount {
    return true;
}

export function DealUpdateAmountFromJSON(json: any): DealUpdateAmount {
    return DealUpdateAmountFromJSONTyped(json, false);
}

export function DealUpdateAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): DealUpdateAmount {
    return json;
}

export function DealUpdateAmountToJSON(json: any): DealUpdateAmount {
    return DealUpdateAmountToJSONTyped(json, false);
}

export function DealUpdateAmountToJSONTyped(value?: DealUpdateAmount | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

