/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { Deal } from './Deal';
import {
    DealFromJSON,
    DealFromJSONTyped,
    DealToJSON,
    DealToJSONTyped,
} from './Deal';

/**
 * 
 * @export
 * @interface DealCollection
 */
export interface DealCollection {
    /**
     * 
     * @type {Array<Deal>}
     * @memberof DealCollection
     */
    data?: Array<Deal>;
    /**
     * 
     * @type {Meta}
     * @memberof DealCollection
     */
    meta?: Meta;
}

/**
 * Check if a given object implements the DealCollection interface.
 */
export function instanceOfDealCollection(value: object): value is DealCollection {
    return true;
}

export function DealCollectionFromJSON(json: any): DealCollection {
    return DealCollectionFromJSONTyped(json, false);
}

export function DealCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DealCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DealFromJSON)),
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
    };
}

export function DealCollectionToJSON(json: any): DealCollection {
    return DealCollectionToJSONTyped(json, false);
}

export function DealCollectionToJSONTyped(value?: DealCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DealToJSON)),
        'meta': MetaToJSON(value['meta']),
    };
}

