/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DealSearchResult
 */
export interface DealSearchResult {
    /**
     * 
     * @type {number}
     * @memberof DealSearchResult
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof DealSearchResult
     */
    dealId?: number;
    /**
     * 
     * @type {number}
     * @memberof DealSearchResult
     */
    schoolId?: number;
    /**
     * 
     * @type {string}
     * @memberof DealSearchResult
     */
    schoolName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DealSearchResult
     */
    conferenceName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DealSearchResult
     */
    conferenceId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DealSearchResult
     */
    divisionId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DealSearchResult
     */
    dealTypeName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DealSearchResult
     */
    dealTypeId?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DealSearchResult
     */
    vendorNames?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DealSearchResult
     */
    startYear?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DealSearchResult
     */
    endYear?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof DealSearchResult
     */
    startAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof DealSearchResult
     */
    summary?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DealSearchResult
     */
    autorenew?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof DealSearchResult
     */
    archived?: boolean | null;
}

/**
 * Check if a given object implements the DealSearchResult interface.
 */
export function instanceOfDealSearchResult(value: object): value is DealSearchResult {
    return true;
}

export function DealSearchResultFromJSON(json: any): DealSearchResult {
    return DealSearchResultFromJSONTyped(json, false);
}

export function DealSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): DealSearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'dealId': json['deal_id'] == null ? undefined : json['deal_id'],
        'schoolId': json['school_id'] == null ? undefined : json['school_id'],
        'schoolName': json['school_name'] == null ? undefined : json['school_name'],
        'conferenceName': json['conference_name'] == null ? undefined : json['conference_name'],
        'conferenceId': json['conference_id'] == null ? undefined : json['conference_id'],
        'divisionId': json['division_id'] == null ? undefined : json['division_id'],
        'dealTypeName': json['deal_type_name'] == null ? undefined : json['deal_type_name'],
        'dealTypeId': json['deal_type_id'] == null ? undefined : json['deal_type_id'],
        'vendorNames': json['vendor_names'] == null ? undefined : json['vendor_names'],
        'startYear': json['start_year'] == null ? undefined : json['start_year'],
        'endYear': json['end_year'] == null ? undefined : json['end_year'],
        'startAt': json['start_at'] == null ? undefined : (new Date(json['start_at'])),
        'summary': json['summary'] == null ? undefined : json['summary'],
        'autorenew': json['autorenew'] == null ? undefined : json['autorenew'],
        'archived': json['archived'] == null ? undefined : json['archived'],
    };
}

export function DealSearchResultToJSON(json: any): DealSearchResult {
    return DealSearchResultToJSONTyped(json, false);
}

export function DealSearchResultToJSONTyped(value?: DealSearchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'deal_id': value['dealId'],
        'school_id': value['schoolId'],
        'school_name': value['schoolName'],
        'conference_name': value['conferenceName'],
        'conference_id': value['conferenceId'],
        'division_id': value['divisionId'],
        'deal_type_name': value['dealTypeName'],
        'deal_type_id': value['dealTypeId'],
        'vendor_names': value['vendorNames'],
        'start_year': value['startYear'],
        'end_year': value['endYear'],
        'start_at': value['startAt'] == null ? value['startAt'] : value['startAt'].toISOString(),
        'summary': value['summary'],
        'autorenew': value['autorenew'],
        'archived': value['archived'],
    };
}

