/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteNote200Response
 */
export interface DeleteNote200Response {
    /**
     * 
     * @type {boolean}
     * @memberof DeleteNote200Response
     */
    success?: boolean;
}

/**
 * Check if a given object implements the DeleteNote200Response interface.
 */
export function instanceOfDeleteNote200Response(value: object): value is DeleteNote200Response {
    return true;
}

export function DeleteNote200ResponseFromJSON(json: any): DeleteNote200Response {
    return DeleteNote200ResponseFromJSONTyped(json, false);
}

export function DeleteNote200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteNote200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function DeleteNote200ResponseToJSON(json: any): DeleteNote200Response {
    return DeleteNote200ResponseToJSONTyped(json, false);
}

export function DeleteNote200ResponseToJSONTyped(value?: DeleteNote200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

