/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.30806351653
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DepartmentFinancialsQuadrantPoint } from './DepartmentFinancialsQuadrantPoint';
import {
    DepartmentFinancialsQuadrantPointFromJSON,
    DepartmentFinancialsQuadrantPointFromJSONTyped,
    DepartmentFinancialsQuadrantPointToJSON,
    DepartmentFinancialsQuadrantPointToJSONTyped,
} from './DepartmentFinancialsQuadrantPoint';
import type { DepartmentFinancialsUnplottedSchool } from './DepartmentFinancialsUnplottedSchool';
import {
    DepartmentFinancialsUnplottedSchoolFromJSON,
    DepartmentFinancialsUnplottedSchoolFromJSONTyped,
    DepartmentFinancialsUnplottedSchoolToJSON,
    DepartmentFinancialsUnplottedSchoolToJSONTyped,
} from './DepartmentFinancialsUnplottedSchool';

/**
 * 
 * @export
 * @interface DepartmentFinancialsQuadrant
 */
export interface DepartmentFinancialsQuadrant {
    /**
     * 
     * @type {number}
     * @memberof DepartmentFinancialsQuadrant
     */
    cohortSize?: number;
    /**
     * 
     * @type {Array<DepartmentFinancialsQuadrantPoint>}
     * @memberof DepartmentFinancialsQuadrant
     */
    points?: Array<DepartmentFinancialsQuadrantPoint>;
    /**
     * 
     * @type {Array<DepartmentFinancialsUnplottedSchool>}
     * @memberof DepartmentFinancialsQuadrant
     */
    unplotted?: Array<DepartmentFinancialsUnplottedSchool>;
}

/**
 * Check if a given object implements the DepartmentFinancialsQuadrant interface.
 */
export function instanceOfDepartmentFinancialsQuadrant(value: object): value is DepartmentFinancialsQuadrant {
    return true;
}

export function DepartmentFinancialsQuadrantFromJSON(json: any): DepartmentFinancialsQuadrant {
    return DepartmentFinancialsQuadrantFromJSONTyped(json, false);
}

export function DepartmentFinancialsQuadrantFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepartmentFinancialsQuadrant {
    if (json == null) {
        return json;
    }
    return {
        
        'cohortSize': json['cohort_size'] == null ? undefined : json['cohort_size'],
        'points': json['points'] == null ? undefined : ((json['points'] as Array<any>).map(DepartmentFinancialsQuadrantPointFromJSON)),
        'unplotted': json['unplotted'] == null ? undefined : ((json['unplotted'] as Array<any>).map(DepartmentFinancialsUnplottedSchoolFromJSON)),
    };
}

export function DepartmentFinancialsQuadrantToJSON(json: any): DepartmentFinancialsQuadrant {
    return DepartmentFinancialsQuadrantToJSONTyped(json, false);
}

export function DepartmentFinancialsQuadrantToJSONTyped(value?: DepartmentFinancialsQuadrant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cohort_size': value['cohortSize'],
        'points': value['points'] == null ? undefined : ((value['points'] as Array<any>).map(DepartmentFinancialsQuadrantPointToJSON)),
        'unplotted': value['unplotted'] == null ? undefined : ((value['unplotted'] as Array<any>).map(DepartmentFinancialsUnplottedSchoolToJSON)),
    };
}

