/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31153399906
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Percentiles over the filed annual amounts, PERCENTILE_CONT interpolation; null when comp is withheld or nothing is filed
 * @export
 * @interface DepartmentAdministratorsStaffStats
 */
export interface DepartmentAdministratorsStaffStats {
    /**
     * 
     * @type {number}
     * @memberof DepartmentAdministratorsStaffStats
     */
    withCompCount: number;
    /**
     * 
     * @type {number}
     * @memberof DepartmentAdministratorsStaffStats
     */
    medianCents: number;
    /**
     * 
     * @type {number}
     * @memberof DepartmentAdministratorsStaffStats
     */
    p25Cents: number;
    /**
     * 
     * @type {number}
     * @memberof DepartmentAdministratorsStaffStats
     */
    p75Cents: number;
    /**
     * 
     * @type {number}
     * @memberof DepartmentAdministratorsStaffStats
     */
    meanCents: number;
    /**
     * True when 990 amounts are in the pool or some seats carry no comp
     * @type {boolean}
     * @memberof DepartmentAdministratorsStaffStats
     */
    estimated: boolean;
}

/**
 * Check if a given object implements the DepartmentAdministratorsStaffStats interface.
 */
export function instanceOfDepartmentAdministratorsStaffStats(value: object): value is DepartmentAdministratorsStaffStats {
    if (!('withCompCount' in value) || value['withCompCount'] === undefined) return false;
    if (!('medianCents' in value) || value['medianCents'] === undefined) return false;
    if (!('p25Cents' in value) || value['p25Cents'] === undefined) return false;
    if (!('p75Cents' in value) || value['p75Cents'] === undefined) return false;
    if (!('meanCents' in value) || value['meanCents'] === undefined) return false;
    if (!('estimated' in value) || value['estimated'] === undefined) return false;
    return true;
}

export function DepartmentAdministratorsStaffStatsFromJSON(json: any): DepartmentAdministratorsStaffStats {
    return DepartmentAdministratorsStaffStatsFromJSONTyped(json, false);
}

export function DepartmentAdministratorsStaffStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepartmentAdministratorsStaffStats {
    if (json == null) {
        return json;
    }
    return {
        
        'withCompCount': json['with_comp_count'],
        'medianCents': json['median_cents'],
        'p25Cents': json['p25_cents'],
        'p75Cents': json['p75_cents'],
        'meanCents': json['mean_cents'],
        'estimated': json['estimated'],
    };
}

export function DepartmentAdministratorsStaffStatsToJSON(json: any): DepartmentAdministratorsStaffStats {
    return DepartmentAdministratorsStaffStatsToJSONTyped(json, false);
}

export function DepartmentAdministratorsStaffStatsToJSONTyped(value?: DepartmentAdministratorsStaffStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'with_comp_count': value['withCompCount'],
        'median_cents': value['medianCents'],
        'p25_cents': value['p25Cents'],
        'p75_cents': value['p75Cents'],
        'mean_cents': value['meanCents'],
        'estimated': value['estimated'],
    };
}

