/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.67
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DepartmentAdministratorsScorecardGap
 */
export interface DepartmentAdministratorsScorecardGap {
    /**
     * 
     * @type {string}
     * @memberof DepartmentAdministratorsScorecardGap
     */
    lens: DepartmentAdministratorsScorecardGapLensEnum;
    /**
     * 
     * @type {number}
     * @memberof DepartmentAdministratorsScorecardGap
     */
    year: number;
    /**
     * 
     * @type {number}
     * @memberof DepartmentAdministratorsScorecardGap
     */
    latestAvailableYear: number | null;
}


/**
 * @export
 */
export const DepartmentAdministratorsScorecardGapLensEnum = {
    DirectorsCup: 'directors_cup'
} as const;
export type DepartmentAdministratorsScorecardGapLensEnum = typeof DepartmentAdministratorsScorecardGapLensEnum[keyof typeof DepartmentAdministratorsScorecardGapLensEnum];


/**
 * Check if a given object implements the DepartmentAdministratorsScorecardGap interface.
 */
export function instanceOfDepartmentAdministratorsScorecardGap(value: object): value is DepartmentAdministratorsScorecardGap {
    if (!('lens' in value) || value['lens'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('latestAvailableYear' in value) || value['latestAvailableYear'] === undefined) return false;
    return true;
}

export function DepartmentAdministratorsScorecardGapFromJSON(json: any): DepartmentAdministratorsScorecardGap {
    return DepartmentAdministratorsScorecardGapFromJSONTyped(json, false);
}

export function DepartmentAdministratorsScorecardGapFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepartmentAdministratorsScorecardGap {
    if (json == null) {
        return json;
    }
    return {
        
        'lens': json['lens'],
        'year': json['year'],
        'latestAvailableYear': json['latest_available_year'],
    };
}

export function DepartmentAdministratorsScorecardGapToJSON(json: any): DepartmentAdministratorsScorecardGap {
    return DepartmentAdministratorsScorecardGapToJSONTyped(json, false);
}

export function DepartmentAdministratorsScorecardGapToJSONTyped(value?: DepartmentAdministratorsScorecardGap | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lens': value['lens'],
        'year': value['year'],
        'latest_available_year': value['latestAvailableYear'],
    };
}

