/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.54.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Suppressed (null) when the source reports no salary, coach count or FTE, when any of them is not positive, or when the salary is negative
 * @export
 * @interface DepartmentFinancialsEadaCategory
 */
export interface DepartmentFinancialsEadaCategory {
    /**
     * Average annual institutional salary per coach, as reported — never a total pool
     * @type {number}
     * @memberof DepartmentFinancialsEadaCategory
     */
    averageSalaryCents: number;
    /**
     * 
     * @type {number}
     * @memberof DepartmentFinancialsEadaCategory
     */
    coachCount: number;
    /**
     * 
     * @type {number}
     * @memberof DepartmentFinancialsEadaCategory
     */
    fte: number;
}

/**
 * Check if a given object implements the DepartmentFinancialsEadaCategory interface.
 */
export function instanceOfDepartmentFinancialsEadaCategory(value: object): value is DepartmentFinancialsEadaCategory {
    if (!('averageSalaryCents' in value) || value['averageSalaryCents'] === undefined) return false;
    if (!('coachCount' in value) || value['coachCount'] === undefined) return false;
    if (!('fte' in value) || value['fte'] === undefined) return false;
    return true;
}

export function DepartmentFinancialsEadaCategoryFromJSON(json: any): DepartmentFinancialsEadaCategory {
    return DepartmentFinancialsEadaCategoryFromJSONTyped(json, false);
}

export function DepartmentFinancialsEadaCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepartmentFinancialsEadaCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'averageSalaryCents': json['average_salary_cents'],
        'coachCount': json['coach_count'],
        'fte': json['fte'],
    };
}

export function DepartmentFinancialsEadaCategoryToJSON(json: any): DepartmentFinancialsEadaCategory {
    return DepartmentFinancialsEadaCategoryToJSONTyped(json, false);
}

export function DepartmentFinancialsEadaCategoryToJSONTyped(value?: DepartmentFinancialsEadaCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'average_salary_cents': value['averageSalaryCents'],
        'coach_count': value['coachCount'],
        'fte': value['fte'],
    };
}

