/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.69-dev.10283
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DepartmentOverviewPrivateDisclosureLine } from './DepartmentOverviewPrivateDisclosureLine';
import {
    DepartmentOverviewPrivateDisclosureLineFromJSON,
    DepartmentOverviewPrivateDisclosureLineFromJSONTyped,
    DepartmentOverviewPrivateDisclosureLineToJSON,
    DepartmentOverviewPrivateDisclosureLineToJSONTyped,
} from './DepartmentOverviewPrivateDisclosureLine';

/**
 * 
 * @export
 * @interface DepartmentOverviewPrivateDisclosure
 */
export interface DepartmentOverviewPrivateDisclosure {
    /**
     * 
     * @type {Array<DepartmentOverviewPrivateDisclosureLine>}
     * @memberof DepartmentOverviewPrivateDisclosure
     */
    firstClass: Array<DepartmentOverviewPrivateDisclosureLine>;
    /**
     * 
     * @type {Array<DepartmentOverviewPrivateDisclosureLine>}
     * @memberof DepartmentOverviewPrivateDisclosure
     */
    degrades: Array<DepartmentOverviewPrivateDisclosureLine>;
}

/**
 * Check if a given object implements the DepartmentOverviewPrivateDisclosure interface.
 */
export function instanceOfDepartmentOverviewPrivateDisclosure(value: object): value is DepartmentOverviewPrivateDisclosure {
    if (!('firstClass' in value) || value['firstClass'] === undefined) return false;
    if (!('degrades' in value) || value['degrades'] === undefined) return false;
    return true;
}

export function DepartmentOverviewPrivateDisclosureFromJSON(json: any): DepartmentOverviewPrivateDisclosure {
    return DepartmentOverviewPrivateDisclosureFromJSONTyped(json, false);
}

export function DepartmentOverviewPrivateDisclosureFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepartmentOverviewPrivateDisclosure {
    if (json == null) {
        return json;
    }
    return {
        
        'firstClass': ((json['first_class'] as Array<any>).map(DepartmentOverviewPrivateDisclosureLineFromJSON)),
        'degrades': ((json['degrades'] as Array<any>).map(DepartmentOverviewPrivateDisclosureLineFromJSON)),
    };
}

export function DepartmentOverviewPrivateDisclosureToJSON(json: any): DepartmentOverviewPrivateDisclosure {
    return DepartmentOverviewPrivateDisclosureToJSONTyped(json, false);
}

export function DepartmentOverviewPrivateDisclosureToJSONTyped(value?: DepartmentOverviewPrivateDisclosure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_class': ((value['firstClass'] as Array<any>).map(DepartmentOverviewPrivateDisclosureLineToJSON)),
        'degrades': ((value['degrades'] as Array<any>).map(DepartmentOverviewPrivateDisclosureLineToJSON)),
    };
}

