/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.55.8-dev.10620
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeskQueueEngagementCoverage
 */
export interface DeskQueueEngagementCoverage {
    /**
     * 
     * @type {Array<string>}
     * @memberof DeskQueueEngagementCoverage
     */
    reasons: Array<DeskQueueEngagementCoverageReasonsEnum>;
}


/**
 * @export
 */
export const DeskQueueEngagementCoverageReasonsEnum = {
    BeforePublication: 'before_publication',
    MaximumRange: 'maximum_range',
    SchemaCoverage: 'schema_coverage',
    SourceRetention: 'source_retention',
    IngestionDelayPossible: 'ingestion_delay_possible',
    LegacyEvents: 'legacy_events'
} as const;
export type DeskQueueEngagementCoverageReasonsEnum = typeof DeskQueueEngagementCoverageReasonsEnum[keyof typeof DeskQueueEngagementCoverageReasonsEnum];


/**
 * Check if a given object implements the DeskQueueEngagementCoverage interface.
 */
export function instanceOfDeskQueueEngagementCoverage(value: object): value is DeskQueueEngagementCoverage {
    if (!('reasons' in value) || value['reasons'] === undefined) return false;
    return true;
}

export function DeskQueueEngagementCoverageFromJSON(json: any): DeskQueueEngagementCoverage {
    return DeskQueueEngagementCoverageFromJSONTyped(json, false);
}

export function DeskQueueEngagementCoverageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeskQueueEngagementCoverage {
    if (json == null) {
        return json;
    }
    return {
        
        'reasons': json['reasons'],
    };
}

export function DeskQueueEngagementCoverageToJSON(json: any): DeskQueueEngagementCoverage {
    return DeskQueueEngagementCoverageToJSONTyped(json, false);
}

export function DeskQueueEngagementCoverageToJSONTyped(value?: DeskQueueEngagementCoverage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reasons': value['reasons'],
    };
}

