/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.73-dev.10297
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeskReportSummaryCover } from './DeskReportSummaryCover';
import {
    DeskReportSummaryCoverFromJSON,
    DeskReportSummaryCoverFromJSONTyped,
    DeskReportSummaryCoverToJSON,
    DeskReportSummaryCoverToJSONTyped,
} from './DeskReportSummaryCover';
import type { DeskRequestContext } from './DeskRequestContext';
import {
    DeskRequestContextFromJSON,
    DeskRequestContextFromJSONTyped,
    DeskRequestContextToJSON,
    DeskRequestContextToJSONTyped,
} from './DeskRequestContext';
import type { DeskReportVersion } from './DeskReportVersion';
import {
    DeskReportVersionFromJSON,
    DeskReportVersionFromJSONTyped,
    DeskReportVersionToJSON,
    DeskReportVersionToJSONTyped,
} from './DeskReportVersion';
import type { DeskReportFullAllOfSections } from './DeskReportFullAllOfSections';
import {
    DeskReportFullAllOfSectionsFromJSON,
    DeskReportFullAllOfSectionsFromJSONTyped,
    DeskReportFullAllOfSectionsToJSON,
    DeskReportFullAllOfSectionsToJSONTyped,
} from './DeskReportFullAllOfSections';
import type { DeskReportArtifact } from './DeskReportArtifact';
import {
    DeskReportArtifactFromJSON,
    DeskReportArtifactFromJSONTyped,
    DeskReportArtifactToJSON,
    DeskReportArtifactToJSONTyped,
} from './DeskReportArtifact';
import type { DeskHeadlineStat } from './DeskHeadlineStat';
import {
    DeskHeadlineStatFromJSON,
    DeskHeadlineStatFromJSONTyped,
    DeskHeadlineStatToJSON,
    DeskHeadlineStatToJSONTyped,
} from './DeskHeadlineStat';

/**
 * 
 * @export
 * @interface DeskReportFull
 */
export interface DeskReportFull {
    /**
     * 
     * @type {string}
     * @memberof DeskReportFull
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof DeskReportFull
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof DeskReportFull
     */
    category: DeskReportFullCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof DeskReportFull
     */
    reportType: DeskReportFullReportTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DeskReportFull
     */
    summary: string | null;
    /**
     * 
     * @type {Array<DeskHeadlineStat>}
     * @memberof DeskReportFull
     */
    headlineStats: Array<DeskHeadlineStat>;
    /**
     * 
     * @type {DeskReportSummaryCover}
     * @memberof DeskReportFull
     */
    cover: DeskReportSummaryCover;
    /**
     * 
     * @type {Date}
     * @memberof DeskReportFull
     */
    publishedAt: Date;
    /**
     * The current version's publish time once past v1 (the UPDATED badge); null at v1
     * @type {Date}
     * @memberof DeskReportFull
     */
    updatedAt: Date | null;
    /**
     * 
     * @type {number}
     * @memberof DeskReportFull
     */
    pageCount: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DeskReportFull
     */
    artifactKinds: Array<DeskReportFullArtifactKindsEnum>;
    /**
     * 
     * @type {Array<DeskReportArtifact>}
     * @memberof DeskReportFull
     */
    artifacts: Array<DeskReportArtifact>;
    /**
     * 
     * @type {string}
     * @memberof DeskReportFull
     */
    rerunCadence: DeskReportFullRerunCadenceEnum;
    /**
     * 
     * @type {string}
     * @memberof DeskReportFull
     */
    pushExample: string | null;
    /**
     * No read row for the caller, or a newer version than the one last opened. Archiving
     * (D-24) creates the row, so an archived-but-never-opened report is not unread — "unread"
     * is the badge rule, not "never opened"; first_open on the full payload is the latter.
     * 
     * @type {boolean}
     * @memberof DeskReportFull
     */
    unread: boolean;
    /**
     * The caller archived this report (per user, WINAD-10348 / D-24)
     * @type {boolean}
     * @memberof DeskReportFull
     */
    archived: boolean;
    /**
     * 
     * @type {DeskRequestContext}
     * @memberof DeskReportFull
     */
    requestContext: DeskRequestContext | null;
    /**
     * Sanitized desk-report v1 markup (doc/desk/report-markup.md)
     * @type {string}
     * @memberof DeskReportFull
     */
    bodyHtml: string;
    /**
     * The reader's "What changed" list (D-23): every published version, newest first,
     * with the reader-facing change note only — the internal history note never leaves
     * the admin API. v1 carries no note ("First edition").
     * 
     * @type {Array<DeskReportVersion>}
     * @memberof DeskReportFull
     */
    versions: Array<DeskReportVersion>;
    /**
     * 
     * @type {Array<DeskReportFullAllOfSections>}
     * @memberof DeskReportFull
     */
    sections: Array<DeskReportFullAllOfSections>;
    /**
     * 
     * @type {number}
     * @memberof DeskReportFull
     */
    versionNumber: number;
    /**
     * True when the caller has no read row yet (drives the 04.2 provenance strip)
     * @type {boolean}
     * @memberof DeskReportFull
     */
    firstOpen: boolean;
}


/**
 * @export
 */
export const DeskReportFullCategoryEnum = {
    Financials: 'Financials',
    Coaching: 'Coaching',
    Vendors: 'Vendors',
    Administrators: 'Administrators'
} as const;
export type DeskReportFullCategoryEnum = typeof DeskReportFullCategoryEnum[keyof typeof DeskReportFullCategoryEnum];

/**
 * @export
 */
export const DeskReportFullReportTypeEnum = {
    IntelligenceBrief: 'intelligence_brief',
    Wcci: 'wcci',
    StaffComp: 'staff_comp',
    VendorBook: 'vendor_book',
    Financial: 'financial',
    BudgetProposal: 'budget_proposal',
    Buyout: 'buyout',
    DecisionBrief: 'decision_brief'
} as const;
export type DeskReportFullReportTypeEnum = typeof DeskReportFullReportTypeEnum[keyof typeof DeskReportFullReportTypeEnum];

/**
 * @export
 */
export const DeskReportFullArtifactKindsEnum = {
    Pdf: 'pdf',
    Xlsx: 'xlsx',
    Pptx: 'pptx'
} as const;
export type DeskReportFullArtifactKindsEnum = typeof DeskReportFullArtifactKindsEnum[keyof typeof DeskReportFullArtifactKindsEnum];

/**
 * @export
 */
export const DeskReportFullRerunCadenceEnum = {
    Off: 'off',
    Quarterly: 'quarterly',
    OnNewFiling: 'on_new_filing',
    OnNewDeal: 'on_new_deal'
} as const;
export type DeskReportFullRerunCadenceEnum = typeof DeskReportFullRerunCadenceEnum[keyof typeof DeskReportFullRerunCadenceEnum];


/**
 * Check if a given object implements the DeskReportFull interface.
 */
export function instanceOfDeskReportFull(value: object): value is DeskReportFull {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('reportType' in value) || value['reportType'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('headlineStats' in value) || value['headlineStats'] === undefined) return false;
    if (!('cover' in value) || value['cover'] === undefined) return false;
    if (!('publishedAt' in value) || value['publishedAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('pageCount' in value) || value['pageCount'] === undefined) return false;
    if (!('artifactKinds' in value) || value['artifactKinds'] === undefined) return false;
    if (!('artifacts' in value) || value['artifacts'] === undefined) return false;
    if (!('rerunCadence' in value) || value['rerunCadence'] === undefined) return false;
    if (!('pushExample' in value) || value['pushExample'] === undefined) return false;
    if (!('unread' in value) || value['unread'] === undefined) return false;
    if (!('archived' in value) || value['archived'] === undefined) return false;
    if (!('requestContext' in value) || value['requestContext'] === undefined) return false;
    if (!('bodyHtml' in value) || value['bodyHtml'] === undefined) return false;
    if (!('versions' in value) || value['versions'] === undefined) return false;
    if (!('sections' in value) || value['sections'] === undefined) return false;
    if (!('versionNumber' in value) || value['versionNumber'] === undefined) return false;
    if (!('firstOpen' in value) || value['firstOpen'] === undefined) return false;
    return true;
}

export function DeskReportFullFromJSON(json: any): DeskReportFull {
    return DeskReportFullFromJSONTyped(json, false);
}

export function DeskReportFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeskReportFull {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'title': json['title'],
        'category': json['category'],
        'reportType': json['report_type'],
        'summary': json['summary'],
        'headlineStats': ((json['headline_stats'] as Array<any>).map(DeskHeadlineStatFromJSON)),
        'cover': DeskReportSummaryCoverFromJSON(json['cover']),
        'publishedAt': (new Date(json['published_at'])),
        'updatedAt': (json['updated_at'] == null ? null : new Date(json['updated_at'])),
        'pageCount': json['page_count'],
        'artifactKinds': json['artifact_kinds'],
        'artifacts': ((json['artifacts'] as Array<any>).map(DeskReportArtifactFromJSON)),
        'rerunCadence': json['rerun_cadence'],
        'pushExample': json['push_example'],
        'unread': json['unread'],
        'archived': json['archived'],
        'requestContext': DeskRequestContextFromJSON(json['request_context']),
        'bodyHtml': json['body_html'],
        'versions': ((json['versions'] as Array<any>).map(DeskReportVersionFromJSON)),
        'sections': ((json['sections'] as Array<any>).map(DeskReportFullAllOfSectionsFromJSON)),
        'versionNumber': json['version_number'],
        'firstOpen': json['first_open'],
    };
}

export function DeskReportFullToJSON(json: any): DeskReportFull {
    return DeskReportFullToJSONTyped(json, false);
}

export function DeskReportFullToJSONTyped(value?: DeskReportFull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uuid': value['uuid'],
        'title': value['title'],
        'category': value['category'],
        'report_type': value['reportType'],
        'summary': value['summary'],
        'headline_stats': ((value['headlineStats'] as Array<any>).map(DeskHeadlineStatToJSON)),
        'cover': DeskReportSummaryCoverToJSON(value['cover']),
        'published_at': value['publishedAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'page_count': value['pageCount'],
        'artifact_kinds': value['artifactKinds'],
        'artifacts': ((value['artifacts'] as Array<any>).map(DeskReportArtifactToJSON)),
        'rerun_cadence': value['rerunCadence'],
        'push_example': value['pushExample'],
        'unread': value['unread'],
        'archived': value['archived'],
        'request_context': DeskRequestContextToJSON(value['requestContext']),
        'body_html': value['bodyHtml'],
        'versions': ((value['versions'] as Array<any>).map(DeskReportVersionToJSON)),
        'sections': ((value['sections'] as Array<any>).map(DeskReportFullAllOfSectionsToJSON)),
        'version_number': value['versionNumber'],
        'first_open': value['firstOpen'],
    };
}

