/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.54.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeskReportArchiveResponseData } from './DeskReportArchiveResponseData';
import {
    DeskReportArchiveResponseDataFromJSON,
    DeskReportArchiveResponseDataFromJSONTyped,
    DeskReportArchiveResponseDataToJSON,
    DeskReportArchiveResponseDataToJSONTyped,
} from './DeskReportArchiveResponseData';

/**
 * 
 * @export
 * @interface DeskReportArchiveResponse
 */
export interface DeskReportArchiveResponse {
    /**
     * 
     * @type {DeskReportArchiveResponseData}
     * @memberof DeskReportArchiveResponse
     */
    data: DeskReportArchiveResponseData;
}

/**
 * Check if a given object implements the DeskReportArchiveResponse interface.
 */
export function instanceOfDeskReportArchiveResponse(value: object): value is DeskReportArchiveResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DeskReportArchiveResponseFromJSON(json: any): DeskReportArchiveResponse {
    return DeskReportArchiveResponseFromJSONTyped(json, false);
}

export function DeskReportArchiveResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeskReportArchiveResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': DeskReportArchiveResponseDataFromJSON(json['data']),
    };
}

export function DeskReportArchiveResponseToJSON(json: any): DeskReportArchiveResponse {
    return DeskReportArchiveResponseToJSONTyped(json, false);
}

export function DeskReportArchiveResponseToJSONTyped(value?: DeskReportArchiveResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DeskReportArchiveResponseDataToJSON(value['data']),
    };
}

