/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.33163395279
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeskReportFullAllOfSections
 */
export interface DeskReportFullAllOfSections {
    /**
     * 
     * @type {string}
     * @memberof DeskReportFullAllOfSections
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DeskReportFullAllOfSections
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof DeskReportFullAllOfSections
     */
    index: number;
}

/**
 * Check if a given object implements the DeskReportFullAllOfSections interface.
 */
export function instanceOfDeskReportFullAllOfSections(value: object): value is DeskReportFullAllOfSections {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    return true;
}

export function DeskReportFullAllOfSectionsFromJSON(json: any): DeskReportFullAllOfSections {
    return DeskReportFullAllOfSectionsFromJSONTyped(json, false);
}

export function DeskReportFullAllOfSectionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeskReportFullAllOfSections {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'index': json['index'],
    };
}

export function DeskReportFullAllOfSectionsToJSON(json: any): DeskReportFullAllOfSections {
    return DeskReportFullAllOfSectionsToJSONTyped(json, false);
}

export function DeskReportFullAllOfSectionsToJSONTyped(value?: DeskReportFullAllOfSections | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'index': value['index'],
    };
}

