/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.54.0-dev.10297
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeskHeadlineStat } from './DeskHeadlineStat';
import {
    DeskHeadlineStatFromJSON,
    DeskHeadlineStatFromJSONTyped,
    DeskHeadlineStatToJSON,
    DeskHeadlineStatToJSONTyped,
} from './DeskHeadlineStat';

/**
 * 
 * @export
 * @interface DeskAdminCover
 */
export interface DeskAdminCover {
    /**
     * 
     * @type {string}
     * @memberof DeskAdminCover
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof DeskAdminCover
     */
    category?: DeskAdminCoverCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof DeskAdminCover
     */
    reportType?: DeskAdminCoverReportTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DeskAdminCover
     */
    summary?: string | null;
    /**
     * 
     * @type {Array<DeskHeadlineStat>}
     * @memberof DeskAdminCover
     */
    headlineStats?: Array<DeskHeadlineStat>;
    /**
     * 
     * @type {string}
     * @memberof DeskAdminCover
     */
    coverTreatment?: DeskAdminCoverCoverTreatmentEnum;
    /**
     * Defaults to "THE DESK · PREPARED FOR <ACCOUNT>" on create
     * @type {string}
     * @memberof DeskAdminCover
     */
    coverKicker?: string | null;
    /**
     * Decorative corner mark ("24", "AD"); blank clears it
     * @type {string}
     * @memberof DeskAdminCover
     */
    coverNumeral?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DeskAdminCover
     */
    pageCount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DeskAdminCover
     */
    pushExample?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeskAdminCover
     */
    rerunCadence?: DeskAdminCoverRerunCadenceEnum;
}


/**
 * @export
 */
export const DeskAdminCoverCategoryEnum = {
    Financials: 'Financials',
    Coaching: 'Coaching',
    Vendors: 'Vendors',
    Administrators: 'Administrators'
} as const;
export type DeskAdminCoverCategoryEnum = typeof DeskAdminCoverCategoryEnum[keyof typeof DeskAdminCoverCategoryEnum];

/**
 * @export
 */
export const DeskAdminCoverReportTypeEnum = {
    IntelligenceBrief: 'intelligence_brief',
    Wcci: 'wcci',
    StaffComp: 'staff_comp',
    VendorBook: 'vendor_book',
    Financial: 'financial',
    BudgetProposal: 'budget_proposal',
    Buyout: 'buyout',
    DecisionBrief: 'decision_brief'
} as const;
export type DeskAdminCoverReportTypeEnum = typeof DeskAdminCoverReportTypeEnum[keyof typeof DeskAdminCoverReportTypeEnum];

/**
 * @export
 */
export const DeskAdminCoverCoverTreatmentEnum = {
    Ink: 'ink',
    Oxblood: 'oxblood',
    Bone: 'bone'
} as const;
export type DeskAdminCoverCoverTreatmentEnum = typeof DeskAdminCoverCoverTreatmentEnum[keyof typeof DeskAdminCoverCoverTreatmentEnum];

/**
 * @export
 */
export const DeskAdminCoverRerunCadenceEnum = {
    Off: 'off',
    Quarterly: 'quarterly',
    OnNewFiling: 'on_new_filing',
    OnNewDeal: 'on_new_deal'
} as const;
export type DeskAdminCoverRerunCadenceEnum = typeof DeskAdminCoverRerunCadenceEnum[keyof typeof DeskAdminCoverRerunCadenceEnum];


/**
 * Check if a given object implements the DeskAdminCover interface.
 */
export function instanceOfDeskAdminCover(value: object): value is DeskAdminCover {
    return true;
}

export function DeskAdminCoverFromJSON(json: any): DeskAdminCover {
    return DeskAdminCoverFromJSONTyped(json, false);
}

export function DeskAdminCoverFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeskAdminCover {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'category': json['category'] == null ? undefined : json['category'],
        'reportType': json['report_type'] == null ? undefined : json['report_type'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'headlineStats': json['headline_stats'] == null ? undefined : ((json['headline_stats'] as Array<any>).map(DeskHeadlineStatFromJSON)),
        'coverTreatment': json['cover_treatment'] == null ? undefined : json['cover_treatment'],
        'coverKicker': json['cover_kicker'] == null ? undefined : json['cover_kicker'],
        'coverNumeral': json['cover_numeral'] == null ? undefined : json['cover_numeral'],
        'pageCount': json['page_count'] == null ? undefined : json['page_count'],
        'pushExample': json['push_example'] == null ? undefined : json['push_example'],
        'rerunCadence': json['rerun_cadence'] == null ? undefined : json['rerun_cadence'],
    };
}

export function DeskAdminCoverToJSON(json: any): DeskAdminCover {
    return DeskAdminCoverToJSONTyped(json, false);
}

export function DeskAdminCoverToJSONTyped(value?: DeskAdminCover | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'category': value['category'],
        'report_type': value['reportType'],
        'summary': value['summary'],
        'headline_stats': value['headlineStats'] == null ? undefined : ((value['headlineStats'] as Array<any>).map(DeskHeadlineStatToJSON)),
        'cover_treatment': value['coverTreatment'],
        'cover_kicker': value['coverKicker'],
        'cover_numeral': value['coverNumeral'],
        'page_count': value['pageCount'],
        'push_example': value['pushExample'],
        'rerun_cadence': value['rerunCadence'],
    };
}

