/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.43.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { Division } from './Division';
import {
    DivisionFromJSON,
    DivisionFromJSONTyped,
    DivisionToJSON,
    DivisionToJSONTyped,
} from './Division';

/**
 * 
 * @export
 * @interface DivisionCollection
 */
export interface DivisionCollection {
    /**
     * 
     * @type {Array<Division>}
     * @memberof DivisionCollection
     */
    data?: Array<Division>;
    /**
     * 
     * @type {Meta}
     * @memberof DivisionCollection
     */
    meta?: Meta;
}

/**
 * Check if a given object implements the DivisionCollection interface.
 */
export function instanceOfDivisionCollection(value: object): value is DivisionCollection {
    return true;
}

export function DivisionCollectionFromJSON(json: any): DivisionCollection {
    return DivisionCollectionFromJSONTyped(json, false);
}

export function DivisionCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DivisionCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DivisionFromJSON)),
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
    };
}

export function DivisionCollectionToJSON(json: any): DivisionCollection {
    return DivisionCollectionToJSONTyped(json, false);
}

export function DivisionCollectionToJSONTyped(value?: DivisionCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DivisionToJSON)),
        'meta': MetaToJSON(value['meta']),
    };
}

