/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.29417043294
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnrichGamePostSearchesRequest
 */
export interface EnrichGamePostSearchesRequest {
    /**
     * The loaded page's [school_id, sport_id] pairs. Malformed or non-positive pairs are ignored; duplicates are de-duped.
     * @type {Array<Array<number>>}
     * @memberof EnrichGamePostSearchesRequest
     */
    pairs: Array<Array<number>>;
}

/**
 * Check if a given object implements the EnrichGamePostSearchesRequest interface.
 */
export function instanceOfEnrichGamePostSearchesRequest(value: object): value is EnrichGamePostSearchesRequest {
    if (!('pairs' in value) || value['pairs'] === undefined) return false;
    return true;
}

export function EnrichGamePostSearchesRequestFromJSON(json: any): EnrichGamePostSearchesRequest {
    return EnrichGamePostSearchesRequestFromJSONTyped(json, false);
}

export function EnrichGamePostSearchesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrichGamePostSearchesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pairs': json['pairs'],
    };
}

export function EnrichGamePostSearchesRequestToJSON(json: any): EnrichGamePostSearchesRequest {
    return EnrichGamePostSearchesRequestToJSONTyped(json, false);
}

export function EnrichGamePostSearchesRequestToJSONTyped(value?: EnrichGamePostSearchesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pairs': value['pairs'],
    };
}

