/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.44.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A position type with optional group stub flag
 * @export
 * @interface FilterPositionType
 */
export interface FilterPositionType {
    /**
     * 
     * @type {number}
     * @memberof FilterPositionType
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof FilterPositionType
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof FilterPositionType
     */
    groupStub?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FilterPositionType
     */
    category?: string | null;
}

/**
 * Check if a given object implements the FilterPositionType interface.
 */
export function instanceOfFilterPositionType(value: object): value is FilterPositionType {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FilterPositionTypeFromJSON(json: any): FilterPositionType {
    return FilterPositionTypeFromJSONTyped(json, false);
}

export function FilterPositionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterPositionType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'groupStub': json['group_stub'] == null ? undefined : json['group_stub'],
        'category': json['category'] == null ? undefined : json['category'],
    };
}

export function FilterPositionTypeToJSON(json: any): FilterPositionType {
    return FilterPositionTypeToJSONTyped(json, false);
}

export function FilterPositionTypeToJSONTyped(value?: FilterPositionType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'group_stub': value['groupStub'],
        'category': value['category'],
    };
}

