/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.44.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Filters
 */
export interface Filters {
    /**
     * Key-value pairs for filtering coaches
     * @type {object}
     * @memberof Filters
     */
    filters?: object;
}

/**
 * Check if a given object implements the Filters interface.
 */
export function instanceOfFilters(value: object): value is Filters {
    return true;
}

export function FiltersFromJSON(json: any): Filters {
    return FiltersFromJSONTyped(json, false);
}

export function FiltersFromJSONTyped(json: any, ignoreDiscriminator: boolean): Filters {
    if (json == null) {
        return json;
    }
    return {
        
        'filters': json['filters'] == null ? undefined : json['filters'],
    };
}

export function FiltersToJSON(json: any): Filters {
    return FiltersToJSONTyped(json, false);
}

export function FiltersToJSONTyped(value?: Filters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filters': value['filters'],
    };
}

