/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.54.0-dev.10366
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialSelectionMetric } from './FinancialSelectionMetric';
import {
    FinancialSelectionMetricFromJSON,
    FinancialSelectionMetricFromJSONTyped,
    FinancialSelectionMetricToJSON,
    FinancialSelectionMetricToJSONTyped,
} from './FinancialSelectionMetric';

/**
 * One source's resolved report for the requested school/grain/year (Financials::SourceSelection::Result) — never a row assembled from unrelated line items across two reports.
 * @export
 * @interface FinancialSelectionResult
 */
export interface FinancialSelectionResult {
    /**
     * 
     * @type {string}
     * @memberof FinancialSelectionResult
     */
    source: FinancialSelectionResultSourceEnum;
    /**
     * 
     * @type {number}
     * @memberof FinancialSelectionResult
     */
    year?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialSelectionResult
     */
    grain: FinancialSelectionResultGrainEnum;
    /**
     * False when no report exists for this source/year/grain, the report exists but has nothing actually reported (NCAA/FRS only), no sport-code crosswalk exists for this sport (EADA sport grain only), a requested metric filter matched nothing this source's vocabulary emits at all, or (single-source mode only) the viewer lacks the ability for this source on this school.
     * @type {boolean}
     * @memberof FinancialSelectionResult
     */
    available: boolean;
    /**
     * sport_not_mapped_to_eada marks a WinAD sport with no EADA crosswalk row at all (a mapping gap, not a missing filing); source_not_permitted_for_viewer also covers best_available/both requests where the viewer holds neither source ability for this school.
     * @type {string}
     * @memberof FinancialSelectionResult
     */
    fallbackReason?: FinancialSelectionResultFallbackReasonEnum | null;
    /**
     * Most-conservative comparability_state across this result's metrics (not_comparable outranks comparison_only outranks mergeable; source_only is the fallback default).
     * @type {string}
     * @memberof FinancialSelectionResult
     */
    comparabilitySummary: FinancialSelectionResultComparabilitySummaryEnum;
    /**
     * 
     * @type {Array<FinancialSelectionMetric>}
     * @memberof FinancialSelectionResult
     */
    metrics: Array<FinancialSelectionMetric>;
}


/**
 * @export
 */
export const FinancialSelectionResultSourceEnum = {
    Eada: 'eada',
    NcaaFrs: 'ncaa_frs',
    None: 'none'
} as const;
export type FinancialSelectionResultSourceEnum = typeof FinancialSelectionResultSourceEnum[keyof typeof FinancialSelectionResultSourceEnum];

/**
 * @export
 */
export const FinancialSelectionResultGrainEnum = {
    Institution: 'institution',
    Sport: 'sport'
} as const;
export type FinancialSelectionResultGrainEnum = typeof FinancialSelectionResultGrainEnum[keyof typeof FinancialSelectionResultGrainEnum];

/**
 * @export
 */
export const FinancialSelectionResultFallbackReasonEnum = {
    NcaaFrsUnavailableUsedEada: 'ncaa_frs_unavailable_used_eada',
    NoReportAvailableForAnySource: 'no_report_available_for_any_source',
    SourceNotPermittedForViewer: 'source_not_permitted_for_viewer',
    SportNotMappedToEada: 'sport_not_mapped_to_eada'
} as const;
export type FinancialSelectionResultFallbackReasonEnum = typeof FinancialSelectionResultFallbackReasonEnum[keyof typeof FinancialSelectionResultFallbackReasonEnum];

/**
 * @export
 */
export const FinancialSelectionResultComparabilitySummaryEnum = {
    NotComparable: 'not_comparable',
    ComparisonOnly: 'comparison_only',
    Mergeable: 'mergeable',
    SourceOnly: 'source_only'
} as const;
export type FinancialSelectionResultComparabilitySummaryEnum = typeof FinancialSelectionResultComparabilitySummaryEnum[keyof typeof FinancialSelectionResultComparabilitySummaryEnum];


/**
 * Check if a given object implements the FinancialSelectionResult interface.
 */
export function instanceOfFinancialSelectionResult(value: object): value is FinancialSelectionResult {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('grain' in value) || value['grain'] === undefined) return false;
    if (!('available' in value) || value['available'] === undefined) return false;
    if (!('comparabilitySummary' in value) || value['comparabilitySummary'] === undefined) return false;
    if (!('metrics' in value) || value['metrics'] === undefined) return false;
    return true;
}

export function FinancialSelectionResultFromJSON(json: any): FinancialSelectionResult {
    return FinancialSelectionResultFromJSONTyped(json, false);
}

export function FinancialSelectionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialSelectionResult {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'],
        'year': json['year'] == null ? undefined : json['year'],
        'grain': json['grain'],
        'available': json['available'],
        'fallbackReason': json['fallback_reason'] == null ? undefined : json['fallback_reason'],
        'comparabilitySummary': json['comparability_summary'],
        'metrics': ((json['metrics'] as Array<any>).map(FinancialSelectionMetricFromJSON)),
    };
}

export function FinancialSelectionResultToJSON(json: any): FinancialSelectionResult {
    return FinancialSelectionResultToJSONTyped(json, false);
}

export function FinancialSelectionResultToJSONTyped(value?: FinancialSelectionResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'year': value['year'],
        'grain': value['grain'],
        'available': value['available'],
        'fallback_reason': value['fallbackReason'],
        'comparability_summary': value['comparabilitySummary'],
        'metrics': ((value['metrics'] as Array<any>).map(FinancialSelectionMetricToJSON)),
    };
}

