/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.54.2-dev.10366
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * WINAD-10369's shared self-describing metric shape (Financials::Metric) — the one row shape returned regardless of whether it came from EADA or NCAA/FRS, each carrying its own source and year so a consumer that flattens results across sources never loses provenance.
 * @export
 * @interface FinancialSelectionMetric
 */
export interface FinancialSelectionMetric {
    /**
     * 
     * @type {string}
     * @memberof FinancialSelectionMetric
     */
    source: FinancialSelectionMetricSourceEnum;
    /**
     * 
     * @type {number}
     * @memberof FinancialSelectionMetric
     */
    year: number;
    /**
     * 
     * @type {string}
     * @memberof FinancialSelectionMetric
     */
    grain: string;
    /**
     * The shared cross-source id when one exists (currently total_revenue, total_expenses). Never an invitation to sum or average two sources' values for the same id — see comparability_state.
     * @type {string}
     * @memberof FinancialSelectionMetric
     */
    canonicalMetricId?: string | null;
    /**
     * The source's own metric id — identical to canonical_metric_id for NCAA/FRS lines, the EADA-native field name (e.g. exp_men) for EADA metrics translated onto the shared vocabulary at sport grain.
     * @type {string}
     * @memberof FinancialSelectionMetric
     */
    nativeMetricId: string;
    /**
     * 
     * @type {string}
     * @memberof FinancialSelectionMetric
     */
    label?: string | null;
    /**
     * Raw typed value (whole dollars for usd fields — not cents)
     * @type {number}
     * @memberof FinancialSelectionMetric
     */
    value?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialSelectionMetric
     */
    unit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialSelectionMetric
     */
    comparabilityState?: FinancialSelectionMetricComparabilityStateEnum | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialSelectionMetric
     */
    counterpartNote?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialSelectionMetric
     */
    gender?: string | null;
    /**
     * "native" for NCAA/FRS lines; the EADA report/sport match status for EADA lines.
     * @type {string}
     * @memberof FinancialSelectionMetric
     */
    mappingStatus: string;
    /**
     * 
     * @type {string}
     * @memberof FinancialSelectionMetric
     */
    sportCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialSelectionMetric
     */
    sportName?: string | null;
}


/**
 * @export
 */
export const FinancialSelectionMetricSourceEnum = {
    Eada: 'eada',
    NcaaFrs: 'ncaa_frs'
} as const;
export type FinancialSelectionMetricSourceEnum = typeof FinancialSelectionMetricSourceEnum[keyof typeof FinancialSelectionMetricSourceEnum];

/**
 * @export
 */
export const FinancialSelectionMetricComparabilityStateEnum = {
    Mergeable: 'mergeable',
    ComparisonOnly: 'comparison_only',
    NotComparable: 'not_comparable',
    SourceOnly: 'source_only'
} as const;
export type FinancialSelectionMetricComparabilityStateEnum = typeof FinancialSelectionMetricComparabilityStateEnum[keyof typeof FinancialSelectionMetricComparabilityStateEnum];


/**
 * Check if a given object implements the FinancialSelectionMetric interface.
 */
export function instanceOfFinancialSelectionMetric(value: object): value is FinancialSelectionMetric {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('grain' in value) || value['grain'] === undefined) return false;
    if (!('nativeMetricId' in value) || value['nativeMetricId'] === undefined) return false;
    if (!('mappingStatus' in value) || value['mappingStatus'] === undefined) return false;
    return true;
}

export function FinancialSelectionMetricFromJSON(json: any): FinancialSelectionMetric {
    return FinancialSelectionMetricFromJSONTyped(json, false);
}

export function FinancialSelectionMetricFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialSelectionMetric {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'],
        'year': json['year'],
        'grain': json['grain'],
        'canonicalMetricId': json['canonical_metric_id'] == null ? undefined : json['canonical_metric_id'],
        'nativeMetricId': json['native_metric_id'],
        'label': json['label'] == null ? undefined : json['label'],
        'value': json['value'] == null ? undefined : json['value'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'comparabilityState': json['comparability_state'] == null ? undefined : json['comparability_state'],
        'counterpartNote': json['counterpart_note'] == null ? undefined : json['counterpart_note'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'mappingStatus': json['mapping_status'],
        'sportCode': json['sport_code'] == null ? undefined : json['sport_code'],
        'sportName': json['sport_name'] == null ? undefined : json['sport_name'],
    };
}

export function FinancialSelectionMetricToJSON(json: any): FinancialSelectionMetric {
    return FinancialSelectionMetricToJSONTyped(json, false);
}

export function FinancialSelectionMetricToJSONTyped(value?: FinancialSelectionMetric | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'year': value['year'],
        'grain': value['grain'],
        'canonical_metric_id': value['canonicalMetricId'],
        'native_metric_id': value['nativeMetricId'],
        'label': value['label'],
        'value': value['value'],
        'unit': value['unit'],
        'comparability_state': value['comparabilityState'],
        'counterpart_note': value['counterpartNote'],
        'gender': value['gender'],
        'mapping_status': value['mappingStatus'],
        'sport_code': value['sportCode'],
        'sport_name': value['sportName'],
    };
}

