/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.61
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FoiaInboxApplyInputExpectedRequest
 */
export interface FoiaInboxApplyInputExpectedRequest {
    /**
     * 
     * @type {string}
     * @memberof FoiaInboxApplyInputExpectedRequest
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof FoiaInboxApplyInputExpectedRequest
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof FoiaInboxApplyInputExpectedRequest
     */
    updatedBySchool: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FoiaInboxApplyInputExpectedRequest
     */
    updatedByWi: Date | null;
    /**
     * 
     * @type {string}
     * @memberof FoiaInboxApplyInputExpectedRequest
     */
    foiaNotesSha256: string;
}

/**
 * Check if a given object implements the FoiaInboxApplyInputExpectedRequest interface.
 */
export function instanceOfFoiaInboxApplyInputExpectedRequest(value: object): value is FoiaInboxApplyInputExpectedRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('updatedBySchool' in value) || value['updatedBySchool'] === undefined) return false;
    if (!('updatedByWi' in value) || value['updatedByWi'] === undefined) return false;
    if (!('foiaNotesSha256' in value) || value['foiaNotesSha256'] === undefined) return false;
    return true;
}

export function FoiaInboxApplyInputExpectedRequestFromJSON(json: any): FoiaInboxApplyInputExpectedRequest {
    return FoiaInboxApplyInputExpectedRequestFromJSONTyped(json, false);
}

export function FoiaInboxApplyInputExpectedRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoiaInboxApplyInputExpectedRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'updatedAt': (new Date(json['updated_at'])),
        'updatedBySchool': (json['updated_by_school'] == null ? null : new Date(json['updated_by_school'])),
        'updatedByWi': (json['updated_by_wi'] == null ? null : new Date(json['updated_by_wi'])),
        'foiaNotesSha256': json['foia_notes_sha256'],
    };
}

export function FoiaInboxApplyInputExpectedRequestToJSON(json: any): FoiaInboxApplyInputExpectedRequest {
    return FoiaInboxApplyInputExpectedRequestToJSONTyped(json, false);
}

export function FoiaInboxApplyInputExpectedRequestToJSONTyped(value?: FoiaInboxApplyInputExpectedRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'updated_at': value['updatedAt'].toISOString(),
        'updated_by_school': value['updatedBySchool'] == null ? value['updatedBySchool'] : value['updatedBySchool'].toISOString().substring(0,10),
        'updated_by_wi': value['updatedByWi'] == null ? value['updatedByWi'] : value['updatedByWi'].toISOString().substring(0,10),
        'foia_notes_sha256': value['foiaNotesSha256'],
    };
}

