/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31606351135
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FoiaInboxEffects } from './FoiaInboxEffects';
import {
    FoiaInboxEffectsFromJSON,
    FoiaInboxEffectsFromJSONTyped,
    FoiaInboxEffectsToJSON,
    FoiaInboxEffectsToJSONTyped,
} from './FoiaInboxEffects';
import type { FoiaInboxApplyInputExpectedRequest } from './FoiaInboxApplyInputExpectedRequest';
import {
    FoiaInboxApplyInputExpectedRequestFromJSON,
    FoiaInboxApplyInputExpectedRequestFromJSONTyped,
    FoiaInboxApplyInputExpectedRequestToJSON,
    FoiaInboxApplyInputExpectedRequestToJSONTyped,
} from './FoiaInboxApplyInputExpectedRequest';

/**
 * 
 * @export
 * @interface FoiaInboxApplyInput
 */
export interface FoiaInboxApplyInput {
    /**
     * 
     * @type {string}
     * @memberof FoiaInboxApplyInput
     */
    mailbox: FoiaInboxApplyInputMailboxEnum;
    /**
     * 
     * @type {string}
     * @memberof FoiaInboxApplyInput
     */
    gmailMessageId: string;
    /**
     * 
     * @type {string}
     * @memberof FoiaInboxApplyInput
     */
    gmailThreadId: string;
    /**
     * 
     * @type {string}
     * @memberof FoiaInboxApplyInput
     */
    runId: string;
    /**
     * 
     * @type {number}
     * @memberof FoiaInboxApplyInput
     */
    foiaRequestId: number;
    /**
     * 
     * @type {number}
     * @memberof FoiaInboxApplyInput
     */
    schoolId: number;
    /**
     * 
     * @type {string}
     * @memberof FoiaInboxApplyInput
     */
    decisionSha256: string;
    /**
     * 
     * @type {FoiaInboxApplyInputExpectedRequest}
     * @memberof FoiaInboxApplyInput
     */
    expectedRequest: FoiaInboxApplyInputExpectedRequest;
    /**
     * 
     * @type {FoiaInboxEffects}
     * @memberof FoiaInboxApplyInput
     */
    effects: FoiaInboxEffects;
}


/**
 * @export
 */
export const FoiaInboxApplyInputMailboxEnum = {
    OpenrecordswinthropintelligenceCom: 'openrecords@winthropintelligence.com'
} as const;
export type FoiaInboxApplyInputMailboxEnum = typeof FoiaInboxApplyInputMailboxEnum[keyof typeof FoiaInboxApplyInputMailboxEnum];


/**
 * Check if a given object implements the FoiaInboxApplyInput interface.
 */
export function instanceOfFoiaInboxApplyInput(value: object): value is FoiaInboxApplyInput {
    if (!('mailbox' in value) || value['mailbox'] === undefined) return false;
    if (!('gmailMessageId' in value) || value['gmailMessageId'] === undefined) return false;
    if (!('gmailThreadId' in value) || value['gmailThreadId'] === undefined) return false;
    if (!('runId' in value) || value['runId'] === undefined) return false;
    if (!('foiaRequestId' in value) || value['foiaRequestId'] === undefined) return false;
    if (!('schoolId' in value) || value['schoolId'] === undefined) return false;
    if (!('decisionSha256' in value) || value['decisionSha256'] === undefined) return false;
    if (!('expectedRequest' in value) || value['expectedRequest'] === undefined) return false;
    if (!('effects' in value) || value['effects'] === undefined) return false;
    return true;
}

export function FoiaInboxApplyInputFromJSON(json: any): FoiaInboxApplyInput {
    return FoiaInboxApplyInputFromJSONTyped(json, false);
}

export function FoiaInboxApplyInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoiaInboxApplyInput {
    if (json == null) {
        return json;
    }
    return {
        
        'mailbox': json['mailbox'],
        'gmailMessageId': json['gmail_message_id'],
        'gmailThreadId': json['gmail_thread_id'],
        'runId': json['run_id'],
        'foiaRequestId': json['foia_request_id'],
        'schoolId': json['school_id'],
        'decisionSha256': json['decision_sha256'],
        'expectedRequest': FoiaInboxApplyInputExpectedRequestFromJSON(json['expected_request']),
        'effects': FoiaInboxEffectsFromJSON(json['effects']),
    };
}

export function FoiaInboxApplyInputToJSON(json: any): FoiaInboxApplyInput {
    return FoiaInboxApplyInputToJSONTyped(json, false);
}

export function FoiaInboxApplyInputToJSONTyped(value?: FoiaInboxApplyInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mailbox': value['mailbox'],
        'gmail_message_id': value['gmailMessageId'],
        'gmail_thread_id': value['gmailThreadId'],
        'run_id': value['runId'],
        'foia_request_id': value['foiaRequestId'],
        'school_id': value['schoolId'],
        'decision_sha256': value['decisionSha256'],
        'expected_request': FoiaInboxApplyInputExpectedRequestToJSON(value['expectedRequest']),
        'effects': FoiaInboxEffectsToJSON(value['effects']),
    };
}

