/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.30098392418
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FrsResolvedSchool
 */
export interface FrsResolvedSchool {
    /**
     * 
     * @type {number}
     * @memberof FrsResolvedSchool
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof FrsResolvedSchool
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FrsResolvedSchool
     */
    status: FrsResolvedSchoolStatusEnum;
    /**
     * 
     * @type {boolean}
     * @memberof FrsResolvedSchool
     */
    hasFiling: boolean;
}


/**
 * @export
 */
export const FrsResolvedSchoolStatusEnum = {
    Included: 'included',
    PrivateNotInFrs: 'private_not_in_frs',
    LicenseExcluded: 'license_excluded'
} as const;
export type FrsResolvedSchoolStatusEnum = typeof FrsResolvedSchoolStatusEnum[keyof typeof FrsResolvedSchoolStatusEnum];


/**
 * Check if a given object implements the FrsResolvedSchool interface.
 */
export function instanceOfFrsResolvedSchool(value: object): value is FrsResolvedSchool {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('hasFiling' in value) || value['hasFiling'] === undefined) return false;
    return true;
}

export function FrsResolvedSchoolFromJSON(json: any): FrsResolvedSchool {
    return FrsResolvedSchoolFromJSONTyped(json, false);
}

export function FrsResolvedSchoolFromJSONTyped(json: any, ignoreDiscriminator: boolean): FrsResolvedSchool {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'status': json['status'],
        'hasFiling': json['has_filing'],
    };
}

export function FrsResolvedSchoolToJSON(json: any): FrsResolvedSchool {
    return FrsResolvedSchoolToJSONTyped(json, false);
}

export function FrsResolvedSchoolToJSONTyped(value?: FrsResolvedSchool | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'status': value['status'],
        'has_filing': value['hasFiling'],
    };
}

