/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.26
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Resolved buyer-side conference/division/subdivision IDs that were applied.
 * @export
 * @interface GadCohortSummaryBuyerFilters
 */
export interface GadCohortSummaryBuyerFilters {
    /**
     * 
     * @type {number}
     * @memberof GadCohortSummaryBuyerFilters
     */
    conferenceId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GadCohortSummaryBuyerFilters
     */
    divisionId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GadCohortSummaryBuyerFilters
     */
    subdivisionId?: number | null;
}

/**
 * Check if a given object implements the GadCohortSummaryBuyerFilters interface.
 */
export function instanceOfGadCohortSummaryBuyerFilters(value: object): value is GadCohortSummaryBuyerFilters {
    return true;
}

export function GadCohortSummaryBuyerFiltersFromJSON(json: any): GadCohortSummaryBuyerFilters {
    return GadCohortSummaryBuyerFiltersFromJSONTyped(json, false);
}

export function GadCohortSummaryBuyerFiltersFromJSONTyped(json: any, ignoreDiscriminator: boolean): GadCohortSummaryBuyerFilters {
    if (json == null) {
        return json;
    }
    return {
        
        'conferenceId': json['conference_id'] == null ? undefined : json['conference_id'],
        'divisionId': json['division_id'] == null ? undefined : json['division_id'],
        'subdivisionId': json['subdivision_id'] == null ? undefined : json['subdivision_id'],
    };
}

export function GadCohortSummaryBuyerFiltersToJSON(json: any): GadCohortSummaryBuyerFilters {
    return GadCohortSummaryBuyerFiltersToJSONTyped(json, false);
}

export function GadCohortSummaryBuyerFiltersToJSONTyped(value?: GadCohortSummaryBuyerFilters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conference_id': value['conferenceId'],
        'division_id': value['divisionId'],
        'subdivision_id': value['subdivisionId'],
    };
}

