/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.43.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameContract
 */
export interface GameContract {
    /**
     * 
     * @type {number}
     * @memberof GameContract
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof GameContract
     */
    homeSchoolId?: number;
    /**
     * 
     * @type {number}
     * @memberof GameContract
     */
    awaySchoolId?: number;
    /**
     * 
     * @type {number}
     * @memberof GameContract
     */
    sportId?: number;
    /**
     * 
     * @type {Date}
     * @memberof GameContract
     */
    gameDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof GameContract
     */
    gameDateTbd?: string;
    /**
     * 
     * @type {number}
     * @memberof GameContract
     */
    compCents?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GameContract
     */
    variable?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GameContract
     */
    cancelFeeCents?: number;
    /**
     * 
     * @type {Date}
     * @memberof GameContract
     */
    signedOn?: Date;
    /**
     * 
     * @type {number}
     * @memberof GameContract
     */
    rawContractId?: number;
    /**
     * 
     * @type {Date}
     * @memberof GameContract
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GameContract
     */
    updatedAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof GameContract
     */
    compTbd?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GameContract
     */
    tbd?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GameContract
     */
    seasonYearTbd?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GameContract
     */
    cancelled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GameContract
     */
    seasonYear?: number;
    /**
     * 
     * @type {string}
     * @memberof GameContract
     */
    gameType?: string;
    /**
     * 
     * @type {string}
     * @memberof GameContract
     */
    offSiteLocation?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GameContract
     */
    verified?: boolean;
}

/**
 * Check if a given object implements the GameContract interface.
 */
export function instanceOfGameContract(value: object): value is GameContract {
    return true;
}

export function GameContractFromJSON(json: any): GameContract {
    return GameContractFromJSONTyped(json, false);
}

export function GameContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameContract {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'homeSchoolId': json['home_school_id'] == null ? undefined : json['home_school_id'],
        'awaySchoolId': json['away_school_id'] == null ? undefined : json['away_school_id'],
        'sportId': json['sport_id'] == null ? undefined : json['sport_id'],
        'gameDate': json['game_date'] == null ? undefined : (new Date(json['game_date'])),
        'gameDateTbd': json['game_date_tbd'] == null ? undefined : json['game_date_tbd'],
        'compCents': json['comp_cents'] == null ? undefined : json['comp_cents'],
        'variable': json['variable'] == null ? undefined : json['variable'],
        'cancelFeeCents': json['cancel_fee_cents'] == null ? undefined : json['cancel_fee_cents'],
        'signedOn': json['signed_on'] == null ? undefined : (new Date(json['signed_on'])),
        'rawContractId': json['raw_contract_id'] == null ? undefined : json['raw_contract_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'compTbd': json['comp_tbd'] == null ? undefined : json['comp_tbd'],
        'tbd': json['tbd'] == null ? undefined : json['tbd'],
        'seasonYearTbd': json['season_year_tbd'] == null ? undefined : json['season_year_tbd'],
        'cancelled': json['cancelled'] == null ? undefined : json['cancelled'],
        'seasonYear': json['season_year'] == null ? undefined : json['season_year'],
        'gameType': json['game_type'] == null ? undefined : json['game_type'],
        'offSiteLocation': json['off_site_location'] == null ? undefined : json['off_site_location'],
        'verified': json['verified'] == null ? undefined : json['verified'],
    };
}

export function GameContractToJSON(json: any): GameContract {
    return GameContractToJSONTyped(json, false);
}

export function GameContractToJSONTyped(value?: GameContract | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'home_school_id': value['homeSchoolId'],
        'away_school_id': value['awaySchoolId'],
        'sport_id': value['sportId'],
        'game_date': value['gameDate'] == null ? value['gameDate'] : value['gameDate'].toISOString(),
        'game_date_tbd': value['gameDateTbd'],
        'comp_cents': value['compCents'],
        'variable': value['variable'],
        'cancel_fee_cents': value['cancelFeeCents'],
        'signed_on': value['signedOn'] == null ? value['signedOn'] : value['signedOn'].toISOString(),
        'raw_contract_id': value['rawContractId'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'comp_tbd': value['compTbd'],
        'tbd': value['tbd'],
        'season_year_tbd': value['seasonYearTbd'],
        'cancelled': value['cancelled'],
        'season_year': value['seasonYear'],
        'game_type': value['gameType'],
        'off_site_location': value['offSiteLocation'],
        'verified': value['verified'],
    };
}

