/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.27190910726
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GamePostPendingWindow } from './GamePostPendingWindow';
import {
    GamePostPendingWindowFromJSON,
    GamePostPendingWindowFromJSONTyped,
    GamePostPendingWindowToJSON,
    GamePostPendingWindowToJSONTyped,
} from './GamePostPendingWindow';
import type { GamePostScheduleGame } from './GamePostScheduleGame';
import {
    GamePostScheduleGameFromJSON,
    GamePostScheduleGameFromJSONTyped,
    GamePostScheduleGameToJSON,
    GamePostScheduleGameToJSONTyped,
} from './GamePostScheduleGame';

/**
 * 
 * @export
 * @interface GamePostScheduleSummary
 */
export interface GamePostScheduleSummary {
    /**
     * 
     * @type {number}
     * @memberof GamePostScheduleSummary
     */
    wantedDatesCount?: number;
    /**
     * 
     * @type {Array<GamePostScheduleGame>}
     * @memberof GamePostScheduleSummary
     */
    scheduledGames?: Array<GamePostScheduleGame>;
    /**
     * 
     * @type {Array<GamePostPendingWindow>}
     * @memberof GamePostScheduleSummary
     */
    pendingWindows?: Array<GamePostPendingWindow>;
}

/**
 * Check if a given object implements the GamePostScheduleSummary interface.
 */
export function instanceOfGamePostScheduleSummary(value: object): value is GamePostScheduleSummary {
    return true;
}

export function GamePostScheduleSummaryFromJSON(json: any): GamePostScheduleSummary {
    return GamePostScheduleSummaryFromJSONTyped(json, false);
}

export function GamePostScheduleSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamePostScheduleSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'wantedDatesCount': json['wanted_dates_count'] == null ? undefined : json['wanted_dates_count'],
        'scheduledGames': json['scheduled_games'] == null ? undefined : ((json['scheduled_games'] as Array<any>).map(GamePostScheduleGameFromJSON)),
        'pendingWindows': json['pending_windows'] == null ? undefined : ((json['pending_windows'] as Array<any>).map(GamePostPendingWindowFromJSON)),
    };
}

export function GamePostScheduleSummaryToJSON(json: any): GamePostScheduleSummary {
    return GamePostScheduleSummaryToJSONTyped(json, false);
}

export function GamePostScheduleSummaryToJSONTyped(value?: GamePostScheduleSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wanted_dates_count': value['wantedDatesCount'],
        'scheduled_games': value['scheduledGames'] == null ? undefined : ((value['scheduledGames'] as Array<any>).map(GamePostScheduleGameToJSON)),
        'pending_windows': value['pendingWindows'] == null ? undefined : ((value['pendingWindows'] as Array<any>).map(GamePostPendingWindowToJSON)),
    };
}

