/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.26
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GamePostGapCountCollectionDataInner
 */
export interface GamePostGapCountCollectionDataInner {
    /**
     * 
     * @type {Date}
     * @memberof GamePostGapCountCollectionDataInner
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GamePostGapCountCollectionDataInner
     */
    endDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof GamePostGapCountCollectionDataInner
     */
    count?: number;
}

/**
 * Check if a given object implements the GamePostGapCountCollectionDataInner interface.
 */
export function instanceOfGamePostGapCountCollectionDataInner(value: object): value is GamePostGapCountCollectionDataInner {
    return true;
}

export function GamePostGapCountCollectionDataInnerFromJSON(json: any): GamePostGapCountCollectionDataInner {
    return GamePostGapCountCollectionDataInnerFromJSONTyped(json, false);
}

export function GamePostGapCountCollectionDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamePostGapCountCollectionDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function GamePostGapCountCollectionDataInnerToJSON(json: any): GamePostGapCountCollectionDataInner {
    return GamePostGapCountCollectionDataInnerToJSONTyped(json, false);
}

export function GamePostGapCountCollectionDataInnerToJSONTyped(value?: GamePostGapCountCollectionDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start_date': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString().substring(0,10),
        'end_date': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'count': value['count'],
    };
}

