/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.42
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Cell/mobile phone. value/dial are null when not on file.
 * @export
 * @interface GamePostSearchResultContactCell
 */
export interface GamePostSearchResultContactCell {
    /**
     * 
     * @type {string}
     * @memberof GamePostSearchResultContactCell
     */
    value: string | null;
    /**
     * 
     * @type {string}
     * @memberof GamePostSearchResultContactCell
     */
    dial?: string | null;
    /**
     * Whether a cell number is on file.
     * @type {boolean}
     * @memberof GamePostSearchResultContactCell
     */
    present: boolean;
}

/**
 * Check if a given object implements the GamePostSearchResultContactCell interface.
 */
export function instanceOfGamePostSearchResultContactCell(value: object): value is GamePostSearchResultContactCell {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('present' in value) || value['present'] === undefined) return false;
    return true;
}

export function GamePostSearchResultContactCellFromJSON(json: any): GamePostSearchResultContactCell {
    return GamePostSearchResultContactCellFromJSONTyped(json, false);
}

export function GamePostSearchResultContactCellFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamePostSearchResultContactCell {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'dial': json['dial'] == null ? undefined : json['dial'],
        'present': json['present'],
    };
}

export function GamePostSearchResultContactCellToJSON(json: any): GamePostSearchResultContactCell {
    return GamePostSearchResultContactCellToJSONTyped(json, false);
}

export function GamePostSearchResultContactCellToJSONTyped(value?: GamePostSearchResultContactCell | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'dial': value['dial'],
        'present': value['present'],
    };
}

