/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameDetailAllOfGameContract } from './GameDetailAllOfGameContract';
import {
    GameDetailAllOfGameContractFromJSON,
    GameDetailAllOfGameContractFromJSONTyped,
    GameDetailAllOfGameContractToJSON,
    GameDetailAllOfGameContractToJSONTyped,
} from './GameDetailAllOfGameContract';

/**
 * 
 * @export
 * @interface GameDetail
 */
export interface GameDetail {
    /**
     * 
     * @type {number}
     * @memberof GameDetail
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof GameDetail
     */
    homeSchoolId?: number;
    /**
     * 
     * @type {number}
     * @memberof GameDetail
     */
    awaySchoolId?: number;
    /**
     * 
     * @type {number}
     * @memberof GameDetail
     */
    sportId: number;
    /**
     * 
     * @type {Date}
     * @memberof GameDetail
     */
    gameDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GameDetail
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GameDetail
     */
    updatedAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof GameDetail
     */
    neutral?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GameDetail
     */
    city?: string;
    /**
     * 
     * @type {number}
     * @memberof GameDetail
     */
    gameContractId?: number;
    /**
     * 
     * @type {number}
     * @memberof GameDetail
     */
    stateId?: number;
    /**
     * 
     * @type {string}
     * @memberof GameDetail
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GameDetail
     */
    inConference?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GameDetail
     */
    seasonYearTbd?: number;
    /**
     * 
     * @type {number}
     * @memberof GameDetail
     */
    homeSchoolScore?: number;
    /**
     * 
     * @type {number}
     * @memberof GameDetail
     */
    awaySchoolScore?: number;
    /**
     * 
     * @type {number}
     * @memberof GameDetail
     */
    overtime?: number;
    /**
     * 
     * @type {number}
     * @memberof GameDetail
     */
    seasonYear?: number;
    /**
     * 
     * @type {string}
     * @memberof GameDetail
     */
    homeSchoolName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameDetail
     */
    awaySchoolName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameDetail
     */
    stateName?: string | null;
    /**
     * Latest NET ranking for the home team, or null when not loaded yet
     * @type {number}
     * @memberof GameDetail
     */
    homeSchoolNetRanking?: number | null;
    /**
     * Latest NET ranking for the away team, or null when not loaded yet
     * @type {number}
     * @memberof GameDetail
     */
    awaySchoolNetRanking?: number | null;
    /**
     * Latest strength-of-schedule ranking for the home team, or null when not loaded yet
     * @type {number}
     * @memberof GameDetail
     */
    homeSchoolSosRanking?: number | null;
    /**
     * Latest strength-of-schedule ranking for the away team, or null when not loaded yet
     * @type {number}
     * @memberof GameDetail
     */
    awaySchoolSosRanking?: number | null;
    /**
     * Season year the displayed NET/SOS rankings are from, or null when neither team has a ranked season
     * @type {number}
     * @memberof GameDetail
     */
    rankingsSeasonYear?: number | null;
    /**
     * 
     * @type {GameDetailAllOfGameContract}
     * @memberof GameDetail
     */
    gameContract?: GameDetailAllOfGameContract | null;
}

/**
 * Check if a given object implements the GameDetail interface.
 */
export function instanceOfGameDetail(value: object): value is GameDetail {
    if (!('sportId' in value) || value['sportId'] === undefined) return false;
    return true;
}

export function GameDetailFromJSON(json: any): GameDetail {
    return GameDetailFromJSONTyped(json, false);
}

export function GameDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'homeSchoolId': json['home_school_id'] == null ? undefined : json['home_school_id'],
        'awaySchoolId': json['away_school_id'] == null ? undefined : json['away_school_id'],
        'sportId': json['sport_id'],
        'gameDate': json['game_date'] == null ? undefined : (new Date(json['game_date'])),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'neutral': json['neutral'] == null ? undefined : json['neutral'],
        'city': json['city'] == null ? undefined : json['city'],
        'gameContractId': json['game_contract_id'] == null ? undefined : json['game_contract_id'],
        'stateId': json['state_id'] == null ? undefined : json['state_id'],
        'description': json['description'] == null ? undefined : json['description'],
        'inConference': json['in_conference'] == null ? undefined : json['in_conference'],
        'seasonYearTbd': json['season_year_tbd'] == null ? undefined : json['season_year_tbd'],
        'homeSchoolScore': json['home_school_score'] == null ? undefined : json['home_school_score'],
        'awaySchoolScore': json['away_school_score'] == null ? undefined : json['away_school_score'],
        'overtime': json['overtime'] == null ? undefined : json['overtime'],
        'seasonYear': json['season_year'] == null ? undefined : json['season_year'],
        'homeSchoolName': json['home_school_name'] == null ? undefined : json['home_school_name'],
        'awaySchoolName': json['away_school_name'] == null ? undefined : json['away_school_name'],
        'stateName': json['state_name'] == null ? undefined : json['state_name'],
        'homeSchoolNetRanking': json['home_school_net_ranking'] == null ? undefined : json['home_school_net_ranking'],
        'awaySchoolNetRanking': json['away_school_net_ranking'] == null ? undefined : json['away_school_net_ranking'],
        'homeSchoolSosRanking': json['home_school_sos_ranking'] == null ? undefined : json['home_school_sos_ranking'],
        'awaySchoolSosRanking': json['away_school_sos_ranking'] == null ? undefined : json['away_school_sos_ranking'],
        'rankingsSeasonYear': json['rankings_season_year'] == null ? undefined : json['rankings_season_year'],
        'gameContract': json['game_contract'] == null ? undefined : GameDetailAllOfGameContractFromJSON(json['game_contract']),
    };
}

export function GameDetailToJSON(json: any): GameDetail {
    return GameDetailToJSONTyped(json, false);
}

export function GameDetailToJSONTyped(value?: GameDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'home_school_id': value['homeSchoolId'],
        'away_school_id': value['awaySchoolId'],
        'sport_id': value['sportId'],
        'game_date': value['gameDate'] == null ? value['gameDate'] : value['gameDate'].toISOString().substring(0,10),
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'neutral': value['neutral'],
        'city': value['city'],
        'game_contract_id': value['gameContractId'],
        'state_id': value['stateId'],
        'description': value['description'],
        'in_conference': value['inConference'],
        'season_year_tbd': value['seasonYearTbd'],
        'home_school_score': value['homeSchoolScore'],
        'away_school_score': value['awaySchoolScore'],
        'overtime': value['overtime'],
        'season_year': value['seasonYear'],
        'home_school_name': value['homeSchoolName'],
        'away_school_name': value['awaySchoolName'],
        'state_name': value['stateName'],
        'home_school_net_ranking': value['homeSchoolNetRanking'],
        'away_school_net_ranking': value['awaySchoolNetRanking'],
        'home_school_sos_ranking': value['homeSchoolSosRanking'],
        'away_school_sos_ranking': value['awaySchoolSosRanking'],
        'rankings_season_year': value['rankingsSeasonYear'],
        'game_contract': GameDetailAllOfGameContractToJSON(value['gameContract']),
    };
}

