/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.37-dev.10118
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GamePostSearchResultGamesInner
 */
export interface GamePostSearchResultGamesInner {
    /**
     * 
     * @type {number}
     * @memberof GamePostSearchResultGamesInner
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof GamePostSearchResultGamesInner
     */
    gameDate?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof GamePostSearchResultGamesInner
     */
    neutral?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof GamePostSearchResultGamesInner
     */
    inConference?: boolean | null;
    /**
     * Free-text game note (e.g. tournament name for neutral-site games)
     * @type {string}
     * @memberof GamePostSearchResultGamesInner
     */
    description?: string | null;
    /**
     * Whether the posting school is the home team
     * @type {boolean}
     * @memberof GamePostSearchResultGamesInner
     */
    isHome?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GamePostSearchResultGamesInner
     */
    opponentId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GamePostSearchResultGamesInner
     */
    opponentName?: string | null;
}

/**
 * Check if a given object implements the GamePostSearchResultGamesInner interface.
 */
export function instanceOfGamePostSearchResultGamesInner(value: object): value is GamePostSearchResultGamesInner {
    return true;
}

export function GamePostSearchResultGamesInnerFromJSON(json: any): GamePostSearchResultGamesInner {
    return GamePostSearchResultGamesInnerFromJSONTyped(json, false);
}

export function GamePostSearchResultGamesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamePostSearchResultGamesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'gameDate': json['game_date'] == null ? undefined : (new Date(json['game_date'])),
        'neutral': json['neutral'] == null ? undefined : json['neutral'],
        'inConference': json['in_conference'] == null ? undefined : json['in_conference'],
        'description': json['description'] == null ? undefined : json['description'],
        'isHome': json['is_home'] == null ? undefined : json['is_home'],
        'opponentId': json['opponent_id'] == null ? undefined : json['opponent_id'],
        'opponentName': json['opponent_name'] == null ? undefined : json['opponent_name'],
    };
}

export function GamePostSearchResultGamesInnerToJSON(json: any): GamePostSearchResultGamesInner {
    return GamePostSearchResultGamesInnerToJSONTyped(json, false);
}

export function GamePostSearchResultGamesInnerToJSONTyped(value?: GamePostSearchResultGamesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'game_date': value['gameDate'] == null ? value['gameDate'] : value['gameDate'].toISOString().substring(0,10),
        'neutral': value['neutral'],
        'in_conference': value['inConference'],
        'description': value['description'],
        'is_home': value['isHome'],
        'opponent_id': value['opponentId'],
        'opponent_name': value['opponentName'],
    };
}

