/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31395956111
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameContractApplyResponseSourceDocument } from './GameContractApplyResponseSourceDocument';
import {
    GameContractApplyResponseSourceDocumentFromJSON,
    GameContractApplyResponseSourceDocumentFromJSONTyped,
    GameContractApplyResponseSourceDocumentToJSON,
    GameContractApplyResponseSourceDocumentToJSONTyped,
} from './GameContractApplyResponseSourceDocument';
import type { GameContractApplyResponseActionsValue } from './GameContractApplyResponseActionsValue';
import {
    GameContractApplyResponseActionsValueFromJSON,
    GameContractApplyResponseActionsValueFromJSONTyped,
    GameContractApplyResponseActionsValueToJSON,
    GameContractApplyResponseActionsValueToJSONTyped,
} from './GameContractApplyResponseActionsValue';
import type { GameContractApplyResponsePdfProcessing } from './GameContractApplyResponsePdfProcessing';
import {
    GameContractApplyResponsePdfProcessingFromJSON,
    GameContractApplyResponsePdfProcessingFromJSONTyped,
    GameContractApplyResponsePdfProcessingToJSON,
    GameContractApplyResponsePdfProcessingToJSONTyped,
} from './GameContractApplyResponsePdfProcessing';
import type { GameContractApplyResponseActor } from './GameContractApplyResponseActor';
import {
    GameContractApplyResponseActorFromJSON,
    GameContractApplyResponseActorFromJSONTyped,
    GameContractApplyResponseActorToJSON,
    GameContractApplyResponseActorToJSONTyped,
} from './GameContractApplyResponseActor';

/**
 * 
 * @export
 * @interface GameContractApplyResponse
 */
export interface GameContractApplyResponse {
    /**
     * 
     * @type {string}
     * @memberof GameContractApplyResponse
     */
    schemaVersion: GameContractApplyResponseSchemaVersionEnum;
    /**
     * 
     * @type {string}
     * @memberof GameContractApplyResponse
     */
    status: GameContractApplyResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof GameContractApplyResponse
     */
    reviewSeriesId: string;
    /**
     * 
     * @type {string}
     * @memberof GameContractApplyResponse
     */
    reviewRevisionSha256: string;
    /**
     * 
     * @type {string}
     * @memberof GameContractApplyResponse
     */
    decisionSha256: string;
    /**
     * 
     * @type {string}
     * @memberof GameContractApplyResponse
     */
    requestSha256: string;
    /**
     * 
     * @type {GameContractApplyResponseActor}
     * @memberof GameContractApplyResponse
     */
    actor: GameContractApplyResponseActor;
    /**
     * 
     * @type {number}
     * @memberof GameContractApplyResponse
     */
    rawContractId: number;
    /**
     * Map of approved action_id to the created GameContract and its linked Game ids
     * @type {{ [key: string]: GameContractApplyResponseActionsValue; }}
     * @memberof GameContractApplyResponse
     */
    actions: { [key: string]: GameContractApplyResponseActionsValue; };
    /**
     * 
     * @type {GameContractApplyResponseSourceDocument}
     * @memberof GameContractApplyResponse
     */
    sourceDocument: GameContractApplyResponseSourceDocument;
    /**
     * 
     * @type {GameContractApplyResponsePdfProcessing}
     * @memberof GameContractApplyResponse
     */
    pdfProcessing: GameContractApplyResponsePdfProcessing;
}


/**
 * @export
 */
export const GameContractApplyResponseSchemaVersionEnum = {
    GameContractEntryReceiptV1: 'game-contract-entry-receipt/v1'
} as const;
export type GameContractApplyResponseSchemaVersionEnum = typeof GameContractApplyResponseSchemaVersionEnum[keyof typeof GameContractApplyResponseSchemaVersionEnum];

/**
 * @export
 */
export const GameContractApplyResponseStatusEnum = {
    Applied: 'applied',
    AlreadyApplied: 'already_applied'
} as const;
export type GameContractApplyResponseStatusEnum = typeof GameContractApplyResponseStatusEnum[keyof typeof GameContractApplyResponseStatusEnum];


/**
 * Check if a given object implements the GameContractApplyResponse interface.
 */
export function instanceOfGameContractApplyResponse(value: object): value is GameContractApplyResponse {
    if (!('schemaVersion' in value) || value['schemaVersion'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('reviewSeriesId' in value) || value['reviewSeriesId'] === undefined) return false;
    if (!('reviewRevisionSha256' in value) || value['reviewRevisionSha256'] === undefined) return false;
    if (!('decisionSha256' in value) || value['decisionSha256'] === undefined) return false;
    if (!('requestSha256' in value) || value['requestSha256'] === undefined) return false;
    if (!('actor' in value) || value['actor'] === undefined) return false;
    if (!('rawContractId' in value) || value['rawContractId'] === undefined) return false;
    if (!('actions' in value) || value['actions'] === undefined) return false;
    if (!('sourceDocument' in value) || value['sourceDocument'] === undefined) return false;
    if (!('pdfProcessing' in value) || value['pdfProcessing'] === undefined) return false;
    return true;
}

export function GameContractApplyResponseFromJSON(json: any): GameContractApplyResponse {
    return GameContractApplyResponseFromJSONTyped(json, false);
}

export function GameContractApplyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameContractApplyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'],
        'status': json['status'],
        'reviewSeriesId': json['review_series_id'],
        'reviewRevisionSha256': json['review_revision_sha256'],
        'decisionSha256': json['decision_sha256'],
        'requestSha256': json['request_sha256'],
        'actor': GameContractApplyResponseActorFromJSON(json['actor']),
        'rawContractId': json['raw_contract_id'],
        'actions': (mapValues(json['actions'], GameContractApplyResponseActionsValueFromJSON)),
        'sourceDocument': GameContractApplyResponseSourceDocumentFromJSON(json['source_document']),
        'pdfProcessing': GameContractApplyResponsePdfProcessingFromJSON(json['pdf_processing']),
    };
}

export function GameContractApplyResponseToJSON(json: any): GameContractApplyResponse {
    return GameContractApplyResponseToJSONTyped(json, false);
}

export function GameContractApplyResponseToJSONTyped(value?: GameContractApplyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema_version': value['schemaVersion'],
        'status': value['status'],
        'review_series_id': value['reviewSeriesId'],
        'review_revision_sha256': value['reviewRevisionSha256'],
        'decision_sha256': value['decisionSha256'],
        'request_sha256': value['requestSha256'],
        'actor': GameContractApplyResponseActorToJSON(value['actor']),
        'raw_contract_id': value['rawContractId'],
        'actions': (mapValues(value['actions'], GameContractApplyResponseActionsValueToJSON)),
        'source_document': GameContractApplyResponseSourceDocumentToJSON(value['sourceDocument']),
        'pdf_processing': GameContractApplyResponsePdfProcessingToJSON(value['pdfProcessing']),
    };
}

