/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.28-dev.10005
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GamePostSearchResultContactsInner
 */
export interface GamePostSearchResultContactsInner {
    /**
     * 
     * @type {string}
     * @memberof GamePostSearchResultContactsInner
     */
    coachName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GamePostSearchResultContactsInner
     */
    coachId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GamePostSearchResultContactsInner
     */
    position?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GamePostSearchResultContactsInner
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GamePostSearchResultContactsInner
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GamePostSearchResultContactsInner
     */
    phoneDial?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GamePostSearchResultContactsInner
     */
    schedulingPhone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GamePostSearchResultContactsInner
     */
    schedulingPhoneDial?: string | null;
}

/**
 * Check if a given object implements the GamePostSearchResultContactsInner interface.
 */
export function instanceOfGamePostSearchResultContactsInner(value: object): value is GamePostSearchResultContactsInner {
    return true;
}

export function GamePostSearchResultContactsInnerFromJSON(json: any): GamePostSearchResultContactsInner {
    return GamePostSearchResultContactsInnerFromJSONTyped(json, false);
}

export function GamePostSearchResultContactsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamePostSearchResultContactsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'coachName': json['coach_name'] == null ? undefined : json['coach_name'],
        'coachId': json['coach_id'] == null ? undefined : json['coach_id'],
        'position': json['position'] == null ? undefined : json['position'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'phoneDial': json['phone_dial'] == null ? undefined : json['phone_dial'],
        'schedulingPhone': json['scheduling_phone'] == null ? undefined : json['scheduling_phone'],
        'schedulingPhoneDial': json['scheduling_phone_dial'] == null ? undefined : json['scheduling_phone_dial'],
    };
}

export function GamePostSearchResultContactsInnerToJSON(json: any): GamePostSearchResultContactsInner {
    return GamePostSearchResultContactsInnerToJSONTyped(json, false);
}

export function GamePostSearchResultContactsInnerToJSONTyped(value?: GamePostSearchResultContactsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coach_name': value['coachName'],
        'coach_id': value['coachId'],
        'position': value['position'],
        'email': value['email'],
        'phone': value['phone'],
        'phone_dial': value['phoneDial'],
        'scheduling_phone': value['schedulingPhone'],
        'scheduling_phone_dial': value['schedulingPhoneDial'],
    };
}

