/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.36742451352
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetRawContractOcrText422Response
 */
export interface GetRawContractOcrText422Response {
    /**
     * 
     * @type {string}
     * @memberof GetRawContractOcrText422Response
     */
    error: string;
}

/**
 * Check if a given object implements the GetRawContractOcrText422Response interface.
 */
export function instanceOfGetRawContractOcrText422Response(value: object): value is GetRawContractOcrText422Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function GetRawContractOcrText422ResponseFromJSON(json: any): GetRawContractOcrText422Response {
    return GetRawContractOcrText422ResponseFromJSONTyped(json, false);
}

export function GetRawContractOcrText422ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRawContractOcrText422Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function GetRawContractOcrText422ResponseToJSON(json: any): GetRawContractOcrText422Response {
    return GetRawContractOcrText422ResponseToJSONTyped(json, false);
}

export function GetRawContractOcrText422ResponseToJSONTyped(value?: GetRawContractOcrText422Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

