/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.41.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSchoolAlternateNames404Response
 */
export interface GetSchoolAlternateNames404Response {
    /**
     * 
     * @type {string}
     * @memberof GetSchoolAlternateNames404Response
     */
    error?: string;
}

/**
 * Check if a given object implements the GetSchoolAlternateNames404Response interface.
 */
export function instanceOfGetSchoolAlternateNames404Response(value: object): value is GetSchoolAlternateNames404Response {
    return true;
}

export function GetSchoolAlternateNames404ResponseFromJSON(json: any): GetSchoolAlternateNames404Response {
    return GetSchoolAlternateNames404ResponseFromJSONTyped(json, false);
}

export function GetSchoolAlternateNames404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSchoolAlternateNames404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function GetSchoolAlternateNames404ResponseToJSON(json: any): GetSchoolAlternateNames404Response {
    return GetSchoolAlternateNames404ResponseToJSONTyped(json, false);
}

export function GetSchoolAlternateNames404ResponseToJSONTyped(value?: GetSchoolAlternateNames404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

