/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeZoneOption } from './TimeZoneOption';
import {
    TimeZoneOptionFromJSON,
    TimeZoneOptionFromJSONTyped,
    TimeZoneOptionToJSON,
    TimeZoneOptionToJSONTyped,
} from './TimeZoneOption';

/**
 * 
 * @export
 * @interface GetTimeZones200Response
 */
export interface GetTimeZones200Response {
    /**
     * 
     * @type {Array<TimeZoneOption>}
     * @memberof GetTimeZones200Response
     */
    usZones?: Array<TimeZoneOption>;
    /**
     * 
     * @type {Array<TimeZoneOption>}
     * @memberof GetTimeZones200Response
     */
    otherZones?: Array<TimeZoneOption>;
}

/**
 * Check if a given object implements the GetTimeZones200Response interface.
 */
export function instanceOfGetTimeZones200Response(value: object): value is GetTimeZones200Response {
    return true;
}

export function GetTimeZones200ResponseFromJSON(json: any): GetTimeZones200Response {
    return GetTimeZones200ResponseFromJSONTyped(json, false);
}

export function GetTimeZones200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTimeZones200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'usZones': json['us_zones'] == null ? undefined : ((json['us_zones'] as Array<any>).map(TimeZoneOptionFromJSON)),
        'otherZones': json['other_zones'] == null ? undefined : ((json['other_zones'] as Array<any>).map(TimeZoneOptionFromJSON)),
    };
}

export function GetTimeZones200ResponseToJSON(json: any): GetTimeZones200Response {
    return GetTimeZones200ResponseToJSONTyped(json, false);
}

export function GetTimeZones200ResponseToJSONTyped(value?: GetTimeZones200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'us_zones': value['usZones'] == null ? undefined : ((value['usZones'] as Array<any>).map(TimeZoneOptionToJSON)),
        'other_zones': value['otherZones'] == null ? undefined : ((value['otherZones'] as Array<any>).map(TimeZoneOptionToJSON)),
    };
}

