/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.42.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { WireChange } from './WireChange';
import {
    WireChangeFromJSON,
    WireChangeFromJSONTyped,
    WireChangeToJSON,
    WireChangeToJSONTyped,
} from './WireChange';

/**
 * 
 * @export
 * @interface GetWireChanges200Response
 */
export interface GetWireChanges200Response {
    /**
     * 
     * @type {Meta}
     * @memberof GetWireChanges200Response
     */
    meta?: Meta;
    /**
     * 
     * @type {Array<WireChange>}
     * @memberof GetWireChanges200Response
     */
    wireChanges?: Array<WireChange>;
}

/**
 * Check if a given object implements the GetWireChanges200Response interface.
 */
export function instanceOfGetWireChanges200Response(value: object): value is GetWireChanges200Response {
    return true;
}

export function GetWireChanges200ResponseFromJSON(json: any): GetWireChanges200Response {
    return GetWireChanges200ResponseFromJSONTyped(json, false);
}

export function GetWireChanges200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWireChanges200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
        'wireChanges': json['wire_changes'] == null ? undefined : ((json['wire_changes'] as Array<any>).map(WireChangeFromJSON)),
    };
}

export function GetWireChanges200ResponseToJSON(json: any): GetWireChanges200Response {
    return GetWireChanges200ResponseToJSONTyped(json, false);
}

export function GetWireChanges200ResponseToJSONTyped(value?: GetWireChanges200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': MetaToJSON(value['meta']),
        'wire_changes': value['wireChanges'] == null ? undefined : ((value['wireChanges'] as Array<any>).map(WireChangeToJSON)),
    };
}

