/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.54.2-dev.10366
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta1 } from './Meta1';
import {
    Meta1FromJSON,
    Meta1FromJSONTyped,
    Meta1ToJSON,
    Meta1ToJSONTyped,
} from './Meta1';
import type { Job } from './Job';
import {
    JobFromJSON,
    JobFromJSONTyped,
    JobToJSON,
    JobToJSONTyped,
} from './Job';

/**
 * 
 * @export
 * @interface JobCollection
 */
export interface JobCollection {
    /**
     * 
     * @type {Array<Job>}
     * @memberof JobCollection
     */
    data?: Array<Job>;
    /**
     * 
     * @type {Meta1}
     * @memberof JobCollection
     */
    meta?: Meta1;
}

/**
 * Check if a given object implements the JobCollection interface.
 */
export function instanceOfJobCollection(value: object): value is JobCollection {
    return true;
}

export function JobCollectionFromJSON(json: any): JobCollection {
    return JobCollectionFromJSONTyped(json, false);
}

export function JobCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(JobFromJSON)),
        'meta': json['meta'] == null ? undefined : Meta1FromJSON(json['meta']),
    };
}

export function JobCollectionToJSON(json: any): JobCollection {
    return JobCollectionToJSONTyped(json, false);
}

export function JobCollectionToJSONTyped(value?: JobCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(JobToJSON)),
        'meta': Meta1ToJSON(value['meta']),
    };
}

