/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.43.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { JobPost } from './JobPost';
import {
    JobPostFromJSON,
    JobPostFromJSONTyped,
    JobPostToJSON,
    JobPostToJSONTyped,
} from './JobPost';

/**
 * 
 * @export
 * @interface JobPostCollection
 */
export interface JobPostCollection {
    /**
     * 
     * @type {Array<JobPost>}
     * @memberof JobPostCollection
     */
    data?: Array<JobPost>;
    /**
     * 
     * @type {Meta}
     * @memberof JobPostCollection
     */
    meta?: Meta;
}

/**
 * Check if a given object implements the JobPostCollection interface.
 */
export function instanceOfJobPostCollection(value: object): value is JobPostCollection {
    return true;
}

export function JobPostCollectionFromJSON(json: any): JobPostCollection {
    return JobPostCollectionFromJSONTyped(json, false);
}

export function JobPostCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobPostCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(JobPostFromJSON)),
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
    };
}

export function JobPostCollectionToJSON(json: any): JobPostCollection {
    return JobPostCollectionToJSONTyped(json, false);
}

export function JobPostCollectionToJSONTyped(value?: JobPostCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(JobPostToJSON)),
        'meta': MetaToJSON(value['meta']),
    };
}

