/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.54.0-dev.10377
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta1 } from './Meta1';
import {
    Meta1FromJSON,
    Meta1FromJSONTyped,
    Meta1ToJSON,
    Meta1ToJSONTyped,
} from './Meta1';
import type { JobPostInterestLead } from './JobPostInterestLead';
import {
    JobPostInterestLeadFromJSON,
    JobPostInterestLeadFromJSONTyped,
    JobPostInterestLeadToJSON,
    JobPostInterestLeadToJSONTyped,
} from './JobPostInterestLead';

/**
 * 
 * @export
 * @interface JobPostInterestLeadCollection
 */
export interface JobPostInterestLeadCollection {
    /**
     * 
     * @type {Array<JobPostInterestLead>}
     * @memberof JobPostInterestLeadCollection
     */
    data?: Array<JobPostInterestLead>;
    /**
     * 
     * @type {Meta1}
     * @memberof JobPostInterestLeadCollection
     */
    meta?: Meta1;
}

/**
 * Check if a given object implements the JobPostInterestLeadCollection interface.
 */
export function instanceOfJobPostInterestLeadCollection(value: object): value is JobPostInterestLeadCollection {
    return true;
}

export function JobPostInterestLeadCollectionFromJSON(json: any): JobPostInterestLeadCollection {
    return JobPostInterestLeadCollectionFromJSONTyped(json, false);
}

export function JobPostInterestLeadCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobPostInterestLeadCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(JobPostInterestLeadFromJSON)),
        'meta': json['meta'] == null ? undefined : Meta1FromJSON(json['meta']),
    };
}

export function JobPostInterestLeadCollectionToJSON(json: any): JobPostInterestLeadCollection {
    return JobPostInterestLeadCollectionToJSONTyped(json, false);
}

export function JobPostInterestLeadCollectionToJSONTyped(value?: JobPostInterestLeadCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(JobPostInterestLeadToJSON)),
        'meta': Meta1ToJSON(value['meta']),
    };
}

