/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.42
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobSchool } from './JobSchool';
import {
    JobSchoolFromJSON,
    JobSchoolFromJSONTyped,
    JobSchoolToJSON,
    JobSchoolToJSONTyped,
} from './JobSchool';

/**
 * 
 * @export
 * @interface JobPostInterestLeadJob
 */
export interface JobPostInterestLeadJob {
    /**
     * 
     * @type {number}
     * @memberof JobPostInterestLeadJob
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof JobPostInterestLeadJob
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof JobPostInterestLeadJob
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof JobPostInterestLeadJob
     */
    url?: string;
    /**
     * 
     * @type {Date}
     * @memberof JobPostInterestLeadJob
     */
    postedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof JobPostInterestLeadJob
     */
    expiredAt?: Date | null;
    /**
     * 
     * @type {JobSchool}
     * @memberof JobPostInterestLeadJob
     */
    school?: JobSchool;
}

/**
 * Check if a given object implements the JobPostInterestLeadJob interface.
 */
export function instanceOfJobPostInterestLeadJob(value: object): value is JobPostInterestLeadJob {
    return true;
}

export function JobPostInterestLeadJobFromJSON(json: any): JobPostInterestLeadJob {
    return JobPostInterestLeadJobFromJSONTyped(json, false);
}

export function JobPostInterestLeadJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobPostInterestLeadJob {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'url': json['url'] == null ? undefined : json['url'],
        'postedAt': json['posted_at'] == null ? undefined : (new Date(json['posted_at'])),
        'expiredAt': json['expired_at'] == null ? undefined : (new Date(json['expired_at'])),
        'school': json['school'] == null ? undefined : JobSchoolFromJSON(json['school']),
    };
}

export function JobPostInterestLeadJobToJSON(json: any): JobPostInterestLeadJob {
    return JobPostInterestLeadJobToJSONTyped(json, false);
}

export function JobPostInterestLeadJobToJSONTyped(value?: JobPostInterestLeadJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'slug': value['slug'],
        'url': value['url'],
        'posted_at': value['postedAt'] == null ? value['postedAt'] : value['postedAt'].toISOString(),
        'expired_at': value['expiredAt'] == null ? value['expiredAt'] : value['expiredAt'].toISOString(),
        'school': JobSchoolToJSON(value['school']),
    };
}

