/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.40
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobProgress } from './JobProgress';
import {
    JobProgressFromJSON,
    JobProgressFromJSONTyped,
    JobProgressToJSON,
    JobProgressToJSONTyped,
} from './JobProgress';

/**
 * 
 * @export
 * @interface JobStatus
 */
export interface JobStatus {
    /**
     * 
     * @type {string}
     * @memberof JobStatus
     */
    jobId: string;
    /**
     * 
     * @type {string}
     * @memberof JobStatus
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof JobStatus
     */
    profile?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JobStatus
     */
    pageCount?: number | null;
    /**
     * 
     * @type {JobProgress}
     * @memberof JobStatus
     */
    progress: JobProgress;
    /**
     * 
     * @type {string}
     * @memberof JobStatus
     */
    createdAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobStatus
     */
    completedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobStatus
     */
    error?: string | null;
}

/**
 * Check if a given object implements the JobStatus interface.
 */
export function instanceOfJobStatus(value: object): value is JobStatus {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    return true;
}

export function JobStatusFromJSON(json: any): JobStatus {
    return JobStatusFromJSONTyped(json, false);
}

export function JobStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['job_id'],
        'status': json['status'],
        'profile': json['profile'] == null ? undefined : json['profile'],
        'pageCount': json['page_count'] == null ? undefined : json['page_count'],
        'progress': JobProgressFromJSON(json['progress']),
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'completedAt': json['completed_at'] == null ? undefined : json['completed_at'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function JobStatusToJSON(json: any): JobStatus {
    return JobStatusToJSONTyped(json, false);
}

export function JobStatusToJSONTyped(value?: JobStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['jobId'],
        'status': value['status'],
        'profile': value['profile'],
        'page_count': value['pageCount'],
        'progress': JobProgressToJSON(value['progress']),
        'created_at': value['createdAt'],
        'completed_at': value['completedAt'],
        'error': value['error'],
    };
}

