/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31393187616
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MassUpdateAdminCompensationsRequestCompensationsInner } from './MassUpdateAdminCompensationsRequestCompensationsInner';
import {
    MassUpdateAdminCompensationsRequestCompensationsInnerFromJSON,
    MassUpdateAdminCompensationsRequestCompensationsInnerFromJSONTyped,
    MassUpdateAdminCompensationsRequestCompensationsInnerToJSON,
    MassUpdateAdminCompensationsRequestCompensationsInnerToJSONTyped,
} from './MassUpdateAdminCompensationsRequestCompensationsInner';

/**
 * 
 * @export
 * @interface MassUpdateAdminCompensationsRequest
 */
export interface MassUpdateAdminCompensationsRequest {
    /**
     * 
     * @type {number}
     * @memberof MassUpdateAdminCompensationsRequest
     */
    coachId: number;
    /**
     * 
     * @type {Array<MassUpdateAdminCompensationsRequestCompensationsInner>}
     * @memberof MassUpdateAdminCompensationsRequest
     */
    compensations: Array<MassUpdateAdminCompensationsRequestCompensationsInner>;
}

/**
 * Check if a given object implements the MassUpdateAdminCompensationsRequest interface.
 */
export function instanceOfMassUpdateAdminCompensationsRequest(value: object): value is MassUpdateAdminCompensationsRequest {
    if (!('coachId' in value) || value['coachId'] === undefined) return false;
    if (!('compensations' in value) || value['compensations'] === undefined) return false;
    return true;
}

export function MassUpdateAdminCompensationsRequestFromJSON(json: any): MassUpdateAdminCompensationsRequest {
    return MassUpdateAdminCompensationsRequestFromJSONTyped(json, false);
}

export function MassUpdateAdminCompensationsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MassUpdateAdminCompensationsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'coachId': json['coach_id'],
        'compensations': ((json['compensations'] as Array<any>).map(MassUpdateAdminCompensationsRequestCompensationsInnerFromJSON)),
    };
}

export function MassUpdateAdminCompensationsRequestToJSON(json: any): MassUpdateAdminCompensationsRequest {
    return MassUpdateAdminCompensationsRequestToJSONTyped(json, false);
}

export function MassUpdateAdminCompensationsRequestToJSONTyped(value?: MassUpdateAdminCompensationsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coach_id': value['coachId'],
        'compensations': ((value['compensations'] as Array<any>).map(MassUpdateAdminCompensationsRequestCompensationsInnerToJSON)),
    };
}

