/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31383289480
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminCompensation } from './AdminCompensation';
import {
    AdminCompensationFromJSON,
    AdminCompensationFromJSONTyped,
    AdminCompensationToJSON,
    AdminCompensationToJSONTyped,
} from './AdminCompensation';

/**
 * 
 * @export
 * @interface MassUpdateAdminCompensations200Response
 */
export interface MassUpdateAdminCompensations200Response {
    /**
     * 
     * @type {Array<AdminCompensation>}
     * @memberof MassUpdateAdminCompensations200Response
     */
    updated?: Array<AdminCompensation>;
}

/**
 * Check if a given object implements the MassUpdateAdminCompensations200Response interface.
 */
export function instanceOfMassUpdateAdminCompensations200Response(value: object): value is MassUpdateAdminCompensations200Response {
    return true;
}

export function MassUpdateAdminCompensations200ResponseFromJSON(json: any): MassUpdateAdminCompensations200Response {
    return MassUpdateAdminCompensations200ResponseFromJSONTyped(json, false);
}

export function MassUpdateAdminCompensations200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MassUpdateAdminCompensations200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'updated': json['updated'] == null ? undefined : ((json['updated'] as Array<any>).map(AdminCompensationFromJSON)),
    };
}

export function MassUpdateAdminCompensations200ResponseToJSON(json: any): MassUpdateAdminCompensations200Response {
    return MassUpdateAdminCompensations200ResponseToJSONTyped(json, false);
}

export function MassUpdateAdminCompensations200ResponseToJSONTyped(value?: MassUpdateAdminCompensations200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'updated': value['updated'] == null ? undefined : ((value['updated'] as Array<any>).map(AdminCompensationToJSON)),
    };
}

