/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PerformanceChartRecord } from './PerformanceChartRecord';
import {
    PerformanceChartRecordFromJSON,
    PerformanceChartRecordFromJSONTyped,
    PerformanceChartRecordToJSON,
    PerformanceChartRecordToJSONTyped,
} from './PerformanceChartRecord';
import type { PerformanceChartCoach } from './PerformanceChartCoach';
import {
    PerformanceChartCoachFromJSON,
    PerformanceChartCoachFromJSONTyped,
    PerformanceChartCoachToJSON,
    PerformanceChartCoachToJSONTyped,
} from './PerformanceChartCoach';

/**
 * 
 * @export
 * @interface PerformanceChartData
 */
export interface PerformanceChartData {
    /**
     * 
     * @type {Array<string>}
     * @memberof PerformanceChartData
     */
    seasons: Array<string>;
    /**
     * 
     * @type {Array<PerformanceChartRecord>}
     * @memberof PerformanceChartData
     */
    records: Array<PerformanceChartRecord>;
    /**
     * 
     * @type {Array<PerformanceChartCoach>}
     * @memberof PerformanceChartData
     */
    coaches: Array<PerformanceChartCoach>;
}

/**
 * Check if a given object implements the PerformanceChartData interface.
 */
export function instanceOfPerformanceChartData(value: object): value is PerformanceChartData {
    if (!('seasons' in value) || value['seasons'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    if (!('coaches' in value) || value['coaches'] === undefined) return false;
    return true;
}

export function PerformanceChartDataFromJSON(json: any): PerformanceChartData {
    return PerformanceChartDataFromJSONTyped(json, false);
}

export function PerformanceChartDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceChartData {
    if (json == null) {
        return json;
    }
    return {
        
        'seasons': json['seasons'],
        'records': ((json['records'] as Array<any>).map(PerformanceChartRecordFromJSON)),
        'coaches': ((json['coaches'] as Array<any>).map(PerformanceChartCoachFromJSON)),
    };
}

export function PerformanceChartDataToJSON(json: any): PerformanceChartData {
    return PerformanceChartDataToJSONTyped(json, false);
}

export function PerformanceChartDataToJSONTyped(value?: PerformanceChartData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'seasons': value['seasons'],
        'records': ((value['records'] as Array<any>).map(PerformanceChartRecordToJSON)),
        'coaches': ((value['coaches'] as Array<any>).map(PerformanceChartCoachToJSON)),
    };
}

