/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PerformanceChartRecord
 */
export interface PerformanceChartRecord {
    /**
     * 
     * @type {number}
     * @memberof PerformanceChartRecord
     */
    wins?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PerformanceChartRecord
     */
    losses?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PerformanceChartRecord
     */
    ties?: number | null;
}

/**
 * Check if a given object implements the PerformanceChartRecord interface.
 */
export function instanceOfPerformanceChartRecord(value: object): value is PerformanceChartRecord {
    return true;
}

export function PerformanceChartRecordFromJSON(json: any): PerformanceChartRecord {
    return PerformanceChartRecordFromJSONTyped(json, false);
}

export function PerformanceChartRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceChartRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'wins': json['wins'] == null ? undefined : json['wins'],
        'losses': json['losses'] == null ? undefined : json['losses'],
        'ties': json['ties'] == null ? undefined : json['ties'],
    };
}

export function PerformanceChartRecordToJSON(json: any): PerformanceChartRecord {
    return PerformanceChartRecordToJSONTyped(json, false);
}

export function PerformanceChartRecordToJSONTyped(value?: PerformanceChartRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wins': value['wins'],
        'losses': value['losses'],
        'ties': value['ties'],
    };
}

