/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.43.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PositionTypeGroup
 */
export interface PositionTypeGroup {
    /**
     * 
     * @type {number}
     * @memberof PositionTypeGroup
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PositionTypeGroup
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PositionTypeGroup
     */
    nameDisplay?: string;
    /**
     * 
     * @type {number}
     * @memberof PositionTypeGroup
     */
    ord?: number;
    /**
     * 
     * @type {Date}
     * @memberof PositionTypeGroup
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PositionTypeGroup
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the PositionTypeGroup interface.
 */
export function instanceOfPositionTypeGroup(value: object): value is PositionTypeGroup {
    return true;
}

export function PositionTypeGroupFromJSON(json: any): PositionTypeGroup {
    return PositionTypeGroupFromJSONTyped(json, false);
}

export function PositionTypeGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): PositionTypeGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameDisplay': json['name_display'] == null ? undefined : json['name_display'],
        'ord': json['ord'] == null ? undefined : json['ord'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function PositionTypeGroupToJSON(json: any): PositionTypeGroup {
    return PositionTypeGroupToJSONTyped(json, false);
}

export function PositionTypeGroupToJSONTyped(value?: PositionTypeGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'name_display': value['nameDisplay'],
        'ord': value['ord'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

