/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.43.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PredictSuccess
 */
export interface PredictSuccess {
    /**
     * 
     * @type {boolean}
     * @memberof PredictSuccess
     */
    isAthletic?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PredictSuccess
     */
    model?: string;
    /**
     * 
     * @type {number}
     * @memberof PredictSuccess
     */
    probability?: number;
}

/**
 * Check if a given object implements the PredictSuccess interface.
 */
export function instanceOfPredictSuccess(value: object): value is PredictSuccess {
    return true;
}

export function PredictSuccessFromJSON(json: any): PredictSuccess {
    return PredictSuccessFromJSONTyped(json, false);
}

export function PredictSuccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredictSuccess {
    if (json == null) {
        return json;
    }
    return {
        
        'isAthletic': json['is_athletic'] == null ? undefined : json['is_athletic'],
        'model': json['model'] == null ? undefined : json['model'],
        'probability': json['probability'] == null ? undefined : json['probability'],
    };
}

export function PredictSuccessToJSON(json: any): PredictSuccess {
    return PredictSuccessToJSONTyped(json, false);
}

export function PredictSuccessToJSONTyped(value?: PredictSuccess | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_athletic': value['isAthletic'],
        'model': value['model'],
        'probability': value['probability'],
    };
}

