/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.42.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PredictFailure
 */
export interface PredictFailure {
    /**
     * 
     * @type {string}
     * @memberof PredictFailure
     */
    detail?: string;
}

/**
 * Check if a given object implements the PredictFailure interface.
 */
export function instanceOfPredictFailure(value: object): value is PredictFailure {
    return true;
}

export function PredictFailureFromJSON(json: any): PredictFailure {
    return PredictFailureFromJSONTyped(json, false);
}

export function PredictFailureFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredictFailure {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function PredictFailureToJSON(json: any): PredictFailure {
    return PredictFailureToJSONTyped(json, false);
}

export function PredictFailureToJSONTyped(value?: PredictFailure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': value['detail'],
    };
}

