/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.42.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RawContract
 */
export interface RawContract {
    /**
     * 
     * @type {number}
     * @memberof RawContract
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof RawContract
     */
    assetFileSize?: number;
    /**
     * 
     * @type {string}
     * @memberof RawContract
     */
    assetContentType?: string;
    /**
     * 
     * @type {string}
     * @memberof RawContract
     */
    assetFileName?: string;
    /**
     * 
     * @type {Date}
     * @memberof RawContract
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RawContract
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof RawContract
     */
    contractTypeId?: number;
    /**
     * 
     * @type {number}
     * @memberof RawContract
     */
    uploaded?: number;
    /**
     * 
     * @type {number}
     * @memberof RawContract
     */
    dealId?: number;
    /**
     * 
     * @type {number}
     * @memberof RawContract
     */
    schoolId?: number;
    /**
     * 
     * @type {number}
     * @memberof RawContract
     */
    schoolRevenueYear?: number;
    /**
     * 
     * @type {number}
     * @memberof RawContract
     */
    auditedFinancialYear?: number;
    /**
     * 
     * @type {string}
     * @memberof RawContract
     */
    text?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RawContract
     */
    useFlexpaper?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RawContract
     */
    gameContractsCount?: number;
    /**
     * 
     * @type {string}
     * @memberof RawContract
     */
    driveId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RawContract
     */
    migratedSuccessfully?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RawContract
     */
    migrationFailureReason?: string;
    /**
     * 
     * @type {string}
     * @memberof RawContract
     */
    unstractPdfText?: string;
    /**
     * 
     * @type {string}
     * @memberof RawContract
     */
    unstractResponsesDetails?: string;
    /**
     * 
     * @type {string}
     * @memberof RawContract
     */
    layoutPreservedPdfText?: string;
}

/**
 * Check if a given object implements the RawContract interface.
 */
export function instanceOfRawContract(value: object): value is RawContract {
    return true;
}

export function RawContractFromJSON(json: any): RawContract {
    return RawContractFromJSONTyped(json, false);
}

export function RawContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawContract {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'assetFileSize': json['asset_file_size'] == null ? undefined : json['asset_file_size'],
        'assetContentType': json['asset_content_type'] == null ? undefined : json['asset_content_type'],
        'assetFileName': json['asset_file_name'] == null ? undefined : json['asset_file_name'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'contractTypeId': json['contract_type_id'] == null ? undefined : json['contract_type_id'],
        'uploaded': json['uploaded'] == null ? undefined : json['uploaded'],
        'dealId': json['deal_id'] == null ? undefined : json['deal_id'],
        'schoolId': json['school_id'] == null ? undefined : json['school_id'],
        'schoolRevenueYear': json['school_revenue_year'] == null ? undefined : json['school_revenue_year'],
        'auditedFinancialYear': json['audited_financial_year'] == null ? undefined : json['audited_financial_year'],
        'text': json['text'] == null ? undefined : json['text'],
        'useFlexpaper': json['use_flexpaper'] == null ? undefined : json['use_flexpaper'],
        'gameContractsCount': json['game_contracts_count'] == null ? undefined : json['game_contracts_count'],
        'driveId': json['drive_id'] == null ? undefined : json['drive_id'],
        'migratedSuccessfully': json['migrated_successfully'] == null ? undefined : json['migrated_successfully'],
        'migrationFailureReason': json['migration_failure_reason'] == null ? undefined : json['migration_failure_reason'],
        'unstractPdfText': json['unstract_pdf_text'] == null ? undefined : json['unstract_pdf_text'],
        'unstractResponsesDetails': json['unstract_responses_details'] == null ? undefined : json['unstract_responses_details'],
        'layoutPreservedPdfText': json['layout_preserved_pdf_text'] == null ? undefined : json['layout_preserved_pdf_text'],
    };
}

export function RawContractToJSON(json: any): RawContract {
    return RawContractToJSONTyped(json, false);
}

export function RawContractToJSONTyped(value?: RawContract | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'asset_file_size': value['assetFileSize'],
        'asset_content_type': value['assetContentType'],
        'asset_file_name': value['assetFileName'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'contract_type_id': value['contractTypeId'],
        'uploaded': value['uploaded'],
        'deal_id': value['dealId'],
        'school_id': value['schoolId'],
        'school_revenue_year': value['schoolRevenueYear'],
        'audited_financial_year': value['auditedFinancialYear'],
        'text': value['text'],
        'use_flexpaper': value['useFlexpaper'],
        'game_contracts_count': value['gameContractsCount'],
        'drive_id': value['driveId'],
        'migrated_successfully': value['migratedSuccessfully'],
        'migration_failure_reason': value['migrationFailureReason'],
        'unstract_pdf_text': value['unstractPdfText'],
        'unstract_responses_details': value['unstractResponsesDetails'],
        'layout_preserved_pdf_text': value['layoutPreservedPdfText'],
    };
}

