/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.2-dev.1153
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoteJobPost
 */
export interface RemoteJobPost {
    /**
     * Remote job post ID
     * @type {number}
     * @memberof RemoteJobPost
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof RemoteJobPost
     */
    uid?: string;
    /**
     * 
     * @type {string}
     * @memberof RemoteJobPost
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof RemoteJobPost
     */
    link: string;
    /**
     * 
     * @type {string}
     * @memberof RemoteJobPost
     */
    workType?: string;
    /**
     * 
     * @type {string}
     * @memberof RemoteJobPost
     */
    descriptionMd?: string;
    /**
     * 
     * @type {string}
     * @memberof RemoteJobPost
     */
    salarySummary?: string;
    /**
     * Remote school WinAD ID
     * @type {number}
     * @memberof RemoteJobPost
     */
    schoolId: number;
    /**
     * 
     * @type {boolean}
     * @memberof RemoteJobPost
     */
    expired?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof RemoteJobPost
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RemoteJobPost
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof RemoteJobPost
     */
    annualSalary?: number;
    /**
     * 
     * @type {number}
     * @memberof RemoteJobPost
     */
    minSalary?: number;
    /**
     * 
     * @type {number}
     * @memberof RemoteJobPost
     */
    maxSalary?: number;
    /**
     * 
     * @type {string}
     * @memberof RemoteJobPost
     */
    payPeriod?: string;
    /**
     * 
     * @type {number}
     * @memberof RemoteJobPost
     */
    requiredYearsOfExperience?: number;
}

/**
 * Check if a given object implements the RemoteJobPost interface.
 */
export function instanceOfRemoteJobPost(value: object): value is RemoteJobPost {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('link' in value) || value['link'] === undefined) return false;
    if (!('schoolId' in value) || value['schoolId'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function RemoteJobPostFromJSON(json: any): RemoteJobPost {
    return RemoteJobPostFromJSONTyped(json, false);
}

export function RemoteJobPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoteJobPost {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'uid': json['uid'] == null ? undefined : json['uid'],
        'title': json['title'],
        'link': json['link'],
        'workType': json['work_type'] == null ? undefined : json['work_type'],
        'descriptionMd': json['description_md'] == null ? undefined : json['description_md'],
        'salarySummary': json['salary_summary'] == null ? undefined : json['salary_summary'],
        'schoolId': json['school_id'],
        'expired': json['expired'] == null ? undefined : json['expired'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'annualSalary': json['annual_salary'] == null ? undefined : json['annual_salary'],
        'minSalary': json['min_salary'] == null ? undefined : json['min_salary'],
        'maxSalary': json['max_salary'] == null ? undefined : json['max_salary'],
        'payPeriod': json['pay_period'] == null ? undefined : json['pay_period'],
        'requiredYearsOfExperience': json['required_years_of_experience'] == null ? undefined : json['required_years_of_experience'],
    };
}

export function RemoteJobPostToJSON(json: any): RemoteJobPost {
    return RemoteJobPostToJSONTyped(json, false);
}

export function RemoteJobPostToJSONTyped(value?: RemoteJobPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'uid': value['uid'],
        'title': value['title'],
        'link': value['link'],
        'work_type': value['workType'],
        'description_md': value['descriptionMd'],
        'salary_summary': value['salarySummary'],
        'school_id': value['schoolId'],
        'expired': value['expired'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'annual_salary': value['annualSalary'],
        'min_salary': value['minSalary'],
        'max_salary': value['maxSalary'],
        'pay_period': value['payPeriod'],
        'required_years_of_experience': value['requiredYearsOfExperience'],
    };
}

