/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.40
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestedItemNoteInputRiNote
 */
export interface RequestedItemNoteInputRiNote {
    /**
     * Note text to create, replace, or append. Leading and trailing whitespace is trimmed; blank or whitespace-only values are rejected.
     * @type {string}
     * @memberof RequestedItemNoteInputRiNote
     */
    note: string;
    /**
     * When true, append the note text to any existing note (skipped if the text is already present as an entry). When false or omitted, replace the existing note content.
     * @type {boolean}
     * @memberof RequestedItemNoteInputRiNote
     */
    append?: boolean;
}

/**
 * Check if a given object implements the RequestedItemNoteInputRiNote interface.
 */
export function instanceOfRequestedItemNoteInputRiNote(value: object): value is RequestedItemNoteInputRiNote {
    if (!('note' in value) || value['note'] === undefined) return false;
    return true;
}

export function RequestedItemNoteInputRiNoteFromJSON(json: any): RequestedItemNoteInputRiNote {
    return RequestedItemNoteInputRiNoteFromJSONTyped(json, false);
}

export function RequestedItemNoteInputRiNoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestedItemNoteInputRiNote {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'],
        'append': json['append'] == null ? undefined : json['append'],
    };
}

export function RequestedItemNoteInputRiNoteToJSON(json: any): RequestedItemNoteInputRiNote {
    return RequestedItemNoteInputRiNoteToJSONTyped(json, false);
}

export function RequestedItemNoteInputRiNoteToJSONTyped(value?: RequestedItemNoteInputRiNote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'note': value['note'],
        'append': value['append'],
    };
}

