/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.29825145814
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestedItemReviewContextRequestedItem
 */
export interface RequestedItemReviewContextRequestedItem {
    /**
     * 
     * @type {number}
     * @memberof RequestedItemReviewContextRequestedItem
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof RequestedItemReviewContextRequestedItem
     */
    status: RequestedItemReviewContextRequestedItemStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof RequestedItemReviewContextRequestedItem
     */
    requestableId: number;
    /**
     * 
     * @type {string}
     * @memberof RequestedItemReviewContextRequestedItem
     */
    requestableType: RequestedItemReviewContextRequestedItemRequestableTypeEnum;
    /**
     * Human-readable requested item category as displayed in WinAD.
     * @type {string}
     * @memberof RequestedItemReviewContextRequestedItem
     */
    typeDisplay: string;
    /**
     * Canonical WinAD display title for the requested item. Returns "Item Deleted" when the underlying requestable record no longer exists.
     * @type {string}
     * @memberof RequestedItemReviewContextRequestedItem
     */
    title: string;
}


/**
 * @export
 */
export const RequestedItemReviewContextRequestedItemStatusEnum = {
    Pending: 'pending',
    NotAvailable: 'not_available',
    Received: 'received'
} as const;
export type RequestedItemReviewContextRequestedItemStatusEnum = typeof RequestedItemReviewContextRequestedItemStatusEnum[keyof typeof RequestedItemReviewContextRequestedItemStatusEnum];

/**
 * @export
 */
export const RequestedItemReviewContextRequestedItemRequestableTypeEnum = {
    DealStatus: 'DealStatus',
    Game: 'Game',
    Compensation: 'Compensation',
    IncomeReport: 'IncomeReport',
    NcaaFinancialReportStatus: 'NcaaFinancialReportStatus',
    AuditedFinancialReportStatus: 'AuditedFinancialReportStatus'
} as const;
export type RequestedItemReviewContextRequestedItemRequestableTypeEnum = typeof RequestedItemReviewContextRequestedItemRequestableTypeEnum[keyof typeof RequestedItemReviewContextRequestedItemRequestableTypeEnum];


/**
 * Check if a given object implements the RequestedItemReviewContextRequestedItem interface.
 */
export function instanceOfRequestedItemReviewContextRequestedItem(value: object): value is RequestedItemReviewContextRequestedItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('requestableId' in value) || value['requestableId'] === undefined) return false;
    if (!('requestableType' in value) || value['requestableType'] === undefined) return false;
    if (!('typeDisplay' in value) || value['typeDisplay'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function RequestedItemReviewContextRequestedItemFromJSON(json: any): RequestedItemReviewContextRequestedItem {
    return RequestedItemReviewContextRequestedItemFromJSONTyped(json, false);
}

export function RequestedItemReviewContextRequestedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestedItemReviewContextRequestedItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'requestableId': json['requestable_id'],
        'requestableType': json['requestable_type'],
        'typeDisplay': json['type_display'],
        'title': json['title'],
    };
}

export function RequestedItemReviewContextRequestedItemToJSON(json: any): RequestedItemReviewContextRequestedItem {
    return RequestedItemReviewContextRequestedItemToJSONTyped(json, false);
}

export function RequestedItemReviewContextRequestedItemToJSONTyped(value?: RequestedItemReviewContextRequestedItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'requestable_id': value['requestableId'],
        'requestable_type': value['requestableType'],
        'type_display': value['typeDisplay'],
        'title': value['title'],
    };
}

