/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.44-dev.10006
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunningJob
 */
export interface RunningJob {
    /**
     * 
     * @type {string}
     * @memberof RunningJob
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof RunningJob
     */
    active?: number;
    /**
     * 
     * @type {number}
     * @memberof RunningJob
     */
    succeeded?: number;
    /**
     * 
     * @type {number}
     * @memberof RunningJob
     */
    failed?: number;
    /**
     * 
     * @type {Date}
     * @memberof RunningJob
     */
    startTime?: Date | null;
}

/**
 * Check if a given object implements the RunningJob interface.
 */
export function instanceOfRunningJob(value: object): value is RunningJob {
    return true;
}

export function RunningJobFromJSON(json: any): RunningJob {
    return RunningJobFromJSONTyped(json, false);
}

export function RunningJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunningJob {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'active': json['active'] == null ? undefined : json['active'],
        'succeeded': json['succeeded'] == null ? undefined : json['succeeded'],
        'failed': json['failed'] == null ? undefined : json['failed'],
        'startTime': json['startTime'] == null ? undefined : (new Date(json['startTime'])),
    };
}

export function RunningJobToJSON(json: any): RunningJob {
    return RunningJobToJSONTyped(json, false);
}

export function RunningJobToJSONTyped(value?: RunningJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'active': value['active'],
        'succeeded': value['succeeded'],
        'failed': value['failed'],
        'startTime': value['startTime'] == null ? value['startTime'] : value['startTime'].toISOString(),
    };
}

