/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.54.2-dev.10366
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SalarySiteAssociationsMeta
 */
export interface SalarySiteAssociationsMeta {
    /**
     * 
     * @type {Date}
     * @memberof SalarySiteAssociationsMeta
     */
    generatedAt: Date;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SalarySiteAssociationsMeta
     */
    filtersApplied?: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof SalarySiteAssociationsMeta
     */
    currentPage: number;
    /**
     * 
     * @type {number}
     * @memberof SalarySiteAssociationsMeta
     */
    perPage: number;
    /**
     * 
     * @type {number}
     * @memberof SalarySiteAssociationsMeta
     */
    maxPerPage: number;
    /**
     * 
     * @type {number}
     * @memberof SalarySiteAssociationsMeta
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof SalarySiteAssociationsMeta
     */
    totalEntries: number;
    /**
     * 
     * @type {number}
     * @memberof SalarySiteAssociationsMeta
     */
    nextPage?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SalarySiteAssociationsMeta
     */
    previousPage?: number | null;
}

/**
 * Check if a given object implements the SalarySiteAssociationsMeta interface.
 */
export function instanceOfSalarySiteAssociationsMeta(value: object): value is SalarySiteAssociationsMeta {
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('perPage' in value) || value['perPage'] === undefined) return false;
    if (!('maxPerPage' in value) || value['maxPerPage'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalEntries' in value) || value['totalEntries'] === undefined) return false;
    return true;
}

export function SalarySiteAssociationsMetaFromJSON(json: any): SalarySiteAssociationsMeta {
    return SalarySiteAssociationsMetaFromJSONTyped(json, false);
}

export function SalarySiteAssociationsMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalarySiteAssociationsMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'generatedAt': (new Date(json['generated_at'])),
        'filtersApplied': json['filters_applied'] == null ? undefined : json['filters_applied'],
        'currentPage': json['current_page'],
        'perPage': json['per_page'],
        'maxPerPage': json['max_per_page'],
        'totalPages': json['total_pages'],
        'totalEntries': json['total_entries'],
        'nextPage': json['next_page'] == null ? undefined : json['next_page'],
        'previousPage': json['previous_page'] == null ? undefined : json['previous_page'],
    };
}

export function SalarySiteAssociationsMetaToJSON(json: any): SalarySiteAssociationsMeta {
    return SalarySiteAssociationsMetaToJSONTyped(json, false);
}

export function SalarySiteAssociationsMetaToJSONTyped(value?: SalarySiteAssociationsMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generated_at': value['generatedAt'].toISOString(),
        'filters_applied': value['filtersApplied'],
        'current_page': value['currentPage'],
        'per_page': value['perPage'],
        'max_per_page': value['maxPerPage'],
        'total_pages': value['totalPages'],
        'total_entries': value['totalEntries'],
        'next_page': value['nextPage'],
        'previous_page': value['previousPage'],
    };
}

