/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One of the up-to-eight schools rendered as a column on the schedule grid
 * @export
 * @interface ScheduleGridSchool
 */
export interface ScheduleGridSchool {
    /**
     * 
     * @type {number}
     * @memberof ScheduleGridSchool
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ScheduleGridSchool
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScheduleGridSchool
     */
    shortName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScheduleGridSchool
     */
    logoUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScheduleGridSchool
     */
    primaryContactName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScheduleGridSchool
     */
    primaryContactPhone?: string | null;
}

/**
 * Check if a given object implements the ScheduleGridSchool interface.
 */
export function instanceOfScheduleGridSchool(value: object): value is ScheduleGridSchool {
    return true;
}

export function ScheduleGridSchoolFromJSON(json: any): ScheduleGridSchool {
    return ScheduleGridSchoolFromJSONTyped(json, false);
}

export function ScheduleGridSchoolFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleGridSchool {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'shortName': json['short_name'] == null ? undefined : json['short_name'],
        'logoUrl': json['logo_url'] == null ? undefined : json['logo_url'],
        'primaryContactName': json['primary_contact_name'] == null ? undefined : json['primary_contact_name'],
        'primaryContactPhone': json['primary_contact_phone'] == null ? undefined : json['primary_contact_phone'],
    };
}

export function ScheduleGridSchoolToJSON(json: any): ScheduleGridSchool {
    return ScheduleGridSchoolToJSONTyped(json, false);
}

export function ScheduleGridSchoolToJSONTyped(value?: ScheduleGridSchool | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'short_name': value['shortName'],
        'logo_url': value['logoUrl'],
        'primary_contact_name': value['primaryContactName'],
        'primary_contact_phone': value['primaryContactPhone'],
    };
}

