/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.30888521824
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DepartmentGuaranteesSportLedger } from './DepartmentGuaranteesSportLedger';
import {
    DepartmentGuaranteesSportLedgerFromJSON,
    DepartmentGuaranteesSportLedgerFromJSONTyped,
    DepartmentGuaranteesSportLedgerToJSON,
    DepartmentGuaranteesSportLedgerToJSONTyped,
} from './DepartmentGuaranteesSportLedger';
import type { DepartmentGuaranteesTrendEntry } from './DepartmentGuaranteesTrendEntry';
import {
    DepartmentGuaranteesTrendEntryFromJSON,
    DepartmentGuaranteesTrendEntryFromJSONTyped,
    DepartmentGuaranteesTrendEntryToJSON,
    DepartmentGuaranteesTrendEntryToJSONTyped,
} from './DepartmentGuaranteesTrendEntry';
import type { CompensationComparisonResolvedScopeConference } from './CompensationComparisonResolvedScopeConference';
import {
    CompensationComparisonResolvedScopeConferenceFromJSON,
    CompensationComparisonResolvedScopeConferenceFromJSONTyped,
    CompensationComparisonResolvedScopeConferenceToJSON,
    CompensationComparisonResolvedScopeConferenceToJSONTyped,
} from './CompensationComparisonResolvedScopeConference';
import type { DepartmentGuaranteesCommittedSide } from './DepartmentGuaranteesCommittedSide';
import {
    DepartmentGuaranteesCommittedSideFromJSON,
    DepartmentGuaranteesCommittedSideFromJSONTyped,
    DepartmentGuaranteesCommittedSideToJSON,
    DepartmentGuaranteesCommittedSideToJSONTyped,
} from './DepartmentGuaranteesCommittedSide';
import type { SchoolDepartmentGuaranteesSchool } from './SchoolDepartmentGuaranteesSchool';
import {
    SchoolDepartmentGuaranteesSchoolFromJSON,
    SchoolDepartmentGuaranteesSchoolFromJSONTyped,
    SchoolDepartmentGuaranteesSchoolToJSON,
    SchoolDepartmentGuaranteesSchoolToJSONTyped,
} from './SchoolDepartmentGuaranteesSchool';
import type { DepartmentGuaranteesFiledLine } from './DepartmentGuaranteesFiledLine';
import {
    DepartmentGuaranteesFiledLineFromJSON,
    DepartmentGuaranteesFiledLineFromJSONTyped,
    DepartmentGuaranteesFiledLineToJSON,
    DepartmentGuaranteesFiledLineToJSONTyped,
} from './DepartmentGuaranteesFiledLine';
import type { DepartmentGuaranteesMarket } from './DepartmentGuaranteesMarket';
import {
    DepartmentGuaranteesMarketFromJSON,
    DepartmentGuaranteesMarketFromJSONTyped,
    DepartmentGuaranteesMarketToJSON,
    DepartmentGuaranteesMarketToJSONTyped,
} from './DepartmentGuaranteesMarket';
import type { DepartmentGuaranteesQuadrant } from './DepartmentGuaranteesQuadrant';
import {
    DepartmentGuaranteesQuadrantFromJSON,
    DepartmentGuaranteesQuadrantFromJSONTyped,
    DepartmentGuaranteesQuadrantToJSON,
    DepartmentGuaranteesQuadrantToJSONTyped,
} from './DepartmentGuaranteesQuadrant';

/**
 * 
 * @export
 * @interface SchoolDepartmentGuarantees
 */
export interface SchoolDepartmentGuarantees {
    /**
     * 
     * @type {SchoolDepartmentGuaranteesSchool}
     * @memberof SchoolDepartmentGuarantees
     */
    school?: SchoolDepartmentGuaranteesSchool;
    /**
     * 
     * @type {CompensationComparisonResolvedScopeConference}
     * @memberof SchoolDepartmentGuarantees
     */
    conference?: CompensationComparisonResolvedScopeConference | null;
    /**
     * 
     * @type {number}
     * @memberof SchoolDepartmentGuarantees
     */
    seasonYear?: number;
    /**
     * 
     * @type {number}
     * @memberof SchoolDepartmentGuarantees
     */
    latestFiledYear?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SchoolDepartmentGuarantees
     */
    selectedYear?: number | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof SchoolDepartmentGuarantees
     */
    availableYears?: Array<number>;
    /**
     * 
     * @type {DepartmentGuaranteesQuadrant}
     * @memberof SchoolDepartmentGuarantees
     */
    quadrant?: DepartmentGuaranteesQuadrant | null;
    /**
     * 
     * @type {DepartmentGuaranteesFiledLine}
     * @memberof SchoolDepartmentGuarantees
     */
    filedLine?: DepartmentGuaranteesFiledLine | null;
    /**
     * 
     * @type {DepartmentGuaranteesCommittedSide}
     * @memberof SchoolDepartmentGuarantees
     */
    committedOut?: DepartmentGuaranteesCommittedSide;
    /**
     * 
     * @type {DepartmentGuaranteesCommittedSide}
     * @memberof SchoolDepartmentGuarantees
     */
    committedIn?: DepartmentGuaranteesCommittedSide;
    /**
     * 
     * @type {Array<DepartmentGuaranteesSportLedger>}
     * @memberof SchoolDepartmentGuarantees
     */
    sports?: Array<DepartmentGuaranteesSportLedger>;
    /**
     * 
     * @type {DepartmentGuaranteesMarket}
     * @memberof SchoolDepartmentGuarantees
     */
    market?: DepartmentGuaranteesMarket | null;
    /**
     * 
     * @type {Array<DepartmentGuaranteesTrendEntry>}
     * @memberof SchoolDepartmentGuarantees
     */
    trend?: Array<DepartmentGuaranteesTrendEntry>;
    /**
     * 
     * @type {number}
     * @memberof SchoolDepartmentGuarantees
     */
    counterpartyDocumentedCount?: number;
}

/**
 * Check if a given object implements the SchoolDepartmentGuarantees interface.
 */
export function instanceOfSchoolDepartmentGuarantees(value: object): value is SchoolDepartmentGuarantees {
    return true;
}

export function SchoolDepartmentGuaranteesFromJSON(json: any): SchoolDepartmentGuarantees {
    return SchoolDepartmentGuaranteesFromJSONTyped(json, false);
}

export function SchoolDepartmentGuaranteesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchoolDepartmentGuarantees {
    if (json == null) {
        return json;
    }
    return {
        
        'school': json['school'] == null ? undefined : SchoolDepartmentGuaranteesSchoolFromJSON(json['school']),
        'conference': json['conference'] == null ? undefined : CompensationComparisonResolvedScopeConferenceFromJSON(json['conference']),
        'seasonYear': json['season_year'] == null ? undefined : json['season_year'],
        'latestFiledYear': json['latest_filed_year'] == null ? undefined : json['latest_filed_year'],
        'selectedYear': json['selected_year'] == null ? undefined : json['selected_year'],
        'availableYears': json['available_years'] == null ? undefined : json['available_years'],
        'quadrant': json['quadrant'] == null ? undefined : DepartmentGuaranteesQuadrantFromJSON(json['quadrant']),
        'filedLine': json['filed_line'] == null ? undefined : DepartmentGuaranteesFiledLineFromJSON(json['filed_line']),
        'committedOut': json['committed_out'] == null ? undefined : DepartmentGuaranteesCommittedSideFromJSON(json['committed_out']),
        'committedIn': json['committed_in'] == null ? undefined : DepartmentGuaranteesCommittedSideFromJSON(json['committed_in']),
        'sports': json['sports'] == null ? undefined : ((json['sports'] as Array<any>).map(DepartmentGuaranteesSportLedgerFromJSON)),
        'market': json['market'] == null ? undefined : DepartmentGuaranteesMarketFromJSON(json['market']),
        'trend': json['trend'] == null ? undefined : ((json['trend'] as Array<any>).map(DepartmentGuaranteesTrendEntryFromJSON)),
        'counterpartyDocumentedCount': json['counterparty_documented_count'] == null ? undefined : json['counterparty_documented_count'],
    };
}

export function SchoolDepartmentGuaranteesToJSON(json: any): SchoolDepartmentGuarantees {
    return SchoolDepartmentGuaranteesToJSONTyped(json, false);
}

export function SchoolDepartmentGuaranteesToJSONTyped(value?: SchoolDepartmentGuarantees | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'school': SchoolDepartmentGuaranteesSchoolToJSON(value['school']),
        'conference': CompensationComparisonResolvedScopeConferenceToJSON(value['conference']),
        'season_year': value['seasonYear'],
        'latest_filed_year': value['latestFiledYear'],
        'selected_year': value['selectedYear'],
        'available_years': value['availableYears'],
        'quadrant': DepartmentGuaranteesQuadrantToJSON(value['quadrant']),
        'filed_line': DepartmentGuaranteesFiledLineToJSON(value['filedLine']),
        'committed_out': DepartmentGuaranteesCommittedSideToJSON(value['committedOut']),
        'committed_in': DepartmentGuaranteesCommittedSideToJSON(value['committedIn']),
        'sports': value['sports'] == null ? undefined : ((value['sports'] as Array<any>).map(DepartmentGuaranteesSportLedgerToJSON)),
        'market': DepartmentGuaranteesMarketToJSON(value['market']),
        'trend': value['trend'] == null ? undefined : ((value['trend'] as Array<any>).map(DepartmentGuaranteesTrendEntryToJSON)),
        'counterparty_documented_count': value['counterpartyDocumentedCount'],
    };
}

