/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.33163395279
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EadaSportResultItem } from './EadaSportResultItem';
import {
    EadaSportResultItemFromJSON,
    EadaSportResultItemFromJSONTyped,
    EadaSportResultItemToJSON,
    EadaSportResultItemToJSONTyped,
} from './EadaSportResultItem';

/**
 * 
 * @export
 * @interface SchoolEadaFinancialsSports
 */
export interface SchoolEadaFinancialsSports {
    /**
     * 
     * @type {boolean}
     * @memberof SchoolEadaFinancialsSports
     */
    found?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SchoolEadaFinancialsSports
     */
    count?: number;
    /**
     * 
     * @type {Array<EadaSportResultItem>}
     * @memberof SchoolEadaFinancialsSports
     */
    items?: Array<EadaSportResultItem>;
}

/**
 * Check if a given object implements the SchoolEadaFinancialsSports interface.
 */
export function instanceOfSchoolEadaFinancialsSports(value: object): value is SchoolEadaFinancialsSports {
    return true;
}

export function SchoolEadaFinancialsSportsFromJSON(json: any): SchoolEadaFinancialsSports {
    return SchoolEadaFinancialsSportsFromJSONTyped(json, false);
}

export function SchoolEadaFinancialsSportsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchoolEadaFinancialsSports {
    if (json == null) {
        return json;
    }
    return {
        
        'found': json['found'] == null ? undefined : json['found'],
        'count': json['count'] == null ? undefined : json['count'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(EadaSportResultItemFromJSON)),
    };
}

export function SchoolEadaFinancialsSportsToJSON(json: any): SchoolEadaFinancialsSports {
    return SchoolEadaFinancialsSportsToJSONTyped(json, false);
}

export function SchoolEadaFinancialsSportsToJSONTyped(value?: SchoolEadaFinancialsSports | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'found': value['found'],
        'count': value['count'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(EadaSportResultItemToJSON)),
    };
}

