/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.53.54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchoolDepartmentFinancialsConference
 */
export interface SchoolDepartmentFinancialsConference {
    /**
     * 
     * @type {number}
     * @memberof SchoolDepartmentFinancialsConference
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SchoolDepartmentFinancialsConference
     */
    name: string;
}

/**
 * Check if a given object implements the SchoolDepartmentFinancialsConference interface.
 */
export function instanceOfSchoolDepartmentFinancialsConference(value: object): value is SchoolDepartmentFinancialsConference {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SchoolDepartmentFinancialsConferenceFromJSON(json: any): SchoolDepartmentFinancialsConference {
    return SchoolDepartmentFinancialsConferenceFromJSONTyped(json, false);
}

export function SchoolDepartmentFinancialsConferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchoolDepartmentFinancialsConference {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function SchoolDepartmentFinancialsConferenceToJSON(json: any): SchoolDepartmentFinancialsConference {
    return SchoolDepartmentFinancialsConferenceToJSONTyped(json, false);
}

export function SchoolDepartmentFinancialsConferenceToJSONTyped(value?: SchoolDepartmentFinancialsConference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

