/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.42.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScraperArgDef
 */
export interface ScraperArgDef {
    /**
     * 
     * @type {string}
     * @memberof ScraperArgDef
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ScraperArgDef
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ScraperArgDef
     */
    description?: string;
}

/**
 * Check if a given object implements the ScraperArgDef interface.
 */
export function instanceOfScraperArgDef(value: object): value is ScraperArgDef {
    return true;
}

export function ScraperArgDefFromJSON(json: any): ScraperArgDef {
    return ScraperArgDefFromJSONTyped(json, false);
}

export function ScraperArgDefFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScraperArgDef {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ScraperArgDefToJSON(json: any): ScraperArgDef {
    return ScraperArgDefToJSONTyped(json, false);
}

export function ScraperArgDefToJSONTyped(value?: ScraperArgDef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'description': value['description'],
    };
}

