/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SportCompensationRankingsSchoolsInner } from './SportCompensationRankingsSchoolsInner';
import {
    SportCompensationRankingsSchoolsInnerFromJSON,
    SportCompensationRankingsSchoolsInnerFromJSONTyped,
    SportCompensationRankingsSchoolsInnerToJSON,
    SportCompensationRankingsSchoolsInnerToJSONTyped,
} from './SportCompensationRankingsSchoolsInner';

/**
 * 
 * @export
 * @interface SportCompensationRankings
 */
export interface SportCompensationRankings {
    /**
     * 
     * @type {boolean}
     * @memberof SportCompensationRankings
     */
    isFootball?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof SportCompensationRankings
     */
    years?: Array<number>;
    /**
     * 
     * @type {Array<SportCompensationRankingsSchoolsInner>}
     * @memberof SportCompensationRankings
     */
    schools?: Array<SportCompensationRankingsSchoolsInner>;
    /**
     * 
     * @type {{ [key: string]: number | null; }}
     * @memberof SportCompensationRankings
     */
    conferenceAvgs?: { [key: string]: number | null; };
}

/**
 * Check if a given object implements the SportCompensationRankings interface.
 */
export function instanceOfSportCompensationRankings(value: object): value is SportCompensationRankings {
    return true;
}

export function SportCompensationRankingsFromJSON(json: any): SportCompensationRankings {
    return SportCompensationRankingsFromJSONTyped(json, false);
}

export function SportCompensationRankingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SportCompensationRankings {
    if (json == null) {
        return json;
    }
    return {
        
        'isFootball': json['is_football'] == null ? undefined : json['is_football'],
        'years': json['years'] == null ? undefined : json['years'],
        'schools': json['schools'] == null ? undefined : ((json['schools'] as Array<any>).map(SportCompensationRankingsSchoolsInnerFromJSON)),
        'conferenceAvgs': json['conference_avgs'] == null ? undefined : json['conference_avgs'],
    };
}

export function SportCompensationRankingsToJSON(json: any): SportCompensationRankings {
    return SportCompensationRankingsToJSONTyped(json, false);
}

export function SportCompensationRankingsToJSONTyped(value?: SportCompensationRankings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_football': value['isFootball'],
        'years': value['years'],
        'schools': value['schools'] == null ? undefined : ((value['schools'] as Array<any>).map(SportCompensationRankingsSchoolsInnerToJSON)),
        'conference_avgs': value['conferenceAvgs'],
    };
}

