/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompensationRow } from './CompensationRow';
import {
    CompensationRowFromJSON,
    CompensationRowFromJSONTyped,
    CompensationRowToJSON,
    CompensationRowToJSONTyped,
} from './CompensationRow';
import type { SchoolNoComp } from './SchoolNoComp';
import {
    SchoolNoCompFromJSON,
    SchoolNoCompFromJSONTyped,
    SchoolNoCompToJSON,
    SchoolNoCompToJSONTyped,
} from './SchoolNoComp';
import type { SportCompensationSubdivision } from './SportCompensationSubdivision';
import {
    SportCompensationSubdivisionFromJSON,
    SportCompensationSubdivisionFromJSONTyped,
    SportCompensationSubdivisionToJSON,
    SportCompensationSubdivisionToJSONTyped,
} from './SportCompensationSubdivision';
import type { SchoolNoSeason } from './SchoolNoSeason';
import {
    SchoolNoSeasonFromJSON,
    SchoolNoSeasonFromJSONTyped,
    SchoolNoSeasonToJSON,
    SchoolNoSeasonToJSONTyped,
} from './SchoolNoSeason';
import type { SportCompensationRankings } from './SportCompensationRankings';
import {
    SportCompensationRankingsFromJSON,
    SportCompensationRankingsFromJSONTyped,
    SportCompensationRankingsToJSON,
    SportCompensationRankingsToJSONTyped,
} from './SportCompensationRankings';
import type { AsstCoachSchool } from './AsstCoachSchool';
import {
    AsstCoachSchoolFromJSON,
    AsstCoachSchoolFromJSONTyped,
    AsstCoachSchoolToJSON,
    AsstCoachSchoolToJSONTyped,
} from './AsstCoachSchool';

/**
 * 
 * @export
 * @interface SportCompensationResponse
 */
export interface SportCompensationResponse {
    /**
     * 
     * @type {number}
     * @memberof SportCompensationResponse
     */
    year?: number;
    /**
     * 
     * @type {string}
     * @memberof SportCompensationResponse
     */
    sportName?: string;
    /**
     * 
     * @type {Array<CompensationRow>}
     * @memberof SportCompensationResponse
     */
    compensations?: Array<CompensationRow>;
    /**
     * 
     * @type {Array<SchoolNoComp>}
     * @memberof SportCompensationResponse
     */
    schoolsNoComp?: Array<SchoolNoComp>;
    /**
     * 
     * @type {Array<SchoolNoSeason>}
     * @memberof SportCompensationResponse
     */
    schoolsNoSeason?: Array<SchoolNoSeason>;
    /**
     * 
     * @type {Array<AsstCoachSchool>}
     * @memberof SportCompensationResponse
     */
    assistantCoaches?: Array<AsstCoachSchool>;
    /**
     * 
     * @type {Array<SportCompensationSubdivision>}
     * @memberof SportCompensationResponse
     */
    subdivisions?: Array<SportCompensationSubdivision>;
    /**
     * 
     * @type {SportCompensationRankings}
     * @memberof SportCompensationResponse
     */
    rankings?: SportCompensationRankings;
}

/**
 * Check if a given object implements the SportCompensationResponse interface.
 */
export function instanceOfSportCompensationResponse(value: object): value is SportCompensationResponse {
    return true;
}

export function SportCompensationResponseFromJSON(json: any): SportCompensationResponse {
    return SportCompensationResponseFromJSONTyped(json, false);
}

export function SportCompensationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SportCompensationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'sportName': json['sport_name'] == null ? undefined : json['sport_name'],
        'compensations': json['compensations'] == null ? undefined : ((json['compensations'] as Array<any>).map(CompensationRowFromJSON)),
        'schoolsNoComp': json['schools_no_comp'] == null ? undefined : ((json['schools_no_comp'] as Array<any>).map(SchoolNoCompFromJSON)),
        'schoolsNoSeason': json['schools_no_season'] == null ? undefined : ((json['schools_no_season'] as Array<any>).map(SchoolNoSeasonFromJSON)),
        'assistantCoaches': json['assistant_coaches'] == null ? undefined : ((json['assistant_coaches'] as Array<any>).map(AsstCoachSchoolFromJSON)),
        'subdivisions': json['subdivisions'] == null ? undefined : ((json['subdivisions'] as Array<any>).map(SportCompensationSubdivisionFromJSON)),
        'rankings': json['rankings'] == null ? undefined : SportCompensationRankingsFromJSON(json['rankings']),
    };
}

export function SportCompensationResponseToJSON(json: any): SportCompensationResponse {
    return SportCompensationResponseToJSONTyped(json, false);
}

export function SportCompensationResponseToJSONTyped(value?: SportCompensationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'sport_name': value['sportName'],
        'compensations': value['compensations'] == null ? undefined : ((value['compensations'] as Array<any>).map(CompensationRowToJSON)),
        'schools_no_comp': value['schoolsNoComp'] == null ? undefined : ((value['schoolsNoComp'] as Array<any>).map(SchoolNoCompToJSON)),
        'schools_no_season': value['schoolsNoSeason'] == null ? undefined : ((value['schoolsNoSeason'] as Array<any>).map(SchoolNoSeasonToJSON)),
        'assistant_coaches': value['assistantCoaches'] == null ? undefined : ((value['assistantCoaches'] as Array<any>).map(AsstCoachSchoolToJSON)),
        'subdivisions': value['subdivisions'] == null ? undefined : ((value['subdivisions'] as Array<any>).map(SportCompensationSubdivisionToJSON)),
        'rankings': SportCompensationRankingsToJSON(value['rankings']),
    };
}

