/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.44.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamScheduleRecentContract
 */
export interface TeamScheduleRecentContract {
    /**
     * 
     * @type {string}
     * @memberof TeamScheduleRecentContract
     */
    schoolName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleRecentContract
     */
    gameContractId?: number;
    /**
     * 
     * @type {string}
     * @memberof TeamScheduleRecentContract
     */
    year?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleRecentContract
     */
    compCents?: number | null;
}

/**
 * Check if a given object implements the TeamScheduleRecentContract interface.
 */
export function instanceOfTeamScheduleRecentContract(value: object): value is TeamScheduleRecentContract {
    return true;
}

export function TeamScheduleRecentContractFromJSON(json: any): TeamScheduleRecentContract {
    return TeamScheduleRecentContractFromJSONTyped(json, false);
}

export function TeamScheduleRecentContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamScheduleRecentContract {
    if (json == null) {
        return json;
    }
    return {
        
        'schoolName': json['school_name'] == null ? undefined : json['school_name'],
        'gameContractId': json['game_contract_id'] == null ? undefined : json['game_contract_id'],
        'year': json['year'] == null ? undefined : json['year'],
        'compCents': json['comp_cents'] == null ? undefined : json['comp_cents'],
    };
}

export function TeamScheduleRecentContractToJSON(json: any): TeamScheduleRecentContract {
    return TeamScheduleRecentContractToJSONTyped(json, false);
}

export function TeamScheduleRecentContractToJSONTyped(value?: TeamScheduleRecentContract | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'school_name': value['schoolName'],
        'game_contract_id': value['gameContractId'],
        'year': value['year'],
        'comp_cents': value['compCents'],
    };
}

