/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TeamScheduleSearchResultAwayContracts } from './TeamScheduleSearchResultAwayContracts';
import {
    TeamScheduleSearchResultAwayContractsFromJSON,
    TeamScheduleSearchResultAwayContractsFromJSONTyped,
    TeamScheduleSearchResultAwayContractsToJSON,
    TeamScheduleSearchResultAwayContractsToJSONTyped,
} from './TeamScheduleSearchResultAwayContracts';
import type { TeamScheduleSearchResultHomeContracts } from './TeamScheduleSearchResultHomeContracts';
import {
    TeamScheduleSearchResultHomeContractsFromJSON,
    TeamScheduleSearchResultHomeContractsFromJSONTyped,
    TeamScheduleSearchResultHomeContractsToJSON,
    TeamScheduleSearchResultHomeContractsToJSONTyped,
} from './TeamScheduleSearchResultHomeContracts';
import type { TeamScheduleContact } from './TeamScheduleContact';
import {
    TeamScheduleContactFromJSON,
    TeamScheduleContactFromJSONTyped,
    TeamScheduleContactToJSON,
    TeamScheduleContactToJSONTyped,
} from './TeamScheduleContact';

/**
 * Enriched team schedule search result with contacts, RPI, returning percentages, and guarantee data
 * @export
 * @interface TeamScheduleSearchResult
 */
export interface TeamScheduleSearchResult {
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleSearchResult
     */
    schoolId?: number;
    /**
     * 
     * @type {string}
     * @memberof TeamScheduleSearchResult
     */
    schoolName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamScheduleSearchResult
     */
    shortName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamScheduleSearchResult
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamScheduleSearchResult
     */
    stateName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamScheduleSearchResult
     */
    conferenceName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleSearchResult
     */
    conferenceId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleSearchResult
     */
    divisionId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleSearchResult
     */
    sportId?: number;
    /**
     * 
     * @type {string}
     * @memberof TeamScheduleSearchResult
     */
    sportName?: string;
    /**
     * Most recent RPI ranking
     * @type {number}
     * @memberof TeamScheduleSearchResult
     */
    lastRpi?: number | null;
    /**
     * 5-year average RPI ranking
     * @type {number}
     * @memberof TeamScheduleSearchResult
     */
    avgRpi?: number | null;
    /**
     * Distance in miles from user's school
     * @type {number}
     * @memberof TeamScheduleSearchResult
     */
    distance?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleSearchResult
     */
    avgGuaranteePaidCents?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleSearchResult
     */
    avgGuaranteeReceivedCents?: number | null;
    /**
     * Win-loss record from previous season (e.g. "22-12")
     * @type {string}
     * @memberof TeamScheduleSearchResult
     */
    previousSeasonRecord?: string | null;
    /**
     * Non-conference games scheduled for current season
     * @type {number}
     * @memberof TeamScheduleSearchResult
     */
    nonConfGamesCurrent?: number;
    /**
     * Non-conference games scheduled for next season
     * @type {number}
     * @memberof TeamScheduleSearchResult
     */
    nonConfGamesNext?: number;
    /**
     * URL to school logo image (small variant)
     * @type {string}
     * @memberof TeamScheduleSearchResult
     */
    schoolLogoUrl?: string | null;
    /**
     * FilTeam ID as string to avoid precision loss
     * @type {string}
     * @memberof TeamScheduleSearchResult
     */
    filTeamId?: string | null;
    /**
     * Percentage of points returning next season
     * @type {number}
     * @memberof TeamScheduleSearchResult
     */
    returningPtsPct?: number | null;
    /**
     * Percentage of rebounds returning next season
     * @type {number}
     * @memberof TeamScheduleSearchResult
     */
    returningRebPct?: number | null;
    /**
     * Percentage of assists returning next season
     * @type {number}
     * @memberof TeamScheduleSearchResult
     */
    returningAstPct?: number | null;
    /**
     * Scheduling contacts for the school/sport
     * @type {Array<TeamScheduleContact>}
     * @memberof TeamScheduleSearchResult
     */
    contacts?: Array<TeamScheduleContact>;
    /**
     * 
     * @type {TeamScheduleSearchResultHomeContracts}
     * @memberof TeamScheduleSearchResult
     */
    homeContracts?: TeamScheduleSearchResultHomeContracts | null;
    /**
     * 
     * @type {TeamScheduleSearchResultAwayContracts}
     * @memberof TeamScheduleSearchResult
     */
    awayContracts?: TeamScheduleSearchResultAwayContracts | null;
}

/**
 * Check if a given object implements the TeamScheduleSearchResult interface.
 */
export function instanceOfTeamScheduleSearchResult(value: object): value is TeamScheduleSearchResult {
    return true;
}

export function TeamScheduleSearchResultFromJSON(json: any): TeamScheduleSearchResult {
    return TeamScheduleSearchResultFromJSONTyped(json, false);
}

export function TeamScheduleSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamScheduleSearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'schoolId': json['school_id'] == null ? undefined : json['school_id'],
        'schoolName': json['school_name'] == null ? undefined : json['school_name'],
        'shortName': json['short_name'] == null ? undefined : json['short_name'],
        'city': json['city'] == null ? undefined : json['city'],
        'stateName': json['state_name'] == null ? undefined : json['state_name'],
        'conferenceName': json['conference_name'] == null ? undefined : json['conference_name'],
        'conferenceId': json['conference_id'] == null ? undefined : json['conference_id'],
        'divisionId': json['division_id'] == null ? undefined : json['division_id'],
        'sportId': json['sport_id'] == null ? undefined : json['sport_id'],
        'sportName': json['sport_name'] == null ? undefined : json['sport_name'],
        'lastRpi': json['last_rpi'] == null ? undefined : json['last_rpi'],
        'avgRpi': json['avg_rpi'] == null ? undefined : json['avg_rpi'],
        'distance': json['distance'] == null ? undefined : json['distance'],
        'avgGuaranteePaidCents': json['avg_guarantee_paid_cents'] == null ? undefined : json['avg_guarantee_paid_cents'],
        'avgGuaranteeReceivedCents': json['avg_guarantee_received_cents'] == null ? undefined : json['avg_guarantee_received_cents'],
        'previousSeasonRecord': json['previous_season_record'] == null ? undefined : json['previous_season_record'],
        'nonConfGamesCurrent': json['non_conf_games_current'] == null ? undefined : json['non_conf_games_current'],
        'nonConfGamesNext': json['non_conf_games_next'] == null ? undefined : json['non_conf_games_next'],
        'schoolLogoUrl': json['school_logo_url'] == null ? undefined : json['school_logo_url'],
        'filTeamId': json['fil_team_id'] == null ? undefined : json['fil_team_id'],
        'returningPtsPct': json['returning_pts_pct'] == null ? undefined : json['returning_pts_pct'],
        'returningRebPct': json['returning_reb_pct'] == null ? undefined : json['returning_reb_pct'],
        'returningAstPct': json['returning_ast_pct'] == null ? undefined : json['returning_ast_pct'],
        'contacts': json['contacts'] == null ? undefined : ((json['contacts'] as Array<any>).map(TeamScheduleContactFromJSON)),
        'homeContracts': json['home_contracts'] == null ? undefined : TeamScheduleSearchResultHomeContractsFromJSON(json['home_contracts']),
        'awayContracts': json['away_contracts'] == null ? undefined : TeamScheduleSearchResultAwayContractsFromJSON(json['away_contracts']),
    };
}

export function TeamScheduleSearchResultToJSON(json: any): TeamScheduleSearchResult {
    return TeamScheduleSearchResultToJSONTyped(json, false);
}

export function TeamScheduleSearchResultToJSONTyped(value?: TeamScheduleSearchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'school_id': value['schoolId'],
        'school_name': value['schoolName'],
        'short_name': value['shortName'],
        'city': value['city'],
        'state_name': value['stateName'],
        'conference_name': value['conferenceName'],
        'conference_id': value['conferenceId'],
        'division_id': value['divisionId'],
        'sport_id': value['sportId'],
        'sport_name': value['sportName'],
        'last_rpi': value['lastRpi'],
        'avg_rpi': value['avgRpi'],
        'distance': value['distance'],
        'avg_guarantee_paid_cents': value['avgGuaranteePaidCents'],
        'avg_guarantee_received_cents': value['avgGuaranteeReceivedCents'],
        'previous_season_record': value['previousSeasonRecord'],
        'non_conf_games_current': value['nonConfGamesCurrent'],
        'non_conf_games_next': value['nonConfGamesNext'],
        'school_logo_url': value['schoolLogoUrl'],
        'fil_team_id': value['filTeamId'],
        'returning_pts_pct': value['returningPtsPct'],
        'returning_reb_pct': value['returningRebPct'],
        'returning_ast_pct': value['returningAstPct'],
        'contacts': value['contacts'] == null ? undefined : ((value['contacts'] as Array<any>).map(TeamScheduleContactToJSON)),
        'home_contracts': TeamScheduleSearchResultHomeContractsToJSON(value['homeContracts']),
        'away_contracts': TeamScheduleSearchResultAwayContractsToJSON(value['awayContracts']),
    };
}

