/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamScheduleCoachesSeasonsInner
 */
export interface TeamScheduleCoachesSeasonsInner {
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleCoachesSeasonsInner
     */
    year?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleCoachesSeasonsInner
     */
    wins?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleCoachesSeasonsInner
     */
    losses?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleCoachesSeasonsInner
     */
    ties?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleCoachesSeasonsInner
     */
    rpi?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TeamScheduleCoachesSeasonsInner
     */
    recordStr?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamScheduleCoachesSeasonsInner
     */
    conferenceRecord?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamScheduleCoachesSeasonsInner
     */
    postseason?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamScheduleCoachesSeasonsInner
     */
    homeRecord?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleCoachesSeasonsInner
     */
    homeWinPercent?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleCoachesSeasonsInner
     */
    sosRanking?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleCoachesSeasonsInner
     */
    offensiveEfficiency?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleCoachesSeasonsInner
     */
    defensiveEfficiency?: number | null;
}

/**
 * Check if a given object implements the TeamScheduleCoachesSeasonsInner interface.
 */
export function instanceOfTeamScheduleCoachesSeasonsInner(value: object): value is TeamScheduleCoachesSeasonsInner {
    return true;
}

export function TeamScheduleCoachesSeasonsInnerFromJSON(json: any): TeamScheduleCoachesSeasonsInner {
    return TeamScheduleCoachesSeasonsInnerFromJSONTyped(json, false);
}

export function TeamScheduleCoachesSeasonsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamScheduleCoachesSeasonsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'wins': json['wins'] == null ? undefined : json['wins'],
        'losses': json['losses'] == null ? undefined : json['losses'],
        'ties': json['ties'] == null ? undefined : json['ties'],
        'rpi': json['rpi'] == null ? undefined : json['rpi'],
        'recordStr': json['record_str'] == null ? undefined : json['record_str'],
        'conferenceRecord': json['conference_record'] == null ? undefined : json['conference_record'],
        'postseason': json['postseason'] == null ? undefined : json['postseason'],
        'homeRecord': json['home_record'] == null ? undefined : json['home_record'],
        'homeWinPercent': json['home_win_percent'] == null ? undefined : json['home_win_percent'],
        'sosRanking': json['sos_ranking'] == null ? undefined : json['sos_ranking'],
        'offensiveEfficiency': json['offensive_efficiency'] == null ? undefined : json['offensive_efficiency'],
        'defensiveEfficiency': json['defensive_efficiency'] == null ? undefined : json['defensive_efficiency'],
    };
}

export function TeamScheduleCoachesSeasonsInnerToJSON(json: any): TeamScheduleCoachesSeasonsInner {
    return TeamScheduleCoachesSeasonsInnerToJSONTyped(json, false);
}

export function TeamScheduleCoachesSeasonsInnerToJSONTyped(value?: TeamScheduleCoachesSeasonsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'wins': value['wins'],
        'losses': value['losses'],
        'ties': value['ties'],
        'rpi': value['rpi'],
        'record_str': value['recordStr'],
        'conference_record': value['conferenceRecord'],
        'postseason': value['postseason'],
        'home_record': value['homeRecord'],
        'home_win_percent': value['homeWinPercent'],
        'sos_ranking': value['sosRanking'],
        'offensive_efficiency': value['offensiveEfficiency'],
        'defensive_efficiency': value['defensiveEfficiency'],
    };
}

