/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamScheduleNote
 */
export interface TeamScheduleNote {
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleNote
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TeamScheduleNote
     */
    content?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TeamScheduleNote
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the TeamScheduleNote interface.
 */
export function instanceOfTeamScheduleNote(value: object): value is TeamScheduleNote {
    return true;
}

export function TeamScheduleNoteFromJSON(json: any): TeamScheduleNote {
    return TeamScheduleNoteFromJSONTyped(json, false);
}

export function TeamScheduleNoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamScheduleNote {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'content': json['content'] == null ? undefined : json['content'],
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function TeamScheduleNoteToJSON(json: any): TeamScheduleNote {
    return TeamScheduleNoteToJSONTyped(json, false);
}

export function TeamScheduleNoteToJSONTyped(value?: TeamScheduleNote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'content': value['content'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

