/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamScheduleDetailSport
 */
export interface TeamScheduleDetailSport {
    /**
     * 
     * @type {number}
     * @memberof TeamScheduleDetailSport
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TeamScheduleDetailSport
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamScheduleDetailSport
     */
    nameDisplay?: string;
}

/**
 * Check if a given object implements the TeamScheduleDetailSport interface.
 */
export function instanceOfTeamScheduleDetailSport(value: object): value is TeamScheduleDetailSport {
    return true;
}

export function TeamScheduleDetailSportFromJSON(json: any): TeamScheduleDetailSport {
    return TeamScheduleDetailSportFromJSONTyped(json, false);
}

export function TeamScheduleDetailSportFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamScheduleDetailSport {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameDisplay': json['name_display'] == null ? undefined : json['name_display'],
    };
}

export function TeamScheduleDetailSportToJSON(json: any): TeamScheduleDetailSport {
    return TeamScheduleDetailSportToJSONTyped(json, false);
}

export function TeamScheduleDetailSportToJSONTyped(value?: TeamScheduleDetailSport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'name_display': value['nameDisplay'],
    };
}

