/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.42.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnauthorizedError
 */
export interface UnauthorizedError {
    /**
     * 
     * @type {string}
     * @memberof UnauthorizedError
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof UnauthorizedError
     */
    errorDescription?: string;
}

/**
 * Check if a given object implements the UnauthorizedError interface.
 */
export function instanceOfUnauthorizedError(value: object): value is UnauthorizedError {
    return true;
}

export function UnauthorizedErrorFromJSON(json: any): UnauthorizedError {
    return UnauthorizedErrorFromJSONTyped(json, false);
}

export function UnauthorizedErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnauthorizedError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'errorDescription': json['error_description'] == null ? undefined : json['error_description'],
    };
}

export function UnauthorizedErrorToJSON(json: any): UnauthorizedError {
    return UnauthorizedErrorToJSONTyped(json, false);
}

export function UnauthorizedErrorToJSONTyped(value?: UnauthorizedError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'error_description': value['errorDescription'],
    };
}

