/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.44.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdatePasswordResetRequestUser } from './UpdatePasswordResetRequestUser';
import {
    UpdatePasswordResetRequestUserFromJSON,
    UpdatePasswordResetRequestUserFromJSONTyped,
    UpdatePasswordResetRequestUserToJSON,
    UpdatePasswordResetRequestUserToJSONTyped,
} from './UpdatePasswordResetRequestUser';

/**
 * 
 * @export
 * @interface UpdatePasswordResetRequest
 */
export interface UpdatePasswordResetRequest {
    /**
     * 
     * @type {UpdatePasswordResetRequestUser}
     * @memberof UpdatePasswordResetRequest
     */
    user: UpdatePasswordResetRequestUser;
}

/**
 * Check if a given object implements the UpdatePasswordResetRequest interface.
 */
export function instanceOfUpdatePasswordResetRequest(value: object): value is UpdatePasswordResetRequest {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function UpdatePasswordResetRequestFromJSON(json: any): UpdatePasswordResetRequest {
    return UpdatePasswordResetRequestFromJSONTyped(json, false);
}

export function UpdatePasswordResetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePasswordResetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UpdatePasswordResetRequestUserFromJSON(json['user']),
    };
}

export function UpdatePasswordResetRequestToJSON(json: any): UpdatePasswordResetRequest {
    return UpdatePasswordResetRequestToJSONTyped(json, false);
}

export function UpdatePasswordResetRequestToJSONTyped(value?: UpdatePasswordResetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UpdatePasswordResetRequestUserToJSON(value['user']),
    };
}

