/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31383324583
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateAdminRequestedItemRequestRequestedItem } from './UpdateAdminRequestedItemRequestRequestedItem';
import {
    UpdateAdminRequestedItemRequestRequestedItemFromJSON,
    UpdateAdminRequestedItemRequestRequestedItemFromJSONTyped,
    UpdateAdminRequestedItemRequestRequestedItemToJSON,
    UpdateAdminRequestedItemRequestRequestedItemToJSONTyped,
} from './UpdateAdminRequestedItemRequestRequestedItem';

/**
 * 
 * @export
 * @interface UpdateAdminRequestedItemRequest
 */
export interface UpdateAdminRequestedItemRequest {
    /**
     * 
     * @type {UpdateAdminRequestedItemRequestRequestedItem}
     * @memberof UpdateAdminRequestedItemRequest
     */
    requestedItem?: UpdateAdminRequestedItemRequestRequestedItem;
}

/**
 * Check if a given object implements the UpdateAdminRequestedItemRequest interface.
 */
export function instanceOfUpdateAdminRequestedItemRequest(value: object): value is UpdateAdminRequestedItemRequest {
    return true;
}

export function UpdateAdminRequestedItemRequestFromJSON(json: any): UpdateAdminRequestedItemRequest {
    return UpdateAdminRequestedItemRequestFromJSONTyped(json, false);
}

export function UpdateAdminRequestedItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAdminRequestedItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'requestedItem': json['requested_item'] == null ? undefined : UpdateAdminRequestedItemRequestRequestedItemFromJSON(json['requested_item']),
    };
}

export function UpdateAdminRequestedItemRequestToJSON(json: any): UpdateAdminRequestedItemRequest {
    return UpdateAdminRequestedItemRequestToJSONTyped(json, false);
}

export function UpdateAdminRequestedItemRequestToJSONTyped(value?: UpdateAdminRequestedItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requested_item': UpdateAdminRequestedItemRequestRequestedItemToJSON(value['requestedItem']),
    };
}

