/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.31386220524
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAdminRequestedItemRequestRequestedItem
 */
export interface UpdateAdminRequestedItemRequestRequestedItem {
    /**
     * 
     * @type {string}
     * @memberof UpdateAdminRequestedItemRequestRequestedItem
     */
    status?: UpdateAdminRequestedItemRequestRequestedItemStatusEnum;
}


/**
 * @export
 */
export const UpdateAdminRequestedItemRequestRequestedItemStatusEnum = {
    Pending: 'pending',
    NotAvailable: 'not_available',
    Received: 'received'
} as const;
export type UpdateAdminRequestedItemRequestRequestedItemStatusEnum = typeof UpdateAdminRequestedItemRequestRequestedItemStatusEnum[keyof typeof UpdateAdminRequestedItemRequestRequestedItemStatusEnum];


/**
 * Check if a given object implements the UpdateAdminRequestedItemRequestRequestedItem interface.
 */
export function instanceOfUpdateAdminRequestedItemRequestRequestedItem(value: object): value is UpdateAdminRequestedItemRequestRequestedItem {
    return true;
}

export function UpdateAdminRequestedItemRequestRequestedItemFromJSON(json: any): UpdateAdminRequestedItemRequestRequestedItem {
    return UpdateAdminRequestedItemRequestRequestedItemFromJSONTyped(json, false);
}

export function UpdateAdminRequestedItemRequestRequestedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAdminRequestedItemRequestRequestedItem {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function UpdateAdminRequestedItemRequestRequestedItemToJSON(json: any): UpdateAdminRequestedItemRequestRequestedItem {
    return UpdateAdminRequestedItemRequestRequestedItemToJSONTyped(json, false);
}

export function UpdateAdminRequestedItemRequestRequestedItemToJSONTyped(value?: UpdateAdminRequestedItemRequestRequestedItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

