/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAccountUserRequestUser
 */
export interface UpdateAccountUserRequestUser {
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateAccountUserRequestUser
     */
    roleSymbols: Array<string>;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdateAccountUserRequestUser
     */
    scheduleSportIds?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdateAccountUserRequestUser
     */
    permissibleSportIds?: Array<number>;
}

/**
 * Check if a given object implements the UpdateAccountUserRequestUser interface.
 */
export function instanceOfUpdateAccountUserRequestUser(value: object): value is UpdateAccountUserRequestUser {
    if (!('roleSymbols' in value) || value['roleSymbols'] === undefined) return false;
    return true;
}

export function UpdateAccountUserRequestUserFromJSON(json: any): UpdateAccountUserRequestUser {
    return UpdateAccountUserRequestUserFromJSONTyped(json, false);
}

export function UpdateAccountUserRequestUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAccountUserRequestUser {
    if (json == null) {
        return json;
    }
    return {
        
        'roleSymbols': json['role_symbols'],
        'scheduleSportIds': json['schedule_sport_ids'] == null ? undefined : json['schedule_sport_ids'],
        'permissibleSportIds': json['permissible_sport_ids'] == null ? undefined : json['permissible_sport_ids'],
    };
}

export function UpdateAccountUserRequestUserToJSON(json: any): UpdateAccountUserRequestUser {
    return UpdateAccountUserRequestUserToJSONTyped(json, false);
}

export function UpdateAccountUserRequestUserToJSONTyped(value?: UpdateAccountUserRequestUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role_symbols': value['roleSymbols'],
        'schedule_sport_ids': value['scheduleSportIds'],
        'permissible_sport_ids': value['permissibleSportIds'],
    };
}

