/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev.36742451352
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSubscriptionAcceptanceRequestSubscription
 */
export interface UpdateSubscriptionAcceptanceRequestSubscription {
    /**
     * Months. One of the lengths the order form offers: 12 or 36 for a standard agreement, otherwise the agreement's own length.
     * @type {number}
     * @memberof UpdateSubscriptionAcceptanceRequestSubscription
     */
    contractTerm: number;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateSubscriptionAcceptanceRequestSubscription
     */
    contractAccepted: boolean;
}

/**
 * Check if a given object implements the UpdateSubscriptionAcceptanceRequestSubscription interface.
 */
export function instanceOfUpdateSubscriptionAcceptanceRequestSubscription(value: object): value is UpdateSubscriptionAcceptanceRequestSubscription {
    if (!('contractTerm' in value) || value['contractTerm'] === undefined) return false;
    if (!('contractAccepted' in value) || value['contractAccepted'] === undefined) return false;
    return true;
}

export function UpdateSubscriptionAcceptanceRequestSubscriptionFromJSON(json: any): UpdateSubscriptionAcceptanceRequestSubscription {
    return UpdateSubscriptionAcceptanceRequestSubscriptionFromJSONTyped(json, false);
}

export function UpdateSubscriptionAcceptanceRequestSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSubscriptionAcceptanceRequestSubscription {
    if (json == null) {
        return json;
    }
    return {
        
        'contractTerm': json['contract_term'],
        'contractAccepted': json['contract_accepted'],
    };
}

export function UpdateSubscriptionAcceptanceRequestSubscriptionToJSON(json: any): UpdateSubscriptionAcceptanceRequestSubscription {
    return UpdateSubscriptionAcceptanceRequestSubscriptionToJSONTyped(json, false);
}

export function UpdateSubscriptionAcceptanceRequestSubscriptionToJSONTyped(value?: UpdateSubscriptionAcceptanceRequestSubscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contract_term': value['contractTerm'],
        'contract_accepted': value['contractAccepted'],
    };
}

