/* tslint:disable */
/* eslint-disable */
/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserScheduleSportsInner } from './UserScheduleSportsInner';
import {
    UserScheduleSportsInnerFromJSON,
    UserScheduleSportsInnerFromJSONTyped,
    UserScheduleSportsInnerToJSON,
    UserScheduleSportsInnerToJSONTyped,
} from './UserScheduleSportsInner';
import type { Division } from './Division';
import {
    DivisionFromJSON,
    DivisionFromJSONTyped,
    DivisionToJSON,
    DivisionToJSONTyped,
} from './Division';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastName?: string;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    state?: UserStateEnum;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    title?: string;
    /**
     * The user's account ID
     * @type {number}
     * @memberof User
     */
    accountId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    accountableId?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    accountableType?: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    coachId?: number;
    /**
     * 
     * @type {Array<Division>}
     * @memberof User
     */
    divisions?: Array<Division>;
    /**
     * 
     * @type {Array<string>}
     * @memberof User
     */
    roles?: Array<string>;
    /**
     * Whether the user is a data admin or super admin
     * @type {boolean}
     * @memberof User
     */
    isAdmin?: boolean;
    /**
     * Whether the user can view coach compensation data
     * @type {boolean}
     * @memberof User
     */
    canSeeCompensation?: boolean;
    /**
     * Whether the user can view scouting/team schedule links
     * @type {boolean}
     * @memberof User
     */
    canShowScouting?: boolean;
    /**
     * Whether the user can view game contract/guarantee data
     * @type {boolean}
     * @memberof User
     */
    canShowGameContract?: boolean;
    /**
     * Whether the user can access the Coaches section
     * @type {boolean}
     * @memberof User
     */
    canSeeCoaches?: boolean;
    /**
     * Whether the user can access the Administrators section
     * @type {boolean}
     * @memberof User
     */
    canSeeAdministrators?: boolean;
    /**
     * Whether the user can access the Financials section
     * @type {boolean}
     * @memberof User
     */
    canShowFinancials?: boolean;
    /**
     * Whether the user can access the Vendors section
     * @type {boolean}
     * @memberof User
     */
    canShowDeals?: boolean;
    /**
     * Whether the user can access the Benchmark section
     * @type {boolean}
     * @memberof User
     */
    canShowBenchmark?: boolean;
    /**
     * Whether the user can access the Departments section
     * @type {boolean}
     * @memberof User
     */
    canShowAthleticProfile?: boolean;
    /**
     * Whether the user can access the Conferences section
     * @type {boolean}
     * @memberof User
     */
    canReadConference?: boolean;
    /**
     * Whether the user can access the Games Wanted section
     * @type {boolean}
     * @memberof User
     */
    canShowGamePost?: boolean;
    /**
     * Whether the user can access Custom School Groups
     * @type {boolean}
     * @memberof User
     */
    canSeeSchoolGroups?: boolean;
    /**
     * Whether the user can view account management
     * @type {boolean}
     * @memberof User
     */
    canReadAccount?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isSportSpecific?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isD2Only?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isConferenceOnly?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof User
     */
    permissibleSportIds?: Array<number> | null;
    /**
     * Cost of living index for the user's school
     * @type {number}
     * @memberof User
     */
    coliIndex?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    subscriptionType?: string | null;
    /**
     * Sports the user can access for game scheduling
     * @type {Array<UserScheduleSportsInner>}
     * @memberof User
     */
    scheduleSports?: Array<UserScheduleSportsInner>;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    schoolCity?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    schoolState?: string | null;
    /**
     * Whether the user must verify OTP to access the application
     * @type {boolean}
     * @memberof User
     */
    otpRequired?: boolean;
    /**
     * User's time zone setting
     * @type {string}
     * @memberof User
     */
    timeZone?: string | null;
    /**
     * Whether user receives scheduling notifications
     * @type {boolean}
     * @memberof User
     */
    schedulingNotifications?: boolean;
    /**
     * Whether user receives games wanted notifications
     * @type {boolean}
     * @memberof User
     */
    gamePostNotifications?: boolean;
    /**
     * Whether user receives scheduling digest emails
     * @type {boolean}
     * @memberof User
     */
    gamesDigest?: boolean;
    /**
     * Email domain required by the user's account
     * @type {string}
     * @memberof User
     */
    emailDomain?: string | null;
}


/**
 * @export
 */
export const UserStateEnum = {
    Created: 'created',
    Suspended: 'suspended',
    Active: 'active',
    Pending: 'pending'
} as const;
export type UserStateEnum = typeof UserStateEnum[keyof typeof UserStateEnum];


/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'state': json['state'] == null ? undefined : json['state'],
        'title': json['title'] == null ? undefined : json['title'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'accountableId': json['accountable_id'] == null ? undefined : json['accountable_id'],
        'accountableType': json['accountable_type'] == null ? undefined : json['accountable_type'],
        'coachId': json['coach_id'] == null ? undefined : json['coach_id'],
        'divisions': json['divisions'] == null ? undefined : ((json['divisions'] as Array<any>).map(DivisionFromJSON)),
        'roles': json['roles'] == null ? undefined : json['roles'],
        'isAdmin': json['is_admin'] == null ? undefined : json['is_admin'],
        'canSeeCompensation': json['can_see_compensation'] == null ? undefined : json['can_see_compensation'],
        'canShowScouting': json['can_show_scouting'] == null ? undefined : json['can_show_scouting'],
        'canShowGameContract': json['can_show_game_contract'] == null ? undefined : json['can_show_game_contract'],
        'canSeeCoaches': json['can_see_coaches'] == null ? undefined : json['can_see_coaches'],
        'canSeeAdministrators': json['can_see_administrators'] == null ? undefined : json['can_see_administrators'],
        'canShowFinancials': json['can_show_financials'] == null ? undefined : json['can_show_financials'],
        'canShowDeals': json['can_show_deals'] == null ? undefined : json['can_show_deals'],
        'canShowBenchmark': json['can_show_benchmark'] == null ? undefined : json['can_show_benchmark'],
        'canShowAthleticProfile': json['can_show_athletic_profile'] == null ? undefined : json['can_show_athletic_profile'],
        'canReadConference': json['can_read_conference'] == null ? undefined : json['can_read_conference'],
        'canShowGamePost': json['can_show_game_post'] == null ? undefined : json['can_show_game_post'],
        'canSeeSchoolGroups': json['can_see_school_groups'] == null ? undefined : json['can_see_school_groups'],
        'canReadAccount': json['can_read_account'] == null ? undefined : json['can_read_account'],
        'isSportSpecific': json['is_sport_specific'] == null ? undefined : json['is_sport_specific'],
        'isD2Only': json['is_d2_only'] == null ? undefined : json['is_d2_only'],
        'isConferenceOnly': json['is_conference_only'] == null ? undefined : json['is_conference_only'],
        'permissibleSportIds': json['permissible_sport_ids'] == null ? undefined : json['permissible_sport_ids'],
        'coliIndex': json['coli_index'] == null ? undefined : json['coli_index'],
        'subscriptionType': json['subscription_type'] == null ? undefined : json['subscription_type'],
        'scheduleSports': json['schedule_sports'] == null ? undefined : ((json['schedule_sports'] as Array<any>).map(UserScheduleSportsInnerFromJSON)),
        'schoolCity': json['school_city'] == null ? undefined : json['school_city'],
        'schoolState': json['school_state'] == null ? undefined : json['school_state'],
        'otpRequired': json['otp_required'] == null ? undefined : json['otp_required'],
        'timeZone': json['time_zone'] == null ? undefined : json['time_zone'],
        'schedulingNotifications': json['scheduling_notifications'] == null ? undefined : json['scheduling_notifications'],
        'gamePostNotifications': json['game_post_notifications'] == null ? undefined : json['game_post_notifications'],
        'gamesDigest': json['games_digest'] == null ? undefined : json['games_digest'],
        'emailDomain': json['email_domain'] == null ? undefined : json['email_domain'],
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'state': value['state'],
        'title': value['title'],
        'account_id': value['accountId'],
        'accountable_id': value['accountableId'],
        'accountable_type': value['accountableType'],
        'coach_id': value['coachId'],
        'divisions': value['divisions'] == null ? undefined : ((value['divisions'] as Array<any>).map(DivisionToJSON)),
        'roles': value['roles'],
        'is_admin': value['isAdmin'],
        'can_see_compensation': value['canSeeCompensation'],
        'can_show_scouting': value['canShowScouting'],
        'can_show_game_contract': value['canShowGameContract'],
        'can_see_coaches': value['canSeeCoaches'],
        'can_see_administrators': value['canSeeAdministrators'],
        'can_show_financials': value['canShowFinancials'],
        'can_show_deals': value['canShowDeals'],
        'can_show_benchmark': value['canShowBenchmark'],
        'can_show_athletic_profile': value['canShowAthleticProfile'],
        'can_read_conference': value['canReadConference'],
        'can_show_game_post': value['canShowGamePost'],
        'can_see_school_groups': value['canSeeSchoolGroups'],
        'can_read_account': value['canReadAccount'],
        'is_sport_specific': value['isSportSpecific'],
        'is_d2_only': value['isD2Only'],
        'is_conference_only': value['isConferenceOnly'],
        'permissible_sport_ids': value['permissibleSportIds'],
        'coli_index': value['coliIndex'],
        'subscription_type': value['subscriptionType'],
        'schedule_sports': value['scheduleSports'] == null ? undefined : ((value['scheduleSports'] as Array<any>).map(UserScheduleSportsInnerToJSON)),
        'school_city': value['schoolCity'],
        'school_state': value['schoolState'],
        'otp_required': value['otpRequired'],
        'time_zone': value['timeZone'],
        'scheduling_notifications': value['schedulingNotifications'],
        'game_post_notifications': value['gamePostNotifications'],
        'games_digest': value['gamesDigest'],
        'email_domain': value['emailDomain'],
    };
}

