/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.41.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CoachCompensation {
    'coachId'?: number;
    'estimated'?: boolean;
    /**
    * The base salary (rounded to 2 decimal places)
    */
    'salary'?: number;
    'year'?: number;
    'coliSalary'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "coachId",
            "baseName": "coach_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "estimated",
            "baseName": "estimated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "salary",
            "baseName": "salary",
            "type": "number",
            "format": "float"
        },
        {
            "name": "year",
            "baseName": "year",
            "type": "number",
            "format": ""
        },
        {
            "name": "coliSalary",
            "baseName": "coli_salary",
            "type": "number",
            "format": "float"
        }    ];

    static getAttributeTypeMap() {
        return CoachCompensation.attributeTypeMap;
    }

    public constructor() {
    }
}
