/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.39.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FoiaRequest {
    'id'?: number;
    'schoolId': number;
    'createdById'?: number;
    'updatedById'?: number;
    'state': FoiaRequestStateEnum;
    'foiaLabelId'?: number;
    'createdAt'?: Date;
    'updatedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "schoolId",
            "baseName": "school_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdById",
            "baseName": "created_by_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "updatedById",
            "baseName": "updated_by_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "FoiaRequestStateEnum",
            "format": ""
        },
        {
            "name": "foiaLabelId",
            "baseName": "foia_label_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return FoiaRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum FoiaRequestStateEnum {
    Active = 'ACTIVE',
    Archived = 'ARCHIVED'
}

