/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.41.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JobCandidate } from '../models/JobCandidate';
import { JobDepartment } from '../models/JobDepartment';
import { JobSchool } from '../models/JobSchool';
import { JobSport } from '../models/JobSport';
import { HttpFile } from '../http/http';

export class Job {
    'id'?: number;
    'title'?: string;
    'description'?: string;
    'jobUrl'?: string;
    'postedAt'?: Date;
    'createdAt'?: Date;
    'school'?: JobSchool;
    'departments'?: Array<JobDepartment>;
    'sports'?: Array<JobSport>;
    'candidates'?: Array<JobCandidate>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "jobUrl",
            "baseName": "job_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "postedAt",
            "baseName": "posted_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "school",
            "baseName": "school",
            "type": "JobSchool",
            "format": ""
        },
        {
            "name": "departments",
            "baseName": "departments",
            "type": "Array<JobDepartment>",
            "format": ""
        },
        {
            "name": "sports",
            "baseName": "sports",
            "type": "Array<JobSport>",
            "format": ""
        },
        {
            "name": "candidates",
            "baseName": "candidates",
            "type": "Array<JobCandidate>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Job.attributeTypeMap;
    }

    public constructor() {
    }
}
