/**
 * Winthrop Intelligence Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.40.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Logo {
    /**
    * Signed, expiring url for the original logo image
    */
    'originalUrl'?: string;
    /**
    * Signed, expiring url for the medium logo image
    */
    'mediumUrl'?: string;
    /**
    * Signed, expiring url for the small logo image
    */
    'smallUrl'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "originalUrl",
            "baseName": "original_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "mediumUrl",
            "baseName": "medium_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "smallUrl",
            "baseName": "small_url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Logo.attributeTypeMap;
    }

    public constructor() {
    }
}
